<?php 
echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); 
function InitStyle() { return " font-style: italic; color: grey;"; }
?>


<h1 class="title">ITスキル診断状況管理</h1>

<form id="form" method="post" action="./editconfirm">
	<style type="text/css">
		option { color: black; }
		/* input::placeholder { font-style: italic; } */
	</style>

	<div class="emegra card">
		<div class="card-header">ITスキル診断者情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns:  repeat(2, 170px 1fr) }
			</style>
			<dl class="emegra info">
				<dt>ID</dt>
				<dd><input class="form-control" name="id" type="text" style="width:50%; text-align:center;" value="tanaka@gmail.com"></dd>
				
                <dt class="essential">応募区分</dt>
				<select class="form-select" name="application_category" style="width:40%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
                        <option value="" selected disabled hidden>選択してください。</option>
                        <option value="0">新卒</option>
                        <option value="1">中途（経歴職）</option>
                    </select>

                <dt>パスワード</dt>
				<dd><input class="form-control" name="password" type="text" style="width:50%; text-align:center;" value="A1b3c4"></dd>

				<dt class="essential">お名前（漢字）</dt>
				<dd><input class="form-control" id="userInput" name="name" type="text" placeholder="漢字を記入してください。"style="width:80%" maxlength='20'></dd>

                <dt>申込日</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:50%; text-align:center;" value="2024.5.6"></dd>
				
                <dt class="essential">お名前（カナ）</dt>
				<dd><input class="form-control" name="kana" type="text" placeholder="カナを記入してください。"style="width:80%" maxlength='50'></dd>

                <dt>性別</dt>
				<dd> 
					<select class="form-select"  name="gender" style="width:20%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
                        <option selected disabled hidden>選択</option>
                        <option value="0">男</option>
                        <option value="1">女</option>
                    </select>
				</dd>
				
                <dt class="essential">学歴</dt>
				<dd>
					<select class="form-select" name="education" style="width:40%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" id="educationSelect" >
                        <option value=""selected disabled hidden>選択してください。</option>
                        <option value="高卒">高卒</option>
                        <option value="専門卒">専門卒</option>
                        <option value="大卒">大卒</option>
                        <option value="大学院卒">大学院卒</option>
                        <option value="その他">その他</option>
                    </select>
                    <div id="otherEducationInput" style=" margin-top:-15px; display:none;">
                        <input class="form-control" type="text" placeholder="その他の場合の、記入" id="otherEducation" name="education" maxlength='20'>
                    </div>
				</dd>

                <dt>生年月日</dt>
				<dd><input class="form-control" id="birth" name="birth" type="text" placeholder="YYYY-MM-DD" autocomplete="off"  style="width:50%"></dd> 


			</dl>
		</div>
	</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">診断者ITスキル有無</div>

	<div class="card-body">
		<style type="text/css">

		dl.emegra.setting { grid-template-columns: repeat(1, 180px 1fr); }
				</style>
		<dl class="emegra setting">
                <dt class="essential">ITスキル有無</dt>
				<dd>
					<select class="form-select" name="skill" style="width:20%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
                        <option value="" selected disabled hidden>選択</option>
                        <option value="0">有</option>
                        <option value="1">無</option>
                    </select>
				</dd>

                <dt class="essential">経験分野</dt>
				<dd>
					<select class="form-select" name="develop" style="width:20%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" id="developSelect" >
						<option value="" selected  >選択してください。</option>
							<?php foreach ($this->develop as $row): ?>
								<?php $texts = explode(',', $row['text']); ?>
								<?php foreach ($texts as $text): ?>
									<option value="<?php echo $text; ?>"><?php echo $text; ?></option>
								<?php endforeach; ?>
							<?php endforeach; ?>
                    </select>
                    <div id="otherDevelopInput" style="margin-top:-15px; display:none;">
                        <input class="form-control" type="text" placeholder="その他の場合の、記入" id="otherDevelop" name="develop" maxlength='20'>
                    </div>
				</dd>

				<dt class="essential">IT経験年数</dt>
				<dd><input class="form-control" id="career" name="career" type="text" placeholder="経歴を記入してください。" style="font-size:15px; width:20%" maxlength='2'></dd> 

				<dt class="essential">問題種別</dt>
				<dd>
					<select class="form-select" name="question_type" style="width:20%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" id="typeSelect">
						<option value="" selected  >選択してください。</option>
						<?php foreach ($this->questionType as $row): ?>
							<?php $texts = explode(',', $row['text']); ?>
							<?php foreach ($texts as $text): ?>
								<option value="<?php echo $text; ?>"><?php echo $text; ?></option>
							<?php endforeach; ?>
						<?php endforeach; ?>
                    </select>
				</dd>

		</dl>
	</div>
</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">ITスキル診断問項詳細</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 140px 1fr); }
		</style>
		<dl class="emegra detail">
                <dt>診断依頼</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:30%; text-align:center;" value="2024.5.6"></dd>

				<dt class="essential">診断問項ID</dt>
				<dd>B-50-T1</dd> 

				<dt class="essential">レベル</dt>
				<dd>初級</dd>

				<dt class="essential">問項数別</dt>
				<dd>50問</dd>
		
				<dt class="essential">診断方法</dt>
                <dd style="grid-column: 2 / 5;">
					<select class="form-select" style="width:13%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
                        <option value="" selected disabled hidden>選択</option>
                        <option value="0">WEB</option>
                        <option value="1">対面</option>
                    </select>
				</dd>
		</dl>
	</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">ITスキル診断状況</div>

		<div class="card-body">
			<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 150px 1fr); }
			</style>
			<dl class="emegra detail">
				<dt>診断実施日</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:30%; text-align:center;" value="2024.5.6"></dd>

				<dt>得点</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:30%; text-align:center;" value="76"></dd> 

				<dt>評価等級</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:30%; text-align:center;" value="B"></dd>

				<dt>診断者のコメント</dt>
				<dd></dd>
		
				<dt>備考</dt>
				<dd></dd>
			</dl>
		</div>
	</div>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="self.location.href='./list';">戻る</button>
	<button class="emegra" style="width:150px;" onclick="self.location.href='./editconfirm';">ITスキル診断依頼</button>
</div>

<script type="text/javascript">
	const smtp = document.getElementById("smtp");
	const form = document.getElementById("form");
	const pattern = /^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-za-z0-9\-]+/;

	function ActiveSmtp(value) {
		if (value == "y") { smtp.disabled = false; }
		else { smtp.disabled = true; }
	}

	function Regist() {
		if (form.code.value == "") {
			alert("職別コードを入力してください");
			setTimeout("form.code.focus();", 100);
			return false;
		}
		
		if (form.id.value == "") {
			alert("IDを入力してください");
			setTimeout("form.id.focus()", 100);
			return false;
		}
		
		if (pattern.test(form.id.value) === false) {
			alert("IDを確認してください");
			setTimeout("form.id.focus()", 100);
			return false;
		}
		
		if (form.password.value == "") {
			alert("パスワードを入力してください");
			setTimeout("form.password.focus()", 100);
			return false;
		}
		
		if (form.name.value == "") {
			alert("名前を入力してください");
			setTimeout("form.name.focus()", 100);
			return false;
		}
		
		if (smtp.disabled == false && smtp.value == "") {
			alert("SMTPを入力してください");
			setTimeout("smtp.focus()", 100);
			return false;
		}

		form.submit();
	}
</script>
<script>
	function ChangeInputStyle(element) {
		element.style.fontStyle = "normal";
		element.style.color = "black";
	}
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">

  <script>
    $(document).ready(function(){
      var birth = document.getElementById("birth");
      $(birth).datepicker({
        format: 'yyyy-mm-dd',
        autohide: true
      });
    });
  </script>