<!-- 修正
作成：丁錫圓
作成日：2024/02/21
修正前：
<!doctype html>
<html lang="jp">

<head>
   Required meta tags 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

   Bootstrap CSS 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
  html {
    height: 100%
  }

  #logo {

    color: #000000;
    font-weight: bold;
    font-size: 32px;
    text-transform: uppercase;
    padding: 5px;
    margin-bottom: 20px;
    background: linear-gradient(to right, #270a09, #8ca6ce);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  </style>
  <title>試験管理サイト</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
  <style type='text/css'>
  body,
  p,
  div,
  span,
  a,
  textarea,
  input,
  select,
  i,
  button,
  h5,
  h4,
  h3,
  h2,
  h1 {
    font-family: 'Noto Sans JP', sans-serif;
  }
  </style>
</head>

<body class="h-100">
  <div class="position-relative h-100" id="content">
    <div class="d-flex flex-column align-items-center position-absolute top-50 start-50 translate-middle">
      <p class="h1 text-center" id="logo">G&G TEST MANAGEMENT</p>
      <form class="d-flex flex-column" id="form_login" style="width: 350px;" method="post">
        <div class="d-flex border-0 mb-1">
          <span style="min-width: 80px;">ID</span>
          <input class="form-control" name="id" type="email" placeholder="IDを入力ください">
        </div>
        <div class="d-flex border-0 mb-1">
          <span style="min-width: 80px;">Password</span>
          <input class="form-control" name="password" type="password" placeholder="パスワードを入力ください">
        </div>
        <button class="btn btn-primary mt-3" id="bt_login" type="button">ログイン</button>
      </form>
    </div>
  </div>

  <script>
  const form = document.getElementById("form_login");

  document.getElementById("bt_login").addEventListener("click", function() {
    if (form.id.value == "") {
      alert("IDを入力ください");
      form.id.focus();
      return false;
    }

    if (!form.id.checkValidity()) {
      alert("IDがEメール形式ではありません");
      form.id.focus();
      return false;
    }

    if (form.password.value == "") {
      alert("パスワードを入力ください");
      form.password.focus();
      return false;
    }

    if (form.password.value.length <= 7) {
      alert("8文字以上入力してください");
      form.password.focus();
      return false;
    }

    const postForm = new FormData();
    postForm.append("id", form.id.value);
    postForm.append("password", form.password.value);

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "./login", true);
    xhr.send(postForm);

    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        if (result == "no id") {
          alert("登録されてないIDです");
          form.id.focus();
        } else if (result == "wrong pw") {
          alert("パスワードを確認してください");
          form.password.focus();
        } else if (result == "success") {
          sessionStorage.setItem("user", form.id.value);
          self.location.href = "./exam/list?page=1";
        }
      }
    }
  });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

</body>

</html> 
修正後：
-->
<!doctype html>
<html lang="jp">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>

  </style>
  <title>試験管理サイト</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
  <link href="/css/layout_sw.css" rel="stylesheet" type="text/css">

  <style type='text/css'>
  </style>
  <style>
    body {
      background-image: url(/img/btn_back_bp.svg);
      background-size: cover;
      background-attachment: fixed;
      background-position: center;
    }

    .vectors {
      z-index: 1;
      background-image: url(/img/login_back_vector.png);
      background-size: 100% 100%;
      right: 0;
      bottom: 0;
      width: 70%;
      height: calc(80%);
      position: fixed;
      background-position: center;
    }
    .gnglogos {
      background-image: url(/img/login_backlogo.png);
      background-size: 80% auto;
      background-repeat: no-repeat;
      background-position: center;
      z-index: 1;
      position: fixed;
      width: 100%;
      height: 100%;
      margin-top:-100px;
    }
    main{
		position: fixed;
		width: 100%;
		height: 100%;
		z-index: 10;
		align-items: center;
		justify-content: center;
		display: flex;
    margin-top:-100px;
	}
  </style>
</head>
<body class="hidden-sn mdb-skin">
<header>
		<div class="fixed-top" style="padding: 20px; color: white;"><img src="/img/hd_logo.png" style="width: 150px; padding-bottom: 10px;"></div>
	</header>
  <main>
  <style type="text/css">
			.ttitle{
				text-align: center;	
				font-size: 25px;
				font-weight: bold;
        min-width:350px;
        margin-top:16px
			}
			.loginid{
				font-weight: 700;
				font-size: 15px;
			}

			.loginpw{
				font-weight: 700;
				font-size: 15px;
			}

			.loginbtn{
				background-image: url(/img/btn_back_bp.svg);
				background-repeat: no-repeat;
				background-size: cover;
				border-radius: 5px;
				background-size: 100% auto;
				border:0;
        width:100%;
        padding:20px;
			}
      .card{
        padding:40px;
        border-radius:6px;
      }
      .logins{
        padding:10px 20px;
      }
      .passwords{
        padding:10px 20px;
      }
      .buttons{
        padding:20px;
      }
		</style>
  <div class="col-sm-8 col-xs-8 col-md-7 col-xl-6 co-lg-5 col-12">
    <div class="card"> 
      <p class="ttitle">G&G「試験管理者」ログイン</p>
      <form class="" id="form_login" style="width: 100%;" method="post">
          <div class='logins'>
          <p class="loginid">ID</p>
            <input class="form-control loginidbox" name="id" type="email" placeholder="IDを入力ください">
          </div>
          <div class='passwords'>
          <p class="loginpw">Password</p>
            <input class="form-control loginpwbox" name="password" type="password" placeholder="パスワードを入力ください">
          </div>
          <div class='buttons'>
            <button class="loginbtn" id="bt_login" type="button" style="color: white;">ログイン</button>
          </div>
      </form>
    </div>
  </div>
</main>
  <div class="vectors"></div>
  <div class="gnglogos"></div>
<footer>
      <div class="">
          <div class='text-muted text-center'>
              <p style='background-color:#;color:white;font-size:11px;padding:7px;margin:0;margin-top:100px;'>
              <div class="fixed-bottom" style="margin-bottom: 30px; font-size: 10px; color: white;"><a
                      href='/' style='color:white; text-decoration:border;'
                      target='_blank'>G&GService Test Management</a> &nbsp; Copyright G&GService All Right
                  Reserved
              </div>
          </div>
      </div>
  </footer>
  <script>
  const form = document.getElementById("form_login");

  document.getElementById("bt_login").addEventListener("click", function() {
    if (form.id.value == "") {
      alert("IDを入力ください");
      form.id.focus();
      return false;
    }

    if (!form.id.checkValidity()) {
      alert("IDがEメール形式ではありません");
      form.id.focus();
      return false;
    }

    if (form.password.value == "") {
      alert("パスワードを入力ください");
      form.password.focus();
      return false;
    }

    if (form.password.value.length <= 7) {
      alert("8文字以上入力してください");
      form.password.focus();
      return false;
    }

    const postForm = new FormData();
    postForm.append("id", form.id.value);
    postForm.append("password", form.password.value);

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "./login", true);
    xhr.send(postForm);

    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        if (result == "no id") {
          alert("登録されてないIDです");
          form.id.focus();
        } else if (result == "wrong pw") {
          alert("パスワードを確認してください");
          form.password.focus();
        } else if (result == "success") {
          sessionStorage.setItem("user", form.id.value);
          self.location.href = "./exam/list?page=1";
        }
      }
    }
  });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

</body>

</html>
<!-- ここまで  -->