<div class="emegra card">
	こんにちは　<?php echo $name; ?>　様<br/>
	試験が始まります<br/>
	一度だけ受けません<br/>
	<br/>
	ボタンを押すとすぐ始まります<br/>
	<br/>
	受けますか？<br/>

</div>

<form id="form" method="post">
	<input name="start" type="hidden"/>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra" onclick="Submit();">受ける</button>
</div>

<script type="text/javascript">
	function Submit() {
		form.submit();
	}
</script>