<?php
$ses_id = (isset($_SESSION['applicant']) && !empty($_SESSION['applicant'])) ? $_SESSION['applicant'] : '';
if ($ses_id) {
    if ($_SESSION['applicant']['id']) {
        $logged = true;
    } else {
        $logged = false;
    }
} else {
    $logged = false;
}

?>
<?php if ($logged == true): ?>
<header>
	<div class="left-column"><img src="/img/hd_logo.png" alt="logo" height="40px" width="auto"></div>
	<div class="middle-column" style="font-size:bold">ITスキル診断</div>
	<div class="right-column"> 
    <div id="date-container" style="display:flex; align-items:center"></div>
    <div style="text-align:center;display:flex; align-items:center;margin-left: 10px; "><?php echo $name; ?></div>
    <div id="timerDisplay" style=" display:flex; align-items:center"></div>
    <button class=" btn btn-sm" id="stopBtn" style=" display:flex; align-items:center; text-align:center;color:yellow; border:none;"  data-bs-toggle="modal" data-bs-target="#staticBackdrop2">一時停止</button>
</div>
</header>	     

<div class="container-fluid">
  <div class="card emegra" >
    <div class="card-body"style="margin-top:70px;">
    <form id="myForm" name="input_form" action="/applicant/exam" method="post">
        <div  class="welcomeText">
          <p style="font-weight: bold; font-size: 20px; text-align:center;"><?php echo $name; ?>様</p>         
          <p>表示される問題に従って回答してください。</p>			
          <p style="color:red;">※ ページ上部の一時停止ボタンを押すと10分間停止し、1回のみ使用可能です。</p>	
        </div>
        <div style="padding:0px 50px;">
          <p style="margin-top:20px;font-weight:bold;">問題数　　<?php echo $question_num; ?>問				</p>				  
          <?php $count = 1; 
          foreach ($matchedData as $idx => $row) : 
          $question_ko = $idx + 1 . ". " . $row["question_ko"];
          $question_jp = $idx + 1 . ". " . $row["question"];
          ?>
            
        <div class="examBox" style="width:100%; display: <?= $count === 1 ? 'block' : 'none' ?>;" id="exam<?= $count ?>">
          <div class="question" style="margin-left:50px;font-weight:bold;" id="<?= $row['idx'] ?>">問題 <?= $language==1 && $row["question_ko"] != null ?  $question_ko : $question_jp ?></div>
            <div class="card-body" style="margin-left: 100px;">
                <div class="answers mt-2">
                    <ul class="list-unstyled">
                        <?php for ($i = 1; $i <= 5; $i++) : ?>
                            <?php 
                            $answerKey = "answer$i";
                            $answerKey_ko = "answer$i"."_ko";
                            $answer_ko = htmlspecialchars($row[$answerKey_ko], ENT_QUOTES);
                            $answer_jp = htmlspecialchars($row[$answerKey], ENT_QUOTES);
                            if (!empty($row[$answerKey])) :
                            ?>
                                <li style="padding: 10px 0">
                                    <input type="radio" name="answer<?= $idx + 1 ?>" value="<?= $i ?>"> <?php echo $language == 1 && $answer_ko != null? $answer_ko : $answer_jp ?>
                                </li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </ul>
                </div>
                <div class="questionNext" id="nextId" onclick="showNextQuestion(<?= $count ?>)">次へ</div>
            </div>
          </div>
        <?php $count++; ?>  
      <?php endforeach; ?>

<script>
    let forms= document.getElementById('myForm');
    let currentNumber =1;
    let ischeck= true;
    function showNextQuestion(current) {
        const currentExam = document.getElementById('exam' + current);
        const nextExam = document.getElementById('exam' + (current + 1));
        if(forms.elements['answer' + currentNumber].value == ""){
          alert("問題を全部入力してください。")
          ischeck = false;
          return false;
        }
        currentNumber++;
        if (currentExam) currentExam.style.display = 'none';
        if (nextExam) nextExam.style.display = 'block';
        if (!nextExam) btn_submit.click();

        }
</script>
    <input type="hidden" id="answer_data" name="answer_data">
        <div class="comment">
          <p style="margin-top:50px;font-weight:bold;">コメント　　　　　　　　 <input class="w-75" type="text" name="comment" id="comment" placeholder="自由に記載"></p>
        </div>
    <div class="button_box" style="margin-bottom: 32px; gap:30px">
      <button  class="applicant_cancel" id="cancel" name="submit_post"  value="cancel" onclick="window.location.href='../applicant/login';">キャンセル</button>
      <button type="button" class="exam_submit" id='btn_submit' name="submit_post"  value="btn_submit" >提出</button>
    </div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="margin-top:150px">
    <div class="modal-content rounded-4">
      <div class="modal-header" style="background:linear-gradient(111deg, #87D782 0%, #22BC8E 100%);color:white; height: 40px;border-top-left-radius:13px;border-top-right-radius:13px">
        <h5 class="modal-title" id="exampleModalLabel">正答確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="filter: invert(100%);"></button>
      </div>
      <div class="modal-body fs-5" style="padding-bottom:0">
      <div id="confirmContent" style="text-align:center;"></div>
      <!-- <div id="confirmComment"></div> -->
      </div>
      <div class="modal-footer  border-top-0" style="margin-bottom:8px; justify-content:center;">
    <button type="button" class="applicant_cancel" data-bs-dismiss="modal">キャンセル</button>
    <button type="submit" class="exam_submit" name="submit_post" value="btn_submit">登録</button>
    </div>
  </div>
  </div>
</div>
<button type="submit" class="timeout_submit" name="submit_post" value="btn_submit" hidden></button>

</form>


<!-- modal -->
<button type="button" class="btn btn-primary" id="loadPage" data-bs-toggle="modal" data-bs-target="#staticBackdrop" style="display:none"></button>
			<div class="modal modal-sheet py-5" style="backdrop-filter: blur(100px);--bs-modal-width: 700px " tabindex="-1" role="dialog" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
				<div class="modal-dialog" style="margin-top:100px;" role="document">
					<div class="modal-content rounded-4">
					<div class="modal-header border-bottom-0" style="background:linear-gradient(111deg, #87D782 0%, #22BC8E 100%); padding:10px 0px; font-size:20px; justify-content:center; color:white;border-top-left-radius:13px;border-top-right-radius:13px">株式会社ジエンジサービス
					<h3 class="modal-title fs-5" id="exampleModalLabel"></h3>
						<!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
					</div>
					<div class="modal-body fs-5">
					<p style="text-align:center; margin-top:1rem;">
          <?php echo $name; ?>様<br/><br/>
					ITスキル診断の受検は一度限りとさせていただいております。<br/>
          スタートボタンを押すと診断が始まります。
          <br/>
          問題は合計 <?php echo $question_num; ?>問、制限時間は <?php echo $time_limit; ?>分です。
					<br/>
					</p>
					</div>
					<div class="modal-footer flex-column border-top-0" style="padding-bottom:32px;">
						<button type="button" class="btn btn-lg  w-75 mx-0" id="startBtn" data-bs-dismiss="modal" style="background: linear-gradient(111deg, #87D782 0%, #22BC8E 100%); color:white; ">スタート</button>
					</div>
					</div>
				</div>
			</div>

<!-- modal2 -->
			<div class="modal modal-sheet py-5" style="backdrop-filter: blur(100px); " tabindex="-1" role="dialog" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true">
				<div class="modal-dialog" style="margin-top:100px;" role="document">
					<div class="modal-content rounded-4">
					<div class="modal-header border-bottom-0" style="background:linear-gradient(111deg, #87D782 0%, #22BC8E 100%); padding:10px 0px; font-size:20px; justify-content:center; color:white;border-top-left-radius:13px;border-top-right-radius:13px">株式会社ジエンジサービス
					<h3 class="modal-title fs-5" id="exampleModalLabel"></h3>
						<!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
					</div>
					<div class="modal-body fs-5">
					<div id='timeLimit' style="text-align:center; margin-top:20px;"></div>
					</div>
					<div class="modal-footer flex-column border-top-0" style="margin-bottom:12px;">
						<button type="button" id='lock_time' class="btn btn-lg  w-75 mx-0" data-bs-dismiss="modal" style="background: linear-gradient(111deg, #87D782 0%, #22BC8E 100%); color:white;">再開</button>
					</div>
					</div>
				</div>
			</div>
 
<!-- exam submit request loading modal -->
<div class="modal" tabindex="-1" role="dialog" id="submitLoading">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h3 style="text-align:center;">依頼転送中です。</h3>
      </div>
    </div>
  </div>
</div>

<script>
function getDayOfWeek(day) {
    const weekdays = ['日', '月', '火', '水', '木', '金', '土'];
    return weekdays[day];
}

function getCurrentDate() {
    const today = new Date();
    const year = today.getFullYear();
    const month = today.getMonth() + 1;
    const date = today.getDate();
    const day = getDayOfWeek(today.getDay());

    return year + '年 ' + addZero(month) + '月 ' + addZero(date) + '日（' + day + '）';
}

function addZero(num) {
    return (num < 10 ? '0' : '') + num;
}

function displayCurrentDate() {
    const dateContainer = document.getElementById('date-container');
    dateContainer.textContent = getCurrentDate();
}

function onLoadEvent() {
	loadPage.click();
}

window.onload = function() {
	onLoadEvent();
  displayCurrentDate();
};

</script>


<script>
  document.getElementById("startBtn").addEventListener("click", function() {
    var lock = 'n';
    var stopBtn = document.getElementById('stopBtn');

    var timerDisplay = document.getElementById("timerDisplay");
    
    var examTime  = <?php echo $time_limit?>; 
    var stopTime = parseInt(10); 

    var minuteToSecond = examTime * 60;
    var stopMinuteToSecond = stopTime * 60;


    var firstAlert= false;
    var secondAlert= false;


    var timer = setInterval(function() {
      if(lock == 'n'){
        updateTimer();
      }
    }, 1000);
    updateTimer();
    
    function updateTimer() {
      var minutes = Math.floor(minuteToSecond / 60);
      var seconds = minuteToSecond % 60;

      timerDisplay.innerHTML ="残り時間: " + minutes + "分 " + seconds + "秒";
      if (minuteToSecond <= 0) {
        clearInterval(timer);
        timerDisplay.innerHTML = "終";
        timeoutExam();
        document.querySelector('.timeout_submit').click();
      }else if(minuteToSecond <= 600 && !firstAlert){
        timerDisplay.style.color = "orange";
        firstAlert=true;
      }else if(minuteToSecond <= 300 && !secondAlert){
        timerDisplay.style.color = "red";
        secondAlert=true;
      }
      else{
        minuteToSecond--;
      }
    }

  document.getElementById("stopBtn").addEventListener("click", function() {
    event.preventDefault();        
    if(lock == 'n'){
      lock='y';
      updateTimer2(); 
      stopBtn.disabled='false';
      stopBtn.style.color = "gray";
    }
    });

    var calc_time=setInterval(function() {
      updateTimer2();
    }, 1000);


  function updateTimer2() {
      if(lock == 'y'){
          var stopMinutes = Math.floor(stopMinuteToSecond / 60);
          var stopSeconds = stopMinuteToSecond % 60;
          document.getElementById("timeLimit").innerHTML="残り時間: " + stopMinutes + "分 " + stopSeconds + "秒";
          stopMinuteToSecond--;

          if (stopMinuteToSecond < 0) {
              clearInterval(calc_time);
              lock = 'y';
              document.getElementById("lock_time").click(); 

              stopBtn.disabled=false; 
              stopBtn.style.color = "gray";
          }
      }
  }


  document.getElementById("lock_time").addEventListener("click",function(){
    if(lock == 'y'){
      lock='n';
    }
  });  
  });


</script>
<!-- <script>
function notReload(event) {
    if ((event.ctrlKey && (event.keyCode === 78 || event.keyCode === 82)) || event.keyCode === 116) {
        event.preventDefault();
        event.stopPropagation();
        alert("リフレッシュ キーは使用できません。");
    }
}
document.addEventListener('keydown', notReload);

</script> -->

<script>
document.addEventListener("DOMContentLoaded", () => {
  const btn_submit = document.querySelector("#btn_submit");
  const nextId = document.getElementById("nextId");
  var form = document.getElementById('myForm');

  btn_submit.addEventListener("click", () => {
    const matchedData = <?php echo json_encode($matchedData); ?>;
    <?php foreach ($matchedData as $questionIdx => $data) : ?>
          var selected = Array.from(form.answer<?= $questionIdx + 1 ?>).find(radio => radio.checked);
          if (selected == null) {
            alert("問題を全部入力してください。");
            event.preventDefault(); // Form submit prevent
            form.answer<?= $questionIdx +1 ?>[0].focus();
            return false; 
          } 
        <?php endforeach; ?>
        var selected = Array.from(form.answer<?= $questionIdx + 1 ?>).find(radio => radio.checked);
          confirmExam(); 

        var myModal = new bootstrap.Modal(document.getElementById('exampleModal'), {
           keyboard: false
        });
  myModal.show();
  });
});
</script>

<!-- Do not press EnterKey -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    document.addEventListener("keypress", function(e) {
      if (e.keyCode == 13) {
        e.preventDefault();
      }
    });
  });
</script>

<script>
 function confirmExam() {
    var formData = new FormData(document.getElementById('myForm'));
    var radioIdsArray= [];
    var confirmContent = document.getElementById('confirmContent');
    confirmContent.innerHTML = '';
    for (var pair of formData.entries()) {
      var questionIdx = pair[0];
      var selectedRadio = document.querySelector('input[name="' + questionIdx + '"]:checked');
      if (selectedRadio) {
        var radioId = selectedRadio.value;
        confirmContent.innerHTML = '試験を提出しますか？';
        formData.append('answer_data', radioId);
        radioIdsArray.push(radioId);
      }      

    }

    var combinedAnswers = radioIdsArray.join(',');
    console.log(combinedAnswers);

    document.getElementById('answer_data').value = combinedAnswers;
    

      
    // var confirmData= confirmContent.innerHTML;
}
</script>

<script>
  function timeoutExam() {
    var formData = new FormData(document.getElementById('myForm'));
    var totalQuestions = <?= count($matchedData) ?>;
    var answersArray = new Array(totalQuestions).fill('');
    var confirmContent = document.getElementById('confirmContent');
    confirmContent.innerHTML = '試験を提出しますか？';

    for (var pair of formData.entries()) {
        var questionIdx = parseInt(pair[0].replace('answer', ''), 10); // 'answer' 제거 후 숫자로 변환
        var selectedRadio = document.querySelector('input[name="' + pair[0] + '"]:checked');
        if (selectedRadio) {
            var radioId = selectedRadio.value;
            answersArray[questionIdx - 1] = radioId; // question index start 1
        }
    }

    var combinedAnswers = answersArray.join(',');
    console.log(combinedAnswers);

    document.getElementById('answer_data').value = combinedAnswers;
  }


</script>
<!-- <script>
 function confirmExam() {
    var formData = new FormData(document.getElementById('myForm'));
    var radioIdsArray= [];
    var comment = document.getElementById('comment').value;
    var confirmContent = document.getElementById('confirmContent');
    confirmContent.innerHTML = '';

    let count = 1;   

    for (var pair of formData.entries()) {
      var questionIdx = pair[0];
      var selectedRadio = document.querySelector('input[name="' + questionIdx + '"]:checked');
      if (selectedRadio) {
        var radioId = selectedRadio.value;
        confirmContent.innerHTML += count++ + '. ' + radioId  + "番" + '<br>';
        formData.append('answer_data', radioId);
        radioIdsArray.push(radioId);
      }      
    }

    confirmComment.innerHTML=comment;
    var combinedAnswers = radioIdsArray.join(',');
      document.getElementById('answer_data').value = combinedAnswers;

      
    var confirmData= confirmContent.innerHTML+comment;
}
</script> -->


<script>
  function requestSubmit(){
    $('#submitLoading').modal('show');
  }
</script>
<?php endif; ?>