<?php
$ses_id = (isset($_SESSION['applicant']) && !empty($_SESSION['applicant'])) ? $_SESSION['applicant'] : '';
if ($ses_id) {
    if ($_SESSION['applicant']['id']) {
        $logged = true;
    } else {
        $logged = false;
    }
} else {
    $logged = false;
}
?>
<?php if ($logged == true): ?>
<header>
	<div class="left-column"><img src="/img/hd_logo.png" alt="logo" height="56px" width="auto"></div>
	<div class="middle-column" style="font-size:bold">ITスキル診断</div>
	<div class="right-column" ><span id="timerDisplay" style="text-align:right;"></span></div>
</header>	
<div class="container-fluid">
  <div class="card emegra" >
    <div class="card-body"style="margin-top:70px;">
      <form id="form" method="post">
        <input name="end" type="hidden"/>
        <div  class="welcomeText">
          <p style="font-weight: bold; font-size: 20px; text-align:center;margin-right:120px;"><?php echo $name; ?>様</p>         
          <p>ITスキル診断を申込いただき誠にありがとうございます。</p>
          <p>問題は合計50問、制限時間は30分です。</p>		
          <p>表示される問題に従って回答してください。</p>			
          <p>ページ下部の一時停止ボタンを押すと10分間停止し、1回のみ使用可能です。</p>	
          <!-- <p>一時停止は1回のみ使用可能です。</p>		 -->
	
        </div>
        <div style="padding:0px 50px;">
        <p  style="margin-top:20px;font-weight:bold;">タイトル：Javaのキーワード</p>		
            <p  style="font-weight:bold;">総問題数：50問				</p>				  
        <div class="examBox">
            <p style="margin-top:20px; margin-left:50px;font-weight:bold;">問題１：Javaで変数を宣言するために使用されるキーワードは何ですか？				</p>						
            <input type="radio" id="html" name="fav_language" value="HTML" style="margin-left:150px;">
            <label for="html">parseDouble()		</label><br><br>
            <input type="radio" id="css" name="fav_language" value="CSS" style="margin-left:150px;">
            <label for="css">toDouble()			</label><br><br>
            <input type="radio" id="javascript" name="fav_language" value="JavaScript" style="margin-left:150px;">
            <label for="javascript">convertToDouble()		</label><br><br>
            <input type="radio" id="javascripts" name="fav_language" value="JavaScripts" style="margin-left:150px;">
            <label for="javascripts">convertToDouble()				</label><br>	<br>	
          </div>

          <div class="examBox">
            <p style="margin-top:20px; margin-left:50px;font-weight:bold;">問題 2：次の例問を見て答えてください</p>						
            <input type="radio" id="age1" name="age" value="1" style="margin-left:150px;">
            <label for="age1">parseDouble()		</label><br><br>
            <input type="radio" id="age2" name="age" value="2" style="margin-left:150px;">
            <label for="age2">toDouble()			</label><br><br>
            <input type="radio" id="age3" name="age" value="3" style="margin-left:150px;">
            <label for="age3">convertToDouble()		</label><br><br>
            <input type="radio" id="age3s" name="age" value="4" style="margin-left:150px;">
            <label for="age3s">convertToDouble()				</label><br>	<br>	
          </div>
        <!-- <?php foreach ($questionDatas as $qIdx => $data): ?>
          <div style="margin-top: 32px">
            <h5><?php echo $qIdx + 1 . ". " . $data["question"]; ?></h5>
            <?php foreach (explode("|", $data["answers"]) as $aIdx => $answer): ?>
              <input class="form-check-input" type="radio" name="question<?= $qIdx ?>" id="<?php echo "Q" . $qIdx . "A" . $aIdx; ?>" value="<?= $aIdx + 1; ?>">
              <label class="form-check-label" for="<?php echo "Q" . $qIdx . "A" . $aIdx; ?>">
                <?php echo $answer; ?>
              </label>
              <br/>
            <?php endforeach; ?>
          </div>
        <?php endforeach; ?> -->
        
        <div class="comment">
          <p style="margin-top:50px;font-weight:bold;">コメント　　　　　　　　 <input class="w-75" type="text" placeholder="自由に記載"></p>
        </div>

      <br/><br/>
      <div class="welcomeText" style="border-bottom:none">
      <p style="text-align:center;">お疲れさまでした。</p>
      <p>以下の送信ボタンをクリックしてください。</p>
      </div>
      
    </div>
    <div class="button_box" style="margin-bottom: 32px; gap:30px">
      <button class="applicant_cancel" name="mode"  value="cancel" onclick="window.location.href='../applicant/login';">キャンセル</button>
      <button class="applicant_stop" id="stopBtn"  data-bs-toggle="modal" data-bs-target="#staticBackdrop2">一時停止</button>
      <button class="exam_submit" name="mode"  value="submit" onclick="check();">提出</button>
    </div>
    </form>

  </div>
  
</div>



<div class="modal fade" id="modal" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5">回答確認</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>

			<div class="modal-body d-flex flex-column">
				<label>回答を登録しますか？</label>
				<!-- <?php foreach ($questionDatas as $questionIdx => $data): ?>
					<label id="answer<?= $questionIdx ?>"></label>
				<?php endforeach; ?> -->
			</div>

			<div class="modal-footer">
				<div class="btn-place" style="width: 100%;">
					<button type="button" class="emegra cancel" data-bs-dismiss="modal">キャンセル</button>
					<button type="button" class="emegra" onclick="submit();">OK</button>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- modal -->
<button type="button" class="btn btn-primary" id="loadPage" data-bs-toggle="modal" data-bs-target="#staticBackdrop" style="display:none"></button>
			<div class="modal modal-sheet py-5" style="backdrop-filter: blur(100px); " tabindex="-1" role="dialog" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
				<div class="modal-dialog" style="margin-top:100px;" role="document">
					<div class="modal-content rounded-4">
					<div class="modal-header border-bottom-0" style="background:linear-gradient(111deg, #87D782 0%, #22BC8E 100%); padding:10px 0px; font-size:20px; justify-content:center; color:white;border-top-left-radius:13px;border-top-right-radius:13px">株式会社ジエンジサービス
					<h3 class="modal-title fs-5" id="exampleModalLabel"></h3>
						<!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
					</div>
					<div class="modal-body fs-5">
					<p style="text-align:center; margin-top:1rem;">
          <?php echo $name; ?>　様<br/><br/>
					ITスキル診断の受検は<br>一度限りとさせていただいております。<br/>
          スタートボタンを押すと診断が始まります。
          <br/>
					<br/>
					今すぐ受検を開始しますか？
					</p>
					</div>
					<div class="modal-footer flex-column border-top-0">
						<button type="button" class="btn btn-lg  w-75 mx-0" id="startBtn" data-bs-dismiss="modal" style="background: linear-gradient(111deg, #87D782 0%, #22BC8E 100%); color:white;">スタート</button>
					</div>
					</div>
				</div>
			</div>

<!-- modal2 -->
			<div class="modal modal-sheet py-5" style="backdrop-filter: blur(100px); " tabindex="-1" role="dialog" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true">
				<div class="modal-dialog" style="margin-top:100px;" role="document">
					<div class="modal-content rounded-4">
					<div class="modal-header border-bottom-0" style="background:linear-gradient(111deg, #87D782 0%, #22BC8E 100%); padding:10px 0px; font-size:20px; justify-content:center; color:white;border-top-left-radius:13px;border-top-right-radius:13px">株式会社ジエンジサービス
					<h3 class="modal-title fs-5" id="exampleModalLabel"></h3>
						<!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
					</div>
					<div class="modal-body fs-5">
					<div id='a' style="text-align:center; margin-top:20px;"></div>
					</div>
					<div class="modal-footer flex-column border-top-0">
						<button type="button" id='lock_time' class="btn btn-lg  w-75 mx-0" data-bs-dismiss="modal" style="background: linear-gradient(111deg, #87D782 0%, #22BC8E 100%); color:white;">スタート</button>
					</div>
					</div>
				</div>
			</div>

<script type="text/javascript">
	const form = document.getElementById("form");

	function check() {
		// <?php foreach ($questionDatas as $index => $data): ?>
		// 	var selected = Array.from(form.question<?= $index ?>).find(radio => radio.checked);
		// 	if (selected == null) {
		// 		alert("答えなかった問題があります。");
		// 		form.question<?= $index ?>[0].focus();
		// 		return false;
		// 	}

		// 	document.getElementById("answer<?= $index ?>").innerText = "<?= $index + 1 ?>. " + selected.value;
		// <?php endforeach; ?>
		
		const modal = new bootstrap.Modal(document.getElementById("modal"), { keyboard: false });
		modal.show();
	}

	function submit() { form.submit(); }
</script>
<!-- ここまで -->
<script>
function getDayOfWeek(day) {
    const weekdays = ['日', '月', '火', '水', '木', '金', '土'];
    return weekdays[day];
}

function getCurrentDate() {
    const today = new Date();
    const year = today.getFullYear();
    const month = today.getMonth() + 1;
    const date = today.getDate();
    const day = getDayOfWeek(today.getDay());

    return year + '年 ' + addZero(month) + '月 ' + addZero(date) + '日（' + day + '）';
}

function addZero(num) {
    return (num < 10 ? '0' : '') + num;
}

function displayCurrentDate() {
    const dateContainer = document.getElementById('timerDisplay');
    dateContainer.textContent = getCurrentDate();
}

function onLoadEvent() {
	loadPage.click();
}

window.onload = function() {
	onLoadEvent();
};

</script>


<script>
document.getElementById("startBtn").addEventListener("click", function() {
  var lock = 'n';
  var stopBtns = document.getElementById('stopBtn');

  var timerDisplay = document.getElementById("timerDisplay");
  var examTime = parseInt(30); 

  var stopTime = parseInt(10); 
  let now_time = 0;

  var minuteToSecond = examTime * 60;
  var stopMinuteToSecond = stopTime * 60;

  var firstAlert= false;
  var secondAlert= false;


  var timer = setInterval(function() {
    if(lock == 'n'){
      updateTimer();
    }
  }, 1000);
  updateTimer();
  
  function updateTimer() {
    var minutes = Math.floor(minuteToSecond / 60);
    var seconds = minuteToSecond % 60;

    timerDisplay.innerHTML = getCurrentDate() + " <?php echo $name; ?> "+"<br> 残り時間: " + minutes + "分 " + seconds + "秒";
    if (minuteToSecond <= 0) {
      clearInterval(timer);
      timerDisplay.innerHTML = "終";
      window.location.href = '../applicant/examclear';
    }else if(minuteToSecond <= 600 && !firstAlert){
      alert("残り10分です。")
      firstAlert=true;
    }else if(minuteToSecond <= 300 && !secondAlert){
      alert("残り5分です。")
      secondAlert=true;
    }
    else{
      minuteToSecond--;
    }
  }

document.getElementById("stopBtn").addEventListener("click", function() {
  event.preventDefault();        
  if(lock == 'n'){
		lock='y';
    updateTimer2(); 
    stopBtns.disabled='false';
      stopBtns.style.backgroundColor = "gray";
	}
  });

  var calc_time=setInterval(function() {
    updateTimer2();
  }, 1000);


function updateTimer2() {
    if(lock == 'y'){
        var stopMinutes = Math.floor(stopMinuteToSecond / 60);
        var stopSeconds = stopMinuteToSecond % 60;
        document.getElementById("a").innerHTML="残り時間: " + stopMinutes + "分 " + stopSeconds + "秒<br><br>"+"再起動するには、<br>[スタート] ボタンを押します。";
        stopMinuteToSecond--;

        if (stopMinuteToSecond < 0) {
            clearInterval(calc_time);
            lock = 'y';
            document.getElementById("lock_time").click(); 

            stopBtns.disabled=false; 
            stopBtns.style.backgroundColor = "gray";
        }
    }
}


document.getElementById("lock_time").addEventListener("click",function(){
  if(lock == 'y'){
		lock='n';
	}
});  
});


</script>

<!-- <script>
function notReload(event) {
    if ((event.ctrlKey && (event.keyCode === 78 || event.keyCode === 82)) || event.keyCode === 116) {
        event.preventDefault();
        event.stopPropagation();
        alert("リフレッシュ キーは使用できません。");
    }
}
document.addEventListener('keydown', notReload);

</script> -->
<?php endif; ?>