<?php
$ses_id = (isset($_SESSION['applicant']) && !empty($_SESSION['applicant'])) ? $_SESSION['applicant'] : '';
if ($ses_id) {
    if ($_SESSION['applicant']['userid']) {
        $logged = true;
    } else {
        $logged = false;
    }
} else {
    $logged = false;
}
?>
<?php if ($logged == true): ?>
    <?php else:?>
<style type="text/css">
	span { margin-bottom: 8px; }
	input { height: 48px; }
</style>
<form id="form" name="login_form" enctype="multipart/form-data" action="/applicant/login" method="get" onsubmit="return submitForm()">
  <div class="emegra card">
    <div class="card-header">ITスキル診断システム</div>

    <div class="card-body">
      <span>ログインID</span>
      <input class="form-control" name='email' id="id" type="text" placeholder="IDを入力ください">

      <span style="margin-top: 24px">パスワード</span>
      <input class="form-control" name='password' id="password" type="password" placeholder="パスワードを入力ください">

      <button class="emegra" style="margin-top: 40px;" type="submit">ログイン</button>
    </div>
  </div>
</form>
<script>
  const id = document.getElementById("id");
  const password = document.getElementById("password");
  const url = window.location.href;

  function submitForm() {
    if (id.value == "") {
      alert("IDを入力ください");
      id.focus();
      return false;
    }

    if (password.value == "") {
      alert("パスワードを入力ください");
      password.focus();
      return false;
    }

    const postForm = new FormData();
    postForm.append("id", id.value);
    postForm.append("password", password.value);

    const xhr = new XMLHttpRequest();
    xhr.open("POST", url, true);
    xhr.send(postForm);

    xhr.onload = () => {
    try {
    if (xhr.status == 200) {
      const result = xhr.responseText;
      const resultDate = JSON.parse(result);
      if (resultDate.status == "wronginfo") {
        alert("有効ではないIDまたはパスワードです。");
        id.focus();
      } else if (resultDate.status == "wrongtime") {
        alert(`診断開始(${resultDate.timein}~${resultDate.timeout})時間に再度お試しください。`);
      } else if (resultDate.status == "timeout") {
        alert(`診断開始(${resultDate.timein}~${resultDate.timeout})時間が過ぎていただめ、受験できません。\n管理者にお問い合わせください。`);
      } else if (resultDate.status == "success") {
        self.location.href = "../applicant/exam";
      }
    } else {
      console.error("Error: Unexpected status code " + xhr.status);
      alert(`ログインエラーが発生しました： (${xhr.status}) \n担当者にお問い合わせください。`);
    }
  } catch (error) {
    console.error("Error occurred during xhr request:", error);
    alert(`ログインエラーが発生しました。： (${error}) \n担当者にお問い合わせください。`);
  }
}
return false;
  }
</script>

<?php endif ?>
