<?php
	$certificateDatas = "";
	if(isset($examData["certificates"])) {
		$certificateDatas = explode(",", $examData["certificates"]);		// certificatesデータをarrayに変更
	}
?>

<style type="text/css">
	dl.emegra { grid-template-columns: repeat(2, 100px 1fr); }
</style>

<form id="form" method="post">
	<input name="certificates" type="hidden"/>

	<div class="emegra card">
		<div class="card-header"><?php echo $examData["name"]; ?> 様の情報</div>

		<div class="card-body">
			<dl class="emegra">
				<dt>最終学歴</dt>
				<dd>
					<select class="form-select" name="academic" onclick="determineCheckboxActivation(event);">
						<option value="" selected disabled hidden>選択してください</option>
						<option value=2>高等学校</option>
						<option value=4>専門学校</option>
						<option value=6>短期大学</option>
						<option value=8>大学</option>
						<option value=10>大学院</option>
						<option value=0>その他</option>
					</select>
				</dd>

				<dt>IT専攻</dt>
				<dd><input type="checkbox" name="major" disabled/></dd>

				<dt>問題種別</dt>
				<dd>
					<select class="form-select" name="type">
						<option value="" selected disabled hidden>選択してください</option>
						<?php foreach ($typeDatas as $data): ?>		<!-- typeデータを表示 -->
							<option value=<?php echo $data["question_type"]; ?>><?php echo $data["question_title"]; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt>経歴</dt>
				<dd><input class="form-control" name="career" placeholder="年単位に数字だけ入力してください。" value="<?php echo $examData["career"]; ?>"/></dd>
			</dl>

			<div style="margin-top: 24px;">
				<span style="font-size: 16px; font-weight: 700;">資格</span>
				<div id="place-certificate">
				<?php if ($certificateDatas != ""): ?>
					<?php foreach ($certificateDatas as $data): ?>		<!-- certificateデータ表示 -->
						<div style="margin-top: 8px; display: flex; align-items: center;">
							<input class="form-control" style="max-width: calc(100% - 46px); margin-right: 8px;" name="certificate[]" placeholder="資格の名を入力してください。" value="<?php echo $data; ?>"/>
							<button type="button" class="btn-minus" onclick="event.target.parentNode.remove();">-</button>
						</div>
					<?php endforeach; ?>
				<?php endif; ?>
			</div>
			<button class="btn-plus" style="margin-top: 8px; float: right;" type="button" onclick="addCertificate();">+</button>
		</div>
	</div>
	</div>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back()">キャンセル</button>
	<button class="emegra" onclick="Confirm()">確認</button>
</div>


<script type="text/javascript">
	const form = document.getElementById("form");
	const certificatePlace = document.getElementById("place-certificate");

	<?php if ($examData["academic"] != ""): ?>		// academicデータがある場合

		<?php if ($examData["academic"] % 2 == 1): ?>
			form.academic.value = <?php echo $examData["academic"] - 1; ?>;
			form.major.disabled = false;
			form.major.checked = true;
		<?php else: ?>
			form.academic.value = <?php echo $examData["academic"]; ?>;
		<?php endif; ?>
	<?php endif; ?>

	<?php if ($examData["question_type"] != ""): ?>		// typeデータがある場合
		form.type.value = "<?php echo $examData["question_type"]; ?>";
	<?php endif; ?>



	function determineCheckboxActivation(event) {
		if (event.target.value == "" || event.target.value < 2) { form.major.disabled = true; }
		else { form.major.disabled = false; }
	}

	function addCertificate() {		// 資格入力空間追加ボタンを押した時
		const newDiv = document.createElement("div");

		newDiv.innerHTML =
			"<div style='margin-top: 8px; display: flex; align-items: center;'>" +
				"<input class='form-control' style='max-width: calc(100% - 46px); margin-right: 8px;' name='certificate[]' placeholder='資格の名を入力してください。'>" +
				"<button type='button' class='btn-minus' onclick='event.target.parentNode.remove();'>-</button>" +
			"</div>";

		certificatePlace.appendChild(newDiv);
	}

	function Confirm() {		//Confirm Validation
		if (form.academic.value == "") {
			alert("学歴を選択してください。");
			form.academic.focus();
			return false;
		}

		if (form.type.value == "") {
			alert("問題種別を選択してください。");
			form.type.focus();
			return false;
		}

		if (form.career.value.trim() == "") {
			alert("経歴を入力してください。");
			form.career.focus();
			return false;
		}

		if (isNaN(form.career.value)) {
			alert("経歴に数字だけ入力してください。");
			form.career.focus();
			return false;
		}

		var result = confirm("設定を登録しますか？");
		if (!result) {
			return false;
		}

		var certificateArray = document.getElementsByName("certificate[]");
		var certificates = "";
		for (let i = 0; i < certificateArray.length; i++) {
			if (certificateArray[i].value.trim() == "") {
				alert("資格を入力してください。");
				certificateArray[i].focus();
				return false;
			}
			else { certificates += certificateArray[i].value.trim() + ","; }
		}
		form.certificates.value = certificates.slice(0, -1);

		form.submit();
	}
</script>