<?php
  $title = array(
    "situation" => "ITスキル診断状況管理",
    "diagnosis" => "ITスキル診断問題管理",
    "question" => "ITスキル診断問項管理",
    "manager" => "ITスキル診断管理者管理",
  );

	if (!isset($_SESSION)) { session_start(); }
	$userData = $_SESSION["user"];

	echo $this->doctype();
	$url = explode("/", $_SERVER["REQUEST_URI"]);
	$mainMenu = $url[2];

	if ($this->title == "") {
		$this->title = "G&GService";
	}

	$breadcrumb = json_decode($this->breadcrumb, true);
?>

<html lang="jp">
	<head>
		<meta charset="utf-8">	
		<?php
			echo $this->headTitle($this->title)->setSeparator(" - ")->setAutoEscape(false);
			
			echo $this->headMeta()
				->appendName("title", $this->title)
				->appendName("description", $this->description)
				->appendName("keywords", $this->keywords)
				->appendName("robots", "ALL")
				->appendName("Distribution", "GNGService")
				->appendName("author", "drapiece@gngs.co.jp")
				->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
				->appendHttpEquiv("X-UA-Compatible", "IE=edge");
		?>
		<meta name="viewport" content="height=device-height">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="/css/emegra-admin.css" rel="stylesheet" type="text/css">
		<link href="/css/custom.css" rel="stylesheet" type="text/css">
		<style>
			.popover{ max-width: 1000px; }
		</style>
	</head>

	<body>
		<header>
			<div class="logo">
				<img src="/img/hd_logo.png" alt="logo" height="43px" width="auto" style="margin-left: 39px;"/>
        <a class="logo-title">ITスキル診断システム<small><small> Ver 1.0</small></small></a>
			</div>

			<div class="title"><p><?= $title[$mainMenu]; ?></p></div>

			<div class="status">
				<p style="margin-right: 16px;"><?php echo $userData["name"]; ?>様</p>
				<p style="margin-right: 24px;"> 前回のログイン:<?php echo $userData["date_login"]; ?></p>
				<a style="margin-right: 32px; display: flex; flex-direction: row; cursor: pointer;" onclick="logout();">
					<img src="/img/ic_logout.svg" alt="logout" width="auto" style="margin-right: 4px;"/>
					ログアウト
				</a>
			</div>
		</header>

		<aside>
      <button class="btn-sub <?php echo $title[$mainMenu] == "ITスキル診断状況管理" ? " active" : ""; ?>" onclick="self.location.href='/admin/situation/list'">ITスキル診断状況管理</button>
      <button class="btn-sub <?php echo $title[$mainMenu] == "ITスキル診断問題管理" ? " active" : ""; ?>" onclick="self.location.href='/admin/diagnosis/list'">ITスキル診断問題管理</button>
      <button class="btn-sub <?php echo $title[$mainMenu] == "ITスキル診断問項管理" ? " active" : ""; ?>" onclick="self.location.href='/admin/question/list'">ITスキル診断問項管理</button>
      <?php if ($_SESSION["user"]["level"] >= 2): ?>
        <button class="btn-sub <?php echo $title[$mainMenu] == "ITスキル診断管理者管理" ? " active" : ""; ?>" onclick="self.location.href='/admin/manager/list'">ITスキル診断管理者管理</button>
      <?php endif; ?>
		</aside>
		
		<main>
			<?php echo $this->content; ?>
		</main>

		<form id="form_logout" action="/admin/account/logout" method="post" action="/admin/account/logout"></form>

		<script>
			if (typeof bootstrap === "undefined") {
				var script = document.createElement("script");
				script.src = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js";
				script.integrity = "sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz";
				script.crossOrigin = "anonymous";
				document.head.appendChild(script);
			} else {
				console.log("Bootstrap is already loaded");
			}
		</script>
		<script>
			if (typeof popoverTriggerList === "undefined") {
				let popoverTriggerList = document.querySelectorAll("[data-bs-toggle='popover']");
				let popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));
			}

      if (typeof tooltipTriggerList === "undefined") {
        let tooltipTriggerList = document.querySelectorAll("[data-bs-toggle='tooltip']")
        let tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
      }

			function logout() { document.getElementById("form_logout").submit(); }
			function setCookie(name, value, options = {}) {
				options = { path: "/" };
				if (options.expires instanceof Date) {
					options.expires = options.expires.toUTCString();
				}
				let updatedCookie = encodeURIComponent(name) + "=" + encodeURIComponent(value);

				for (let optionKey in options) {
					updatedCookie += "; " + optionKey;
					let optionValue = options[optionKey];
					if (optionValue !== true) {
						updatedCookie += "=" + optionValue;
					}
				}
				
				document.cookie = updatedCookie;
			}
			function getCookie(name) {
				let matches = document.cookie.match(new RegExp("(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, "\\$1") + "=([^;]*)"));
				return matches ? decodeURIComponent(matches[1]) : undefined;
			}
			function deleteCookie(name) { setCookie(name, "", { "max-age": -1 }) }
		</script>
	</body>
</html>