<!-- <?php echo $this->doctype();
$mm = $_SERVER['REQUEST_URI'];
$exp = explode("/", $mm);
$expp = explode("?", $exp[1]);
$topMenu = $expp[0];

if ($this->title == '') {
  $this->title = 'G&GService';
}

$category = $this->layout()->category;
?>

<html lang="jp">

<head>
  <meta charset="utf-8">
  <?php
  echo $this->headTitle($this->title)->setSeparator(' - ')->setAutoEscape(false);

  echo $this->headMeta()
    ->appendName('title', $this->title)
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords)
    ->appendName('robots', 'ALL')
    ->appendName('Distribution', 'GNGService')
    ->appendName('author', 'drapiece@gngs.co.jp')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
  ?>
  <meta name="viewport" content="height=device-height">

  <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/css/bootstrap-grid.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/css/open-iconic-bootstrap.min.css" rel="stylesheet">
  <link href="/css/default.css" rel="stylesheet" type="text/css">
  <script type="text/javascript" src="/js/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="/js/addclear.js"></script>
  <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

  <style>
    .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }
  </style>

  <script>
    window.addEventListener("DOMContentLoaded", () => {
      if (sessionStorage.getItem("user") == null) {
        alert('ログインをしてください。');
        self.location.href = '/admin/login';
      }
    });
  </script>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand text-white">GNGService</a>
        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item"> <a class="nav-link" style="cursor: pointer;" onclick="LogOut()">Logout</a> </li>
          </ul>
        </div>

        <script>
          function LogOut() {
            var result = confirm("ログアウトしますか？");
            if (result === true) {
              sessionStorage.removeItem("user")
              self.location.href = " /admin/login";
            }
          }
        </script>
      </div>
    </nav>
  </header>

  <main>
    <div class="d-flex">
      <div class="d-flex flex-column flex-shrink-0 pt-1 vh-100 bg-light" style="width: 280px;">
        <ul class="list-group">
          <a class="list-group-item rounded-0 border-0 bg-dark text-white">応募者状況管理</a>
          <a class="list-group-item rounded-0 border-0 pl-5" <?php echo $category == 1 ? "style='background-color: #a1a6a9; color: white;'" : "" ?> href="/admin/exam/list?page=1" style="text-decoration-line: none;">試験一覧</a>
          <a class="list-group-item rounded-0 border-0 pl-5" <?php echo $category == 2 ? "style='background-color: #a1a6a9; color: white;'" : "" ?> href="/admin/exam/register" style="text-decoration-line: none;">試験登録</a>
          <a class="list-group-item rounded-0 border-0 bg-dark text-white">問題管理</a>
          <a class="list-group-item rounded-0 border-0 pl-5" <?php echo $category == 3 ? "style='background-color: #a1a6a9; color: white;'" : "" ?> href="/admin/question/list?page=1" style="text-decoration-line: none;">問題一覧</a>
          <a class="list-group-item rounded-0 border-0 pl-5" <?php echo $category == 4 ? "style='background-color: #a1a6a9; color: white;'" : "" ?> href="/admin/question/register" style="text-decoration-line: none;">問題登録</a>
        </ul>
      </div>
      <div class="w-100 h-100 d-flex flex-column justify-content-center">
        <?php echo $this->content; ?>
      </div>
    </div>
  </main>

  <footer>
  </footer>
  <?php echo $this->inlineScript() ?>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
  </script>
</body>

</html> -->