<?php if ($this->pageCount): ?>
<nav aria-label="Page navigation">
	<ul class="pagination justify-content-center">
		<?php if (isset($this->previous)): ?>
			<li class="page-item">
				<a class="page-link" href="<?php echo $this->url;?><?php echo ($this->url=='')?"?":"&"?>page=1">最前へ</a>
			</li>
			<li class="page-item">
				<a class="page-link" href="<?php echo $this->url;?><?php echo ($this->url=='')?"?":"&"?>page=<?php echo $this->previous;?>">前へ</a>
			</li>
		<?php else: ?>
			<li class="page-item disabled">
				<a class="page-link" href="#">&laquo;</a>
			</li>
		<?php endif; ?>
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<li class="page-item">
					<a class="page-link" href="<?php echo $this->url;?><?php echo ($this->url=='')?"?":"&"?>page=<?php echo $page;?>"><?php echo $page;?></a>
				</li>
			<?php else: ?>
				<li class="page-item active">
					<a class="page-link" href="#"><?php echo $page; ?></a>
				</li>
			<?php endif; ?>
		<?php endforeach; ?>
		<?php if (isset($this->next)): ?>
			<li class="page-item">
				<a class="page-link" href="<?php echo $this->url; ?><?php echo ($this->url=='')?"?":"&"?>page=<?php echo $this->next;?>">次へ</a>
			</li>
			<li class="page-item">
				<a class="page-link" href="<?php echo $this->url; ?><?php echo ($this->url=='')?"?":"&"?>page=<?php echo $this->next;?>">最後へ</a>
			</li>
		<?php else: ?>
			<li class="page-item disabled">
				<a class="page-link" href="#">&raquo;</a>
			</li>
		<?php endif; ?>
	</ul>
</nav>
<?php endif; ?>
