<?php
  $levelTextDatas = ["無級", "初級", "中級", "高級"];
  $numTextDatas = ["①", "②", "③", "④", "⑤"];
  $rankTextDatas = ["A", "B", "C", "D"];
  $pointCriteriaDatas = [90, 70, 50, 0];

  function ChangeToPopoverForm($string) {
    $string = str_replace("<", "＜", $string);
    $string = str_replace(">", "＞", $string);
    $string = str_replace('"', "”", $string);
    $string = str_replace("{{n}}", "<br/>", $string);
    $string = "<pre>" . $string . "</pre>";
    return $string;
  }

  if (!isset($_SESSION)) { session_start(); }

  $resultPointDatas = explode(",", $diagnosisData["result_points"]);
  $resultTextDatas = explode(",", $diagnosisData["result_texts"]);
  $resultCommentDatas = explode(",", $diagnosisData["result_comments"]);

  // Check approve authority
  $isApprover = false;
  if ($_SESSION["user"]["level"] >= 1) { $isApprover = true; }
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">問題詳細</h1>

<div class="emegra card">
  <div class="card-header">設定</div>

  <div class="card-body">
    <style type="text/css">
        dl.emegra.setting { grid-template-columns: 140px 1fr; }
    </style>
    <dl class="emegra setting">
      <dt>問題ID</dt>
      <dd><?php echo $diagnosisData["code"]; ?></dd>
      
      <dt>分類</dt>
      <dd><?php echo $optionDatas[$diagnosisData["class1st"]]; ?> / <?php echo $optionDatas[$diagnosisData["class2nd"]]; ?></dd>
    
      <dt>レベル</dt>
      <dd><?php echo $levelTextDatas[$diagnosisData["level"]]; ?></dd>
    
      <dt>タイトル</dt>
      <dd><?php echo $diagnosisData["title"]; ?></dd>
    </dl>
  </div>
</div>

<div class="emegra card" style="margin-top: 32px;">
  <div class="card-header">問題</div>

  <div class="card-body">
    <style type="text/css">
      dl.emegra.question { grid-template-columns: 140px 1fr; }
    </style>
    <dl class="emegra question">
      <dt>問項数</dt>
      <dd><?php echo $diagnosisData["question_num"]; ?>題項</dd>

      <dt>診断時間</dt>
      <dd><?php echo $diagnosisData["time_limit"]; ?>分</dd>

      <dt>問項一覧</dt>
      <div style="width: 100%;">
        <style type="text/css">
          input.checkbox { height: 20px !important; }

          div.emegra-table th, div.emegra-table td { padding: 0; }
          div.emegra-table {
            max-height: 500px;
            overflow-y: auto;
          }
          div.emegra-table th {
            position: sticky;
            top: 0;
          }
        </style>

        <div style="display: flex;">
          <div class="emegra-table">
            <table class="table table-bordered" id="table-diagnosis_list">
              <thead>
                <tr>
                  <th>No</th>
                  <th>問項タイトル</th>
                  <th>大分類</th>
                  <th>小分類</th>
                  <th>レベル</th>
                  <th  style="padding-right: 17px;">点数</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($questionDatas as $index => $data): ?>
                  <?php
                    $popoverContent = $numTextDatas[0] . $data["answer1"];
                    for ($i = 2; $i <= 5; $i++) {
                      if ($data["answer" . $i] == null) { break; }
                      $popoverContent .= "{{n}}" . $numTextDatas[$i -1] . $data["answer" . $i];
                    }
                    $popoverContent = ChangeToPopoverForm($popoverContent);
                  ?>
                  <tr>
                    <td><?php echo $index + 1; ?></td>
                    <td class="start" data-bs-toggle='popover' data-bs-placement="bottom" data-bs-title="<?php echo ChangeToPopoverForm($data["question"]); ?>" data-bs-content="<?php echo $popoverContent; ?>" data-bs-html="true">
                      <?php echo $data["title"]; ?>
                    </td>
                    <td class="start"><?php echo $optionDatas[$data["class1st"]]; ?></td>
                    <td class="start"><?php echo $optionDatas[$data["class2nd"]]; ?></td>
                    <td><?php echo $levelTextDatas[$data["level"]]; ?></td>
                    <td><?php echo $data["point"]; ?></td>
                  </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </dl>
  </div>
</div>

<div class="emegra card" style="margin-top: 32px;">
  <div class="card-header">情報</div>

  <div class="card-body">
      <style type="text/css">
        table.evaluation {
          width: 100%;
          text-align: center;
        }
        table.evaluation tr {
          display: grid;
          grid-template-columns: 200px 150px 150px 1fr;
          gap: 10px 8px;
        }
        table.evaluation td {
          padding: 4px 0;
          display: flex;
          align-items: center;
          justify-content: center;
        }
      </style>
      <table class="evaluation">
        <thead>
          <tr>
            <th>評価等級</th>
            <th>評価点数</th>
            <th>評価</th>
            <th>評価コメント</th>
          </tr>
        </thead>
        <tbody>
          <?php for ($i = 0; $i < count($rankTextDatas); $i++): ?>
            <?php
              $lastIdx = count($rankTextDatas) - 1;

              $rankText = $rankTextDatas[$i] . "（";
              if ($i != $lastIdx) { $rankText .= $pointCriteriaDatas[$i] . "%以上"; }
              if ($i != 0) { $rankText .= $pointCriteriaDatas[$i - 1] . "%未満"; }
              $rankText .= "）";

              $resultPointText = $diagnosisData["point_total"] . " ~ ";
              if ($i != 0) { $resultPointText = $resultPointDatas[$i - 1] . " ~ "; }
              $resultPointText .= $resultPointDatas[$i];
            ?>

            <tr>
              <td style="justify-content: start;"><?php echo $rankText; ?></td>
              <td><?php echo $resultPointText; ?></td>
              <td style="justify-content: start; text-align: left;"><?php echo $resultTextDatas[$i]; ?></td>
              <td style="justify-content: start; text-align: left;"><?php echo $resultCommentDatas[$i]; ?></td>
            </tr>
          <?php endfor; ?>
        </tbody>
      </table>
  </div>
</div>

<div class="btn-place" style="margin-top: 32px;">
  <button class="emegra cancel" onclick="history.back();">一覧へ</button>
  <?php if ($isApprover): ?>
    <button class="emegra" onclick="self.location.href='../edit/<?php echo $diagnosisData['idx']; ?>';">修正</button>
    <button class="emegra delete" onclick="Remove();">削除</button>
  <?php endif; ?>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript">
  <?php if ($isApprover): ?>
    function Remove() {
      if (confirm("削除しますか？") === false) { return false; }

      const postForm = new FormData();
      postForm.append("idxs", <?php echo $diagnosisData["idx"]; ?>);

      const xhr = new XMLHttpRequest();
      xhr.open("POST", "../remove", true);
      xhr.send(postForm);
      xhr.onload = () => {
        if (xhr.status == 200) {
          const result = xhr.responseText;
          if (result == "success") {
            alert("削除しました。");
            self.location.href = "../list";
          }
          else {
            let alertString = ErrorString();
            alertString += "\nresponse text is not success in diagnosois_detail Remove";
            alertString += "\nresponseText: " + result;
            alert(alertString);
            console.log(result);

            return false;
          }
        }
        else {
          let alertString = ErrorString();
          alertString += "\nxhr error in diagnosois_detail Remove";
          alertString += "\nerror code: " + xhr.status;
          alert(alertString);

          return false;
        }
      }
    }
  <?php endif; ?>



  function ErrorString() {
    let alertString = "予期せぬエラーが発生しました。";
    alertString += "\n管理者にエラー内容をお知らせくださいますようお願いいたします。";
    alertString += "\n\nエラー内容：";
    return alertString;
  }
</script>