<?php
  $levelTexts = ["無級", "初級", "中級", "高級"];
  $numTexts = array("①", "②", "③", "④", "⑤");

  function ReplaceSymbol($string) {
    $string = str_replace("<", "＜", $string);
    $string = str_replace(">", "＞", $string);
    return $string;
  }

  if (!isset($_SESSION)) { session_start(); }

  $isSet = false;
  if (isset($_COOKIE["diagnosisData"])) {
    $isSet = true;
    $diagnosisData = json_decode($_COOKIE["diagnosisData"], true);
    setcookie("diagnosisData", "", time() - 3600, "/");
  }

  $isEdit = false;
  if (isset($diagnosisData["idx"])) {
    $isSet = true;
    $isEdit = true;

    $pointDatas = explode(",", $diagnosisData["result_points"]);
    $textDatas = explode(",", $diagnosisData["result_texts"]);
    $commentDatas = explode(",", $diagnosisData["result_comments"]);

    for ($i = 1; $i <= 4; $i++) {
      $diagnosisData["point" . $i] = $pointDatas[$i - 1];
      $diagnosisData["text" . $i] = $textDatas[$i - 1];
      $diagnosisData["comment" . $i] = $commentDatas[$i - 1];
    }
  }
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

<form id="form" method="post" action="./confirm">
  <?php if ($isEdit): ?>
    <input name="idx" value="<?php echo $diagnosisData["idx"]; ?>" hidden/>
  <?php endif; ?>
  <input name="question_idxs" value="<?php echo ($isSet) ? $diagnosisData["question_idxs"] : ""; ?>" hidden/>
  <input name="point_total" value="<?php echo ($isSet) ? $diagnosisData["point_total"] : ""; ?>" hidden/>

  <div class="emegra card">
    <div class="card-header">設定</div>

    <div class="card-body">
      <style type="text/css">
        dl.emegra.setting { grid-template-columns: 140px 1fr; }
      </style>
      <dl class="emegra setting">
        <?php if ($isEdit): ?>
          <dt>問題ID</dt>
          <dd><input class="form-control form-control-sm" name="code" style="width: 150px;" readonly value="<?php echo $diagnosisData["code"];?>"/></dd>
        <?php endif; ?>

        <dt class="essential">大分類</dt>
        <dd>
          <select class="form-select" name="class1st" onchange="ChangeClass1st(this)" style="width: 150px;">
            <option value="" hidden>選択</option>

            <?php foreach ($optionDatas["class1st"] as $data): ?>
              <option value="<?php echo $data["idx"]; ?>"<?php echo ($isSet && $diagnosisData["class1st"] == $data["idx"]) ? " selected" : ""; ?>>
                <?php echo $data["text"]; ?>
              </option>
            <?php endforeach; ?>
          </select>
        </dd>

        <dt class="essential">小分類</dt>
        <dd>
          <select class="form-select" name="class2nd" id="class2nd" onchange="ChangeValue(this)" style="width: 150px;">
            <option value="" hidden>選択</option>

            <?php if ($isSet): ?>
              <?php foreach ($optionDatas["class2nd"][$diagnosisData["class1st"]] as $data): ?>
                <option value="<?php echo $data["idx"]; ?>"<?php echo ($diagnosisData["class2nd"] == $data["idx"]) ? " selected" : ""; ?>>
                  <?php echo $data["text"]; ?>
                </option>
              <?php endforeach; ?>
            <?php endif; ?>
          </select>
        </dd>

        <dt class="essential">レベル</dt>
        <dd>
          <select class="form-select" name="level" onchange="ChangeLevel(this)" style="width: 100px;">
            <option value="" hidden>選択</option>

            <?php for($i = 0; $i <= 3; $i++): ?>
              <option value="<?= $i ?>"<?php echo ($isSet && $diagnosisData["level"] == $i) ? " selected" : ""; ?>>
                <?= $levelTexts[$i]; ?>
              </option>
            <?php endfor; ?>
          </select>
        </dd>	

        <dt class="essential">タイトル</dt>
        <dd><input class="form-control" name="title" type="text" placeholder="タイトルを入力してください" value="<?php echo ($isSet) ? $diagnosisData["title"] : ""; ?>"/></dd>
      </dl>
    </div>
  </div>

  <div class="emegra card" style="margin-top: 32px;">
    <div class="card-header">問題</div>

    <div class="card-body">
      <style type="text/css">
        dl.emegra.question { grid-template-columns: 140px 1fr; }
      </style>
      <dl class="emegra question">
        <dt>問項数</dt>
        <dd><?php echo ($isSet) ? $diagnosisData["question_num"] : "0"; ?>題項</dd>
        <input type="number" name="question_num" value="<?php echo ($isSet) ? $diagnosisData["question_num"] : ""; ?>" hidden/>
        
        <dt class="essential">診断時間</dt>
        <dd><input type="number" class="form-control" name="time_limit" style="width: 80px;" value="<?php echo ($isSet) ? $diagnosisData["time_limit"] : "50"; ?>"/>分</dd>
        
				<dt class="essential">問項一覧</dt>
        <div style="width: 100%; display: flex;">

          <style type="text/css">
            div.emegra-table th, div.emegra-table td { padding: 0; }
            div.emegra-table thead, div.emegra-table tbody tr { display: table; width: 100%; }
            div.emegra-table tbody { display: block; }
            div.emegra-table tbody {
              height: 100px;
              overflow-y: scroll;
            }
          </style>
          <div class="emegra-table">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th style="width: 60px;">No</th>
                  <th>問項タイトル</th>
                  <th>タイプ</th>
                  <th>点数</th>
                  <th><input type="checkbox" id="check-question_list" value="" onclick="CheckingList(this);"/></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style="width: 60px;">1</td>
                  <td>1</td>
                  <td>1</td>
                  <td>1</td>
                  <td>1</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </dl>
    </div>
  </div>
</form>