<?php
  $levelTexts = ["無級", "初級", "中級", "高級"];
  /*
    作成：朴昰成
    作成日：24/06/11
  */
  $selectTypeDatas = array(
    "level" => "レベル",
    "class" => "問項種別",
  );
  /* ここまで */

  /*
    作成：朴昰成
    修正：朴昰成
    修正日：24/06/11
  */

  /* 修正前：
    $url = explode("?", $_SERVER["REQUEST_URI"])[0];
    if (!isset($_SESSION)) { session_start(); }
  */

  /* 修正後： */
  if (!isset($_SESSION)) { session_start(); }
  $url = explode("?", $_SERVER["REQUEST_URI"]);
  $route = $url[0];

  $isSearch = array(
    "select" => false,
  );

  $queryDatas = array();
  if (isset($url[1])) {
    $querys = explode("&", $url[1]);
    foreach ($querys as $query) {
      $queryData = explode("=", $query);

      if ($queryData[0] == "select") {
        $queryDatas["select"] = explode("-", $queryData[1]);
        $isSearch["select"] = true;
      }
      else {
        $queryDatas[$queryData[0]] = $queryData[1];
        $isSearch[$queryData[0]] = true;
      }
    }
  }
  /* ここまで */

	$firstNo = $diagnosisDatas->getTotalItemCount();
	$firstNo -= (($diagnosisDatas->getCurrentPageNumber() - 1) * $diagnosisDatas->getitemCountPerPage());
  /*
    作成：朴昰成
    削除：朴昰成
    削除日：24/06/11

  削除前：

    if (isset($searchData)) {
      $searchKey = array_keys($searchData)[0];
      $searchValue = $searchData[$searchKey];
    }
  ここまで */
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

  /*
    作成：朴昰成
    削除：朴昰成
    削除日：24/06/11

  削除前：
    .info-num {
      height: 100%;
      display: flex;
      justify-content: end;
    }

    input.search {
      width: 150px;
    }
    button.emegra.search.confirm {
      height: 30px;
      width: 100px;
      flex-shrink: 0;
      
      font-size: 15px;
      font-weight: 400;
    }

    table.emegra tr { grid-template-columns: 50px 100px repeat(2, 80px) 60px 1fr 50px 60px 60px; }
    table.emegra tr.index {
      padding-top: 8px;
      padding-bottom: 4px;
      grid-template-areas:
      "no id  class    class   level title num criteria update"
      "no id class1st class2nd level title num criteria update";
    }
    table.emegra tr.index > th {
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
    }
  ここまで */

	.list-title {
		text-align: left;
		
		cursor: pointer;
	}
	.list-title:hover { text-decoration: underline; }

	.pagination-place, .button-place {
		margin-top: 10px;
		display: flex;
		justify-content: center;
	}
	.button-place { justify-content: space-between; }
</style>
<content class="header">
  <div class="title">ITスキル診断問題管理</div>
</content>

<content class="main">
	<div style="width: 100%; display: flex; align-items: end; justify-content: space-between;">
		<div class="info-num">
      <div class="count">診断問題総計<div class="num"><?php echo $totalNum; ?></div>部</div>
		</div>

		<div style="display: flex;">
      <!--
        作成：朴昰成
        修正：朴昰成
        修正日：24/06/11
      -->
      
      <!-- 修正前： <?php /* />
        <select class="form-select form-select-sm" style="width: 150px; margin-right: 8px;" onchange="ChangeSearch(this.value)">
          <option value="level"<?php echo (isset($searchData) && $searchKey == "level") ? " selected" : ""; ?>>レベル</option>
          <option value="class1st"<?php echo (isset($searchData) && $searchKey == "class1st") ? " selected" : ""; ?>>大分類</option>
          <option value="class2nd"<?php echo (isset($searchData) && $searchKey == "class2nd") ? " selected" : ""; ?>>小分類</option>
        </select>
        <div style="width: 150px; margin-right: 8px;">
          <select class="form-select form-select-sm" id="select-search">
            <?php if (isset($searchData)): ?>
              <?php if ($searchKey == "class1st"): ?>
                <?php foreach ($inputOptionDatas[$searchKey] as $data): ?>
                  <option value="<?php echo $data["idx"]; ?>"<?php echo ($data["idx"] == $searchValue) ? " selected" : ""; ?>><?php echo $data["text"]; ?></option>
                <?php endforeach; ?>
              <?php elseif ($searchKey == "class2nd"): ?>
                <?php foreach ($class2ndDatas as $data): ?>
                  <option value="<?php echo $data; ?>"<?php echo ($data == $searchValue) ? " selected" : ""; ?>><?php echo ($data == "Cpp") ? "C++" : $data; ?></option>
                <?php endforeach; ?>
              <?php else: ?>
                <?php for($i = 0; $i <= 3; $i++): ?>
                  <option value="<?= $i; ?>"<?php echo ($searchValue == $i) ? " selected" : ""; ?>><?= $levelTexts[$i]; ?></option>
                <?php endfor; ?>
              <?php endif; ?>
            <?php else: ?>
              <option value="" hidden>選択</option>
              <?php for($i = 0; $i <= 3; $i++): ?>
                <option value="<?= $i; ?>"><?= $levelTexts[$i]; ?></option>
              <?php endfor; ?>
            <?php endif; ?>
          </select>
        </div>
        <button class="emegra search confirm" onclick="SearchDiagnosis()">検索</button>
      <?php */ ?> -->

      <!-- 修正後： -->
      <select class="form-select form-select-sm" id="select-select_type" style="width: 120px; margin-right: 8px;" onchange="ChangeSelectType(this)">
        <option value="">全て</option>

        <?php foreach ($selectTypeDatas as $value => $text): ?>
          <option value="<?= $value; ?>"<?php echo ($isSearch["select"] && $queryDatas["select"][0] == $value) ? " selected" : ""?>><?= $text; ?></option>
        <?php endforeach; ?>
      </select>

      <select class="form-select form-select-sm" id="select-select_value" style="width: 120px; margin-right: 8px;" onchange="ChangeSelectValue(this)">
        <?php if ($isSearch["select"]): ?>
          <?php if ($queryDatas["select"][0] == "level"): ?>
            <?php foreach ($levelTexts as $value => $text): ?>
              <option value="<?= $value; ?>"<?php echo ($queryDatas["select"][1] == $value) ? " selected" : ""; ?>><?= $text; ?></option>
            <?php endforeach; ?>
          <?php elseif ($queryDatas["select"][0] == "class"): ?>
            <?php foreach ($optionDatas["class1st"] as $data): ?>
              <option value="<?php echo $data["idx"]; ?>"<?php echo ($queryDatas["select"][1] == $data["idx"]) ? " selected" : ""; ?>><?php echo $data["text"]; ?></option>
            <?php endforeach; ?>
          <?php else: ?>
            <?php foreach ($optionDatas[$queryDatas["select"][0]] as $data): ?>
              <option value="<?php echo $data["idx"]; ?>"<?php echo ($queryDatas["select"][1] == $data["idx"]) ? " selected" : ""; ?>><?php echo $data["text"]; ?></option>
            <?php endforeach; ?>
          <?php endif; ?>
        <?php else: ?>
          <option value="" hidden>選択</option>
        <?php endif; ?>
      </select>

      <select class="form-select form-select-sm" id="select-select_class" style="width: 120px;" onchange="Select(this)">
        <?php if ($queryDatas["select"][0] == "class"): ?>
          <?php foreach ($optionDatas["class2nd"][$queryDatas["select"][1]] as $data): ?>
            <option value="<?php echo $data["idx"]; ?>"<?php echo ($data["idx"] == $queryDatas["select"][2]) ? " selected" : ""; ?>><?php echo $data["text"]; ?></option>
          <?php endforeach; ?>
        <?php else: ?>
          <option value="" hidden>選択</option>
        <?php endif; ?>
      </select>
      <!-- ここまで -->
		</div>
	</div>

  <div class="emegra-table">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th rowspan="2">No</th>
          <th rowspan="2">問題ID</th>
          <th colspan="2">種別</th>
          <th rowspan="2">レベル</th>
          <th rowspan="2">タイトル</th>
          <th rowspan="2">問項数</th>
          <th rowspan="2">合格基準</th>
          <th rowspan="2">変更日</th>
        </tr>
        <tr>
          <th>大分類</th>
          <th>小分類</th>
        </tr>
      </thead>
      <tbody>
        <?php if (empty(iterator_to_array($diagnosisDatas))): ?>
          <td colspan="9"> データがありません。</td>
        <?php else: ?>
          <?php foreach ($diagnosisDatas as $index => $data): ?>
            <tr>
              <td><?php echo $firstNo - $index; ?></td>
              <td><?php echo $data["code"]; ?></td>

              <td><?php echo $optionDatas[$data["class1st"]]; ?></td>
              <td><?php echo $optionDatas[$data["class2nd"]]; ?></td>

              <td><?php echo $levelTexts[$data["level"]]; ?></td>
              <td class="start"><a onclick="self.location.href='./detail/<?php echo $data['idx']; ?>'"><?php echo $data["title"]; ?></a></td>
              <td><?php echo $data["question_num"]; ?>問項</td>

              <?php
                $points = explode(",", $data["result_points"]);
                $passPoint = $points[count($points) - 2];
              ?>
              <td><?php echo $passPoint; ?>点</td>
              <td><?php echo date("y.m.d", strtotime($data["date_start"])); ?></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>

	<div class="pagination-place" style="margin-top: 10px;">
		<?php echo $this->paginationControl($diagnosisDatas, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
	</div>

	<div class="button-place" style="margin-top: 10px;">
		<div></div>

		<div>
			<button class="emegra" onclick="self.window.location='./input'">新規登録</button>
		</div>	
	</div>
</content>

<script type="text/javascript">
  /*
    作成：朴昰成
    削除：朴昰成
    削除日：24/06/11

  削除前： <?php /* ?>
    const selectSearch = document.getElementById("select-search");

    let searchOption = "<?php echo (isset($searchData)) ? $searchKey : "level"; ?>";

    function ChangeSearch(value) {
      selectSearch.replaceChildren();
      searchOption = value;

      var option = document.createElement("option");
      option.value = "";
      option.innerText = "選択";
      option.hidden = true;
      selectSearch.appendChild(option);

      switch(value) {
        case "level":
          <?php for ($i = 0; $i <= 3; $i++): ?>
            var option = document.createElement("option");
            option.value = <?= $i; ?>;
            option.innerText = "<?= $levelTexts[$i]; ?>";
            selectSearch.appendChild(option);
          <?php endfor; ?>
          break;
        case "class1st":
          <?php foreach ($inputOptionDatas["class1st"] as $data): ?>
            var option = document.createElement("option");
            option.value = <?php echo $data["idx"]; ?>;
            option.innerText = "<?php echo $data["text"]; ?>";
            selectSearch.appendChild(option);
          <?php endforeach; ?>
          break;
        case "class2nd":
          <?php foreach ($class2ndDatas as $data): ?>
            var option = document.createElement("option");
            option.value = "<?php echo $data; ?>";
            option.innerText = "<?php echo ($data == "Cpp") ? "C++" : $data; ?>";
            selectSearch.appendChild(option);
          <?php endforeach; ?>
          break;
      }
    }

    function SearchDiagnosis() {
      if (selectSearch.value == "") {
        alert("検索するデータを選択してください。");
        selectSearch.focus();
        return false;
      }

      let url = "<?= $url ?>?" + searchOption + "=" + selectSearch.value;
      self.window.location = url;
    }
  <?php */ ?> ここまで */
  /*
    作成：朴昰成
    作成日：24/06/11
  */
  const selectSelectType = document.getElementById("select-select_type");
  const selectSelectValue = document.getElementById("select-select_value");
  const selectSelectClass = document.getElementById("select-select_class");

  function ChangeSelectType(element) {
    if (element.value == "") { Select(element); }

    selectSelectValue.replaceChildren();

    var option = document.createElement("option");
    option.value = "";
    option.hidden = true;
    option.innerText = "選択";
    selectSelectValue.appendChild(option);

    switch (element.value) {
      case "level":
        <?php foreach ($levelTexts as $value => $text): ?>
          var option = document.createElement("option");
          option.value = "<?php echo $value; ?>";
          option.innerText = "<?php echo $text; ?>";
          selectSelectValue.appendChild(option);
        <?php endforeach; ?>
        break;
      case "class":
        <?php foreach ($optionDatas["class1st"] as $data): ?>
          var option = document.createElement("option");
          option.value = "<?php echo $data["idx"]; ?>";
          option.innerText = "<?php echo $data["text"]; ?>";
          selectSelectValue.appendChild(option);
        <?php endforeach; ?>
        break;
    }
  }

  function ChangeSelectValue(element) {
    console.log(element.value);
    if (selectSelectType.value != "class") { Select(element); }

    selectSelectClass.replaceChildren();

    var option = document.createElement("option");
    option.value = "";
    option.hidden = true;
    option.innerText = "選択";
    selectSelectClass.appendChild(option);

    switch (element.value) {
      <?php foreach ($optionDatas["class1st"] as $class1stData): ?>
        case "<?php echo $class1stData["idx"]; ?>":
          <?php foreach ($optionDatas["class2nd"][$class1stData["idx"]] as $class2ndData): ?>
            var option = document.createElement("option");
            option.value = "<?php echo $class2ndData["idx"]; ?>";
            option.innerText = "<?php echo $class2ndData["text"]; ?>";
            selectSelectClass.appendChild(option);
          <?php endforeach; ?>
          break;
      <?php endforeach; ?>
    }
  }

  function Select(element) {
    <?php
      $newQuery = "?";

      if (!empty($queryDatas)) {
        foreach ($queryDatas as $key => $data) {
          if ($key == "page") { continue; }
          if ($key == "select") { continue; }

          $newQuery .= $key . "=" . implode("-", $data) . "&";
        }
      }

      $url = $route . $newQuery;
    ?>

    let url = "<?= $url; ?>";

    if (element.value != "") { url += "select=" + selectSelectType.value + "-" + selectSelectValue.value + "-"; }
    if (element == selectSelectClass) { url += selectSelectClass.value + "-"; }
    url = url.slice(0, -1);

    self.window.location = url;
  }
  /* ここまで */
</script>