<?php
	$levelTexts = array("0級", "初級", "中級", "高級");

	if (!isset($_SESSION)) { session_start(); }

	$isSet = false;
	if (isset($_COOKIE["diagnosisData"])) {
		$isSet = true;
    $diagnosisData = json_decode($_COOKIE["diagnosisData"], true);
		setcookie("diagnosisData", "", time() - 3600, "/");
	}

	$isEdit = false;
	if (isset($diagnosisData["idx"])) {
		$isSet = true;
		$isEdit = true;

		$pointDatas = explode(",", $diagnosisData["result_points"]);
		$textDatas = explode(",", $diagnosisData["result_texts"]);
		$commentDatas = explode(",", $diagnosisData["result_comments"]);

		for ($i = 1; $i <= 4; $i++) {
			$diagnosisData["point" . $i] = $pointDatas[$i - 1];
			$diagnosisData["text" . $i] = $textDatas[$i - 1];
			$diagnosisData["comment" . $i] = $commentDatas[$i - 1];
		}
	}
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

<form id="form" method="post" action="./confirm">
	<?php if ($isEdit): ?>
		<input name="idx" value="<?php echo $diagnosisData["idx"]; ?>" hidden/>
	<?php endif; ?>
	<input name="question_idxs" value="<?php echo ($isSet) ? $diagnosisData["question_idxs"] : ""; ?>" hidden/>
	<input name="totalPoint" value="" hidden/>

	<style type="text/css">
		option { color: black; }
		input::placeholder { font-style: italic; }
	</style>

	<div class="emegra card">
		<div class="card-header">設定</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.setting { grid-template-columns: 140px 1fr; }
			</style>
			<dl class="emegra setting">
				<!-- <?php /* ?> Delete 24/05/17
				削除前：
				<dt>職別コード</dt>
				<dd><input class="form-control form-control-sm" name="code" style="width: 150px;" readonly value="<?php echo ($isSet) ? $diagnosisData["code"] : $code; ?>"/></dd>
				<?php */ ?> -->

				<dt class="essential">大分類</dt>
				<dd>
					<select class="form-select" name="class1st" onchange="ChangeClass1st(this)" style="width: 150px;">
						<option value="" hidden>選択</option>
						<?php foreach ($optionDatas["class1st"] as $data): ?>
							<option value="<?php echo $data["idx"]; ?>"<?php echo ($isSet && $diagnosisData["class1st"] == $data["idx"]) ? " selected" : ""; ?>>
								<?php echo $data["text"]; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt class="essential">小分類</dt>
				<dd>
					<select class="form-select" name="class2nd" id="class2nd" onchange="ChangeValue(this)" style="width: 150px;">
						<option value="" hidden>選択</option>
						<?php if ($isSet): ?>
							<?php foreach ($optionDatas["class2nd"][$diagnosisData["class1st"]] as $data): ?>
								<option value="<?php echo $data["idx"]; ?>"<?php echo ($diagnosisData["class2nd"] == $data["idx"]) ? " selected" : ""; ?>>
									<?php echo $data["text"]; ?>
								</option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</dd>

				<dt class="essential">レベル</dt>
				<dd>
					<select class="form-select" name="level" onchange="ChangeLevel(this)" style="width: 100px;">
						<option value="" hidden>選択</option>
						<?php for($i = 0; $i <= 3; $i++): ?>
							<option value="<?= $i ?>"<?php echo ($isSet && $diagnosisData["level"] == $i) ? " selected" : ""; ?>>
								<?= $levelTexts[$i]; ?>
							</option>
						<?php endfor; ?>
					</select>
				</dd>	

				<dt class="essential">タイトル</dt>
				<dd><input class="form-control" name="title" type="text" placeholder="タイトルを入力してください" value="<?php echo ($isSet) ? $diagnosisData["title"] : ""; ?>"/></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">問題</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.question { grid-template-columns: 140px 1fr; }
			</style>
			<dl class="emegra question">
				<dt class="essential">問項数</dt>
				<dd><input type="number" class="form-control" name="question_num" style="width: 80px;" value="<?php echo ($isSet) ? $diagnosisData["question_num"] : "35"; ?>"/>問題</dd>

				<dt class="essential">診断時間</dt>
				<dd><input type="number" class="form-control" name="time_limit" style="width: 80px;" value="<?php echo ($isSet) ? $diagnosisData["time_limit"] : "50"; ?>"/>分</dd>

				<dt class="essential" id="correct-title">問項一覧</dt>
				<div style="width: 100%; display: flex;">
					<style type="text/css">
						table.emegra tr { grid-template-columns: 50px 1fr 60px 50px; }
						table.emegra th, table.emegra td { padding: 5px 0 !important; }
					</style>
					<table class="emegra">
						<thead>
							<tr>
								<th>No</th>
								<th>問項タイトル</th>
								<th>タイプ</th>
								<th>点数</th>
							</tr>
						</thead>
						<tbody id="tbody-question_list">
							<?php if ($isSet): ?>
								<?php foreach ($questionDatas as $index => $data): ?>
									<tr>
										<td><?= $index + 1; ?></td>
										<td style="text-align: left" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-title="<?php echo $data->question; ?>" data-bs-content=""><div><?php echo $data->title; ?></div></td>
										<td><?php echo $data->type; ?></td>
										<td><?php echo $data->point; ?></td>
									</tr>
								<?php endforeach; ?>
								<tr>
									<td style="grid-column: 1 / 4;"></td>
									<td><?php echo $diagnosisData["totalPoint"]; ?>点</td>
								</tr>
							<?php else: ?>
								<tr>
									<td style="grid-column: 1 / 5;">設定で大分類、小分類、レベルを選択し、左側のボタンを押してください。</td>
								</tr>
							<?php endif; ?>
						</tbody>
					</table>
					<button type="button" class="emegra" onclick="CreateList()" style="margin-left: 8px;">問題作成</button>
				</div>
			</dl>
		</div>
	</div>

	
	<div class="modal fade" id="modal-question_select" tabindex="-1" data-bs-backdrop="static">
		<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
			<div class="modal-content">
				<div class="modal-header" style="padding: 0;">
					<table class="emegra">
						<thead>
							<tr style="padding-right: 32px;">
								<th><input type="checkbox"/></th>
								<th>タイトル</th>
								<th>タイプ</th>
								<th>点数</th>
							</tr>
						</thead>
					</table>
				</div>
				<div class="modal-body" style="padding: 0;">
					<table class="emegra">
						<tbody id="tbody-question_select">
							<?php foreach ($questionDatas as $data): ?>
								<?php
									$popContent = $numTexts[0] . ReplaceSymbol($data["answer1"]);
									for ($i = 2; $i <= 5; $i++) {
										if ($data["answer" . $i] == null) { break; }
										$popContent .= "<br/>" . $numTexts[$i -1] . ReplaceSymbol($data["answer" . $i]);
									}
								?>
								<tr>
									<td><input type="checkbox" value="<?php echo $data["idx"]; ?>"/></td>
									<td class="left" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-title="<?php echo ReplaceSymbol($data["question"]); ?>" data-bs-content="<?php echo $popContent; ?>" data-bs-html="true"><?php echo $data["title"]; ?></td>
									<td><?php echo $data["type"]; ?></td>
									<td><?php echo $data["point"]; ?></td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<div class="modal-footer" style="justify-content: center;">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="width: 120px;">閉じる</button>
					<button type="button" class="emegra" onclick="AddQuestion()">追加</button>
				</div>
			</div>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">情報</div>

		<div class="card-body">
			<style type="text/css">
				table.evaluation {
					width: 100%;
					text-align: center;
				}
				table.evaluation tr {
					display: grid;
					grid-template-columns: 100px 150px 150px 1fr;
					gap: 10px 8px;
				}
				table.evaluation td {
					padding: 4px 0;
					display: flex;
					align-items: center;
					justify-content: center;
				}
			</style>
			<table class="evaluation">
				<thead>
					<tr>
						<th>評価等級</th>
						<th>評価点数</th>
						<th>評価</th>
						<th>評価コメント</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>A</td>
						<td style="display: flex; justify-content:space-between">
							<input class="form-control form-control-sm" name="point1" style="width: 50px;" oninput="ChangePoint(this)" value="<?php echo ($isSet) ? $diagnosisData["point1"] : "91"; ?>"/>
							~
							<input class="form-control form-control-sm" style="width: 50px;" readonly value="100"/>
						</td>
						<td><input class="form-control form-control-sm" name="text1" value="<?php echo ($isSet) ? $diagnosisData["text1"] : ""; ?>"/></td>
						<td><input class="form-control form-control-sm" name="comment1" value="<?php echo ($isSet) ? $diagnosisData["comment1"] : ""; ?>"/></td>
					</tr>
					<tr>
						<td>B</td>
						<td style="display: flex; justify-content:space-between">
							<input class="form-control form-control-sm" name="point2" style="width: 50px;" oninput="ChangePoint(this)" value="<?php echo ($isSet) ? $diagnosisData["point2"] : "78"; ?>"/>
							~
							<input class="form-control form-control-sm" id="point1Child" readonly style="width: 50px;" value="<?php echo ($isSet) ? $diagnosisData["point1"] - 1 : "90"; ?>"/>
						</td>
						<td><input class="form-control form-control-sm" name="text2" value="<?php echo ($isSet) ? $diagnosisData["text2"] : ""; ?>"/></td>
						<td><input class="form-control form-control-sm" name="comment2" value="<?php echo ($isSet) ? $diagnosisData["comment2"] : ""; ?>"/></td>
					</tr>
					<tr>
						<td>C</td>
						<td style="display: flex; justify-content:space-between">
							<input class="form-control form-control-sm" name="point3" style="width: 50px;" oninput="ChangePoint(this)" value="<?php echo ($isSet) ? $diagnosisData["point3"] : "60"; ?>"/>
							~
							<input class="form-control form-control-sm" id="point2Child" readonly style="width: 50px;"  value="<?php echo ($isSet) ? $diagnosisData["point2"] - 1 : "77"; ?>"/>
						</td>
						<td><input class="form-control form-control-sm" name="text3" value="<?php echo ($isSet) ? $diagnosisData["text3"] : ""; ?>"/></td>
						<td><input class="form-control form-control-sm" name="comment3" value="<?php echo ($isSet) ? $diagnosisData["comment3"] : ""; ?>"/></td>
					</tr>
					<tr>
						<td>D</td>
						<td style="display: flex; justify-content:space-between">
							<input class="form-control form-control-sm" name="point4" readonly style="width: 50px;" value="0"/>
							~
							<input class="form-control form-control-sm" id="point3Child" readonly style="width: 50px;"  value="<?php echo ($isSet) ? $diagnosisData["point3"] - 1 : "59"; ?>"/>
						</td>
						<td><input class="form-control form-control-sm" name="text4" value="<?php echo ($isSet) ? $diagnosisData["text4"] : ""; ?>"/></td>
						<td><input class="form-control form-control-sm" name="comment4" value="<?php echo ($isSet) ? $diagnosisData["comment4"] : ""; ?>"/></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back();">戻る</button>

	<?php if ($isEdit): ?>
		<button class="emegra" onclick="Update();">修正</button>
	<?php else: ?>
		<button class="emegra" onclick="Regist();">確認画面へ</button>
	<?php endif; ?>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript">
	const questionListBody = document.getElementById("tbody-question_list");
	const selectInputs = document.getElementsByTagName("select");

	const questionSelectBody = document.getElementById("tbody-question_select");
	const modalDiv = document.getElementById("modal-question_select");
	const modal = new bootstrap.Modal(modalDiv);

	const form = document.getElementById("form");

	window.onload = function() {
		SetValue();
		<?php if ($isSet): ?>
			ReadList();
		<?php endif; ?>
	}

	function SetValue() {
		<?php if ($isSet): ?>
			for (let i = 0; i < selectInputs.length; i++ ) {
				var select = selectInputs.item(i);
				if (select.value == "") { select.dataset.value = ""; }
				else { select.dataset.value = "1"; }
			}
		<?php else: ?>
			for (let i = 0; i < selectInputs.length; i++ ) {
				var select = selectInputs.item(i);
				if (select.value == "") { select.dataset.value = ""; }
				else { select.dataset.value = "1"; }
			}
		<?php endif; ?>
	}


	function ChangeValue(element) { element.dataset.value = element.value; }

	function ChangeClass1st(element) {
		ChangeValue(element);

		form.class2nd.replaceChildren();
		form.class2nd.dataset.value = "";

		switch (element.value) {
			<?php foreach ($optionDatas["class2nd"] as $value => $class2nd): ?>
				case "<?php echo $value; ?>":
					var option = document.createElement("option");
					option.value = "";
					option.innerText = "選択";
					option.hidden = true;
					form.class2nd.appendChild(option);

					<?php foreach ($class2nd as $data): ?>
						var option = document.createElement("option");
						option.value = <?php echo $data["idx"]; ?>;
						option.innerText = "<?php echo $data["text"]; ?>";
						class2nd.appendChild(option);
					<?php endforeach; ?>
					break;
			<?php endforeach; ?>
		}
	}

	function ChangeLevel(element) {
		ChangeValue(element);

		switch (element.value) {
			<?php foreach ($resultDatas as $idx => $data): ?>
				case "<?php echo $idx; ?>":
					<?php foreach ($data as $name => $value): ?>
						form.<?php echo $name; ?>.value = "<?php echo $value; ?>";

						<?php if ($name == "point1" || $name == "point2" || $name == "point3"): ?>
							var pointElement = document.getElementById("<?php echo $name; ?>Child");
							pointElement.value = <?php echo $value - 1; ?>;
						<?php elseif ($name == "point3"): ?>
							var pointElement = document.getElementById("<?php echo $name; ?>Child");
							pointElement.value = 0;
						<?php endif; ?>
					<?php endforeach; ?>
					break;
			<?php endforeach; ?>
		}
	}
	
	function CreateList(element) {
		if (form.class1st.value == "") {
			RequestSelect(form.class1st, "大分類");
			return false;
		}

		if (form.class2nd.value == "") {
			RequestSelect(form.class2nd, "小分類");
			return false;
		}

		if (form.level.value == "") {
			RequestSelect(form.level, "レベル");
			return false;
		}

		const postForm = new FormData();
		postForm.append("class1st", form.class1st.value);
		postForm.append("class2nd", form.class2nd.value);
		postForm.append("level", form.level.value);
		postForm.append("question_num", form.question_num.value);
		postForm.append("time_limit", form.time_limit.value);

		const xhr = new XMLHttpRequest();
		<?php if ($isEdit): ?>
			xhr.open("POST", "../read", true);
		<?php else: ?>
			xhr.open("POST", "./read", true);
		<?php endif; ?>
		xhr.send(postForm);

		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
				console.log(result);
				
				// Check is json
				try {
					questionDatas = JSON.parse(result);
				} catch (e) {
					alert("error");
					console.log(result);
					return false;
				}

				UpdateQuestionDatas(questionDatas);
			}
		}
	}

	<?php if ($isSet): ?>
		function ReadList() {
			const postForm = new FormData();
			postForm.append("question_idxs", form.question_idxs.value);

			const xhr = new XMLHttpRequest();
			<?php if ($isEdit): ?>
				xhr.open("POST", "../read", true);
			<?php else: ?>
				xhr.open("POST", "./read", true);
			<?php endif; ?>
			xhr.send(postForm);

			xhr.onload = () => {
				if (xhr.status == 200) {
					const result = xhr.responseText;
					console.log(result);
					
					// Check is json
					try {
						questionDatas = JSON.parse(result);
					} catch (e) {
						alert("error");
						console.log(result);
						return false;
					}

					UpdateQuestionDatas(questionDatas);
				}
			}
		}
	<?php endif; ?>

	function UpdateQuestionDatas(questionDatas) {
		questionListBody.replaceChildren();

		let point = 0;
		let questionTdxs = "";
		for (let i = 0; i < questionDatas.length; i++) {
			let tr = document.createElement("tr");

			let numTd = document.createElement("td");
			numTd.innerHTML = Number(i) + 1;
			tr.appendChild(numTd);

			let titleTd = document.createElement("td");
			titleTd.style.textAlign = "start";
			titleTd.setAttribute("data-bs-toggle", "popover");
			titleTd.setAttribute("data-bs-placement", "bottom");
			titleTd.setAttribute("data-bs-title", questionDatas[i]["question"]);
			titleTd.setAttribute("data-bs-content", questionDatas[i]["answers"]);
			titleTd.innerHTML = questionDatas[i]["title"];
			tr.appendChild(titleTd);

			let typeTd = document.createElement("td");
			typeTd.innerHTML = questionDatas[i]["type"];
			tr.appendChild(typeTd);

			let pointTd = document.createElement("td");
			pointTd.innerHTML = questionDatas[i]["point"];
			tr.appendChild(pointTd);

			questionListBody.appendChild(tr);
			point += Number(questionDatas[i]["point"]);
			questionTdxs += questionDatas[i]["idx"] + ",";
		}

		const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
		const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))

		let resultTr = document.createElement("tr");
		let emptyTd = document.createElement("td");
		emptyTd.style.gridColumn = "1 / 4";
		resultTr.appendChild(emptyTd);

		let resultTd = document.createElement("td");
		resultTd.innerText = point + "点";
		resultTr.appendChild(resultTd);
		questionListBody.appendChild(resultTr);
		form.totalPoint.value = point;

		form.question_idxs.value = questionTdxs.slice(0, -1);
	}

	modalDiv.addEventListener("show.bs.modal", function (event) {
		let selectCheckboxs = questionSelectBody.getElementsByTagName("input");
		questionIdxs = form.question_idx.value.split(",");

		for (let i = 0; i < selectCheckboxs.length; i++) {
			if (questionIdxs.indexOf(selectCheckboxs[i].value) == -1) {
				selectCheckboxs[i].parentNode.parentNode.hidden = false;
				selectCheckboxs[i].checked = false;
			}
			else {
				selectCheckboxs[i].parentNode.parentNode.hidden = true;
				selectCheckboxs[i].checked = true;
			}
		}
	})
	
	function AddQuestion() {
		let selectCheckboxs = questionSelectBody.getElementsByTagName("input");

		chkCheked = false;
		let questionIdxs = [];
		let createIdxs = [];
		for (let i = 0; i < selectCheckboxs.length; i++) {
			if (selectCheckboxs[i].parentNode.parentNode.hidden == true) {
				questionIdxs.push(selectCheckboxs[i].value);
				
				createIdxs.push(i);
			}
			else if (selectCheckboxs[i].checked == true) {
				chkCheked = true;

				questionIdxs.push(selectCheckboxs[i].value);

				createIdxs.push(i);
			}
		}

		if (chkCheked) {
			questionListBody.replaceChildren();
			for (let i = 0; i < createIdxs.length; i++) {
				let row = selectCheckboxs[createIdxs[i]].parentNode.parentNode.cloneNode(true);
				row.hidden = false;
				row.getElementsByTagName("input")[0].checked = false;
				questionListBody.appendChild(row);
			}

			form.question_idx.value = questionIdxs.join(",");

			modal.hide();
		}
		else {
			alert("追加する問題を選択してください。");
		}
	}
	
	function DeleteQuestion() {
		let listCheckboxs = questionListBody.getElementsByTagName("input");

		chkCheked = false;
		let questionIdxs = form.question_idx.value.split(",");
		let deleteIdxs = [];
		for (let i = 0; i < listCheckboxs.length; i++) {
			if (listCheckboxs[i].checked == true) {
				chkCheked = true;

				for (let j = 0; j < questionIdxs.length; j++) {
					if(questionIdxs[j] == listCheckboxs[i].value)  {
						questionIdxs.splice(j, 1);
						break;
					}
				}

				deleteIdxs.push(i);
			}
		}

		if (chkCheked) {
			if (confirm("削除しますか？") === false) { return false; }

			for (let i = deleteIdxs.length - 1; i >= 0; i--) {
				console.log(deleteIdxs[i]);
				listCheckboxs[deleteIdxs[i]].parentNode.parentNode.remove();
			}

			form.question_idx.value = questionIdxs.join(",");
		}
		else { 
			alert("削除する問題を選択してください。");
		}
	}

	function ChangePoint(element) {
		let pointElement = document.getElementById(element.name + "Child");
		pointElement.value = element.value - 1;
	}

		function Regist() {
			if (form.class1st.value == "") {
				RequestSelect(form.class1st, "大分類");
				return false;
			}

			if (form.class2nd.value == "") {
				RequestSelect(form.class2nd, "小分類");
				return false;
			}

			if (form.level.value == "") {
				RequestSelect(form.level, "レベル");
				return false;
			}

			if (form.title.value == "") {
				RequestSelect(form.title, "タイトル");
				return false;
			}
			
			if (form.question_idxs.value == "") {
				alert("問題を作成してください。");
				questionListBody.focus();
				return false;
			}

			<?php for ($i = 1; $i <= 4; $i++): ?>
				if (form.point<?= $i ?>.value == "") {
					alert("評価点数を入力してください。");
					setTimeout("form.point<?= $i ?>.focus()", 100);
					return false;
				}
				
				if (form.text<?= $i ?>.value == "") {
					alert("評価を入力してください。");
					setTimeout("form.text<?= $i ?>.focus()", 100);
					return false;
				}
				
				if (form.comment<?= $i ?>.value == "") {
					alert("評価コメントを入力してください。");
					setTimeout("form.comment<?= $i ?>.focus()", 100);
					return false;
				}
			<?php endfor; ?>

			form.submit();
		}

	function RequestSelect(element, text) {
		alert(text + "を選択してください");
		element.focus();
	}
</script>