<?php
  $levelTexts = ["無級", "初級", "中級", "高級"];

	$url = explode("?", $_SERVER["REQUEST_URI"])[0];
	if (!isset($_SESSION)) { session_start(); }

	$firstNo = $diagnosisDatas->getTotalItemCount();
	$firstNo -= (($diagnosisDatas->getCurrentPageNumber() - 1) * $diagnosisDatas->getitemCountPerPage());

	if (isset($searchData)) {
		$searchKey = array_keys($searchData)[0];
		$searchValue = $searchData[$searchKey];
	}
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: end;
	}

	input.search {
		width: 150px;
	}
	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		flex-shrink: 0;
		
		font-size: 15px;
		font-weight: 400;
	}

	table.emegra tr { grid-template-columns: 50px 100px repeat(2, 80px) 60px 1fr 50px 60px 60px; }
	table.emegra tr.index {
		padding-top: 8px;
		padding-bottom: 4px;
		grid-template-areas:
    "no id  class    class   level title num criteria update"
    "no id class1st class2nd level title num criteria update";
	}
	table.emegra tr.index > th {
		padding: 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.list-title {
		text-align: left;
		
		cursor: pointer;
	}
	.list-title:hover { text-decoration: underline; }

	.pagination-place, .button-place {
		margin-top: 10px;
		display: flex;
		justify-content: center;
	}
	.button-place { justify-content: space-between; }
</style>
<content class="header">
  <div class="title">ITスキル診断問題管理</div>
</content>

<content class="main">
	<div style="width: 100%; display: flex; align-items: end; justify-content: space-between;">
		<div class="info-num">
      <div class="count">診断問題総計<div class="num"><?php echo $totalNum; ?></div>部</div>
		</div>

		<div style="display: flex;">
			<select class="form-select form-select-sm" style="width: 150px; margin-right: 8px;" onchange="ChangeSearch(this.value)">
				<option value="level"<?php echo (isset($searchData) && $searchKey == "level") ? " selected" : ""; ?>>レベル</option>
				<option value="class1st"<?php echo (isset($searchData) && $searchKey == "class1st") ? " selected" : ""; ?>>大分類</option>
				<option value="class2nd"<?php echo (isset($searchData) && $searchKey == "class2nd") ? " selected" : ""; ?>>小分類</option>
			</select>
			<div style="width: 150px; margin-right: 8px;">
				<select class="form-select form-select-sm" id="select-search">
					<?php if (isset($searchData)): ?>
						<?php if ($searchKey == "class1st"): ?>
							<?php foreach ($inputOptionDatas[$searchKey] as $data): ?>
								<option value="<?php echo $data["idx"]; ?>"<?php echo ($data["idx"] == $searchValue) ? " selected" : ""; ?>><?php echo $data["text"]; ?></option>
							<?php endforeach; ?>
						<?php elseif ($searchKey == "class2nd"): ?>
							<?php foreach ($class2ndDatas as $data): ?>
								<option value="<?php echo $data; ?>"<?php echo ($data == $searchValue) ? " selected" : ""; ?>><?php echo ($data == "Cpp") ? "C++" : $data; ?></option>
							<?php endforeach; ?>
						<?php else: ?>
							<?php for($i = 0; $i <= 3; $i++): ?>
								<option value="<?= $i; ?>"<?php echo ($searchValue == $i) ? " selected" : ""; ?>><?= $levelTexts[$i]; ?></option>
							<?php endfor; ?>
						<?php endif; ?>
					<?php else: ?>
						<option value="" hidden>選択</option>
						<?php for($i = 0; $i <= 3; $i++): ?>
							<option value="<?= $i; ?>"><?= $levelTexts[$i]; ?></option>
						<?php endfor; ?>
					<?php endif; ?>
				</select>
			</div>
			<button class="emegra search confirm" onclick="SearchDiagnosis()">検索</button>
		</div>
	</div>

	<?php if (empty(iterator_to_array($diagnosisDatas))): ?>
		<div class="table-empty" style="margin-top: 16px;">
			データがありません。
		</div>
	<?php else: ?>
    <!--
      作成：朴昰成
      修正：朴昰成
      修正日：240610
    -->

    <!-- 修正前： <?php /* ?>
      <table class="emegra" style="margin-top: 8px;">
        <thead>
          <tr class="index">
            <th style="grid-area: no">No</th>

            <th style="grid-area: class">種別</th>
            <th style="grid-area: class1st">大分類</th>
            <th style="grid-area: class2nd">小分類</th>

            <th style="grid-area: level">レベル</th>
            <th style="grid-area: title">タイトル</th>
            <th style="grid-area: num">問項数</th>
            <th style="grid-area: criteria">合格基準</th>
            <th style="grid-area: update">変更日</th>
            <th style="grid-area: id">問題ID</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($diagnosisDatas as $index => $data): ?>
            <tr>
              <td><?php echo $firstNo - $index ; ?></td>
              <td><?php echo $data["code"]; ?></td>
              <td><?php echo $optionDatas[$data["class1st"]]; ?></td>
              <td><?php echo $optionDatas[$data["class2nd"]]; ?></td>
              <td><?php echo $levelTexts[$data["level"]]; ?></td>
              <td class="link left" onclick="self.location.href='./detail/<?php echo $data['idx']; ?>'"><?php echo $data["title"]; ?></td>
              <td><?php echo $data["question_num"]; ?>問題</td>
              <td>100点</td>
              <td><?php echo date("y.m.d", strtotime($data["date_start"])); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php */ ?> -->

		<!-- 修正後： -->
    <div class="emegra-table">
      <table class="table table-bordered">
        <thead>
            <th rowspan="2">No</th>
            <th colspan="2">種別</th>
            <th rowspan="2">レベル</th>
            <th rowspan="2">タイトル</th>
            <th rowspan="2">問項数</th>
            <th rowspan="2">合格基準</th>
            <th rowspan="2">変更日</th>
            <th rowspan="2">問題ID</th>
          </tr>
            <th>大分類</th>
            <th>小分類</th>
          <tr>

          </tr>
        </thead>
        <tbody>
          <?php foreach ($diagnosisDatas as $index => $data): ?>
            <tr>
              <td><?php echo $firstNo - $index ; ?></td>
              <td><?php echo $data["code"]; ?></td>
              <td><?php echo $optionDatas[$data["class1st"]]; ?></td>
              <td><?php echo $optionDatas[$data["class2nd"]]; ?></td>
              <td><?php echo $levelTexts[$data["level"]]; ?></td>
              <td class="start" style="padding: 0 8px;"><a onclick="self.location.href='./detail/<?php echo $data['idx']; ?>'"><?php echo $data["title"]; ?></a></td>
              <td><?php echo $data["question_num"]; ?>問題</td>
              <td>100点</td>
              <td><?php echo date("y.m.d", strtotime($data["date_start"])); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
		<!-- ここまで -->
	<?php endif; ?>

	<div class="pagination-place" style="margin-top: 10px;">
		<?php echo $this->paginationControl($diagnosisDatas, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
	</div>

	<div class="button-place" style="margin-top: 10px;">
		<div></div>

		<div>
			<button class="emegra" onclick="self.window.location='./input'">新規登録</button>
		</div>	
	</div>
</content>

<script type="text/javascript">
	const selectSearch = document.getElementById("select-search");

	let searchOption = "<?php echo (isset($searchData)) ? $searchKey : "level"; ?>";

	function ChangeSearch(value) {
		selectSearch.replaceChildren();
		searchOption = value;

		var option = document.createElement("option");
		option.value = "";
		option.innerText = "選択";
		option.hidden = true;
		selectSearch.appendChild(option);

		switch(value) {
			case "level":
				<?php for ($i = 0; $i <= 3; $i++): ?>
					var option = document.createElement("option");
					option.value = <?= $i; ?>;
					option.innerText = "<?= $levelTexts[$i]; ?>";
					selectSearch.appendChild(option);
				<?php endfor; ?>
				break;
			case "class1st":
				<?php foreach ($inputOptionDatas["class1st"] as $data): ?>
					var option = document.createElement("option");
					option.value = <?php echo $data["idx"]; ?>;
					option.innerText = "<?php echo $data["text"]; ?>";
					selectSearch.appendChild(option);
				<?php endforeach; ?>
				break;
			case "class2nd":
				<?php foreach ($class2ndDatas as $data): ?>
					var option = document.createElement("option");
					option.value = "<?php echo $data; ?>";
					option.innerText = "<?php echo ($data == "Cpp") ? "C++" : $data; ?>";
					selectSearch.appendChild(option);
				<?php endforeach; ?>
				break;
		}
	}

	function SearchDiagnosis() {
		if (selectSearch.value == "") {
			alert("検索するデータを選択してください。");
			selectSearch.focus();
			return false;
		}

		let url = "<?= $url ?>?" + searchOption + "=" + selectSearch.value;
		self.window.location = url;
	}
</script>