<?php
	$numTexts = array("①", "②", "③", "④", "⑤");

	function ReplaceSymbol($string) {
		$string = str_replace("<", "＜", $string);
		$string = str_replace(">", "＞", $string);
		return $string;
	}
?>

<style type="text/css">
	table.emegra tr { grid-template-columns: 60px 1fr 60px 50px 30px; }
	table.emegra th, table.emegra td { padding: 5px 0 !important; }
</style>

<table class="emegra">
	<thead>
		<tr>
			<th>No</th>
			<th>タイトル</th>
			<th>タイプ</th>
			<th>点数</th>
			<th><input type="checkbox"/></th>
		</tr>
	</thead>
	<tbody id="tbody-question_list">
	</tbody>
</table>
<form id="form">
	保存したデータインデックス<input name="question_idx">
</form>

<button type="button" class="emegra" data-bs-toggle="modal" data-bs-target="#modal-question_select">追加</button>
<button type="button" class="emegra delete" onclick="DeleteQuestion()">削除</button>
<button type="button" class="emegra" onclick="ReadData()">作成</button>

<div class="modal fade" id="modal-question_select" tabindex="-1" data-bs-backdrop="static">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
		<div class="modal-content">
			<div class="modal-header" style="padding: 0;">
				<table class="emegra">
					<thead>
						<tr style="padding-right: 32px;">
							<th>No</th>
							<th>タイトル</th>
							<th>タイプ</th>
							<th>点数</th>
							<th><input type="checkbox"/></th>
						</tr>	
					</thead>
				</table>
			</div>
			<div class="modal-body" style="padding: 0;">
				<table class="emegra">
					<tbody id="tbody-question_select">
						<tr>
							<td style="grid-column: 1 / 4;">データを入力してください。</td>
						</tr>
					</tbody>
				</table>
			</div>
      <div class="modal-footer" style="justify-content: center;">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="width: 120px;">閉じる</button>
        <button type="button" class="emegra" onclick="AddQuestion()">保存</button>
      </div>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript">
	const numTexts = ["①", "②", "③", "④", "⑤"];

	const questionListBody = document.getElementById("tbody-question_list");

	const modalDiv = document.getElementById("modal-question_select");
	const modal = new bootstrap.Modal(modalDiv);
	const questionSelectBody = document.getElementById("tbody-question_select");

	const form = document.getElementById("form");

	let selectCheckboxs = questionSelectBody.getElementsByTagName("input");

	let popoverTriggerList = document.querySelectorAll("[data-bs-toggle='popover']");
	let popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));

	modalDiv.addEventListener("show.bs.modal", function (event) {
		let selectCheckboxs = questionSelectBody.getElementsByTagName("input");
		questionIdxs = form.question_idx.value.split(",");

		let no = 1;
		for (let i = 0; i < selectCheckboxs.length; i++) {
			if (questionIdxs.indexOf(selectCheckboxs[i].value) == -1) {
				selectCheckboxs[i].parentNode.parentNode.hidden = false;
				selectCheckboxs[i].checked = false;
				selectCheckboxs[i].parentNode.parentNode.childNodes[0].innerText = no;
				no++;
			}
			else {
				selectCheckboxs[i].parentNode.parentNode.hidden = true;
				selectCheckboxs[i].checked = true;
			}
		}
	})

	function AddQuestion() {
		chkCheked = false;
		let checkboxIdxs = [];
		for (let i = 0; i < selectCheckboxs.length; i++) {
			if (selectCheckboxs[i].parentNode.parentNode.hidden == true) {
				console.log("hidden" + i);
				checkboxIdxs.push(i);
			}
			else if (selectCheckboxs[i].checked == true) {
				console.log("check" + i);
				chkCheked = true;

				checkboxIdxs.push(i);
			}
		}

		if (chkCheked) {
			AddQuestionByIdxs(checkboxIdxs);
			modal.hide();
		}
		else {
			alert("追加する問題を選択してください。");
		}
	}

	function DeleteQuestion() {
		let listCheckboxs = questionListBody.getElementsByTagName("input");

		chkCheked = false;
		let questionIdxs = form.question_idx.value.split(",");
		let deleteIdxs = [];
		for (let i = 0; i < listCheckboxs.length; i++) {
			if (listCheckboxs[i].checked == true) {
				chkCheked = true;

				for (let j = 0; j < questionIdxs.length; j++) {
					if(questionIdxs[j] == listCheckboxs[i].value) {
						questionIdxs.splice(j, 1);
						break;
					}
				}

				deleteIdxs.push(i);
			}
		}

		if (chkCheked) {
			if (confirm("削除しますか？") === false) { return false; }

			for (let i = deleteIdxs.length - 1; i >= 0; i--) {
				listCheckboxs[deleteIdxs[i]].parentNode.parentNode.remove();
			}

			$totalPoint = 0;
			for (let i = 0; i < questionListBody.childNodes.length - 1; i++) {
				questionListBody.childNodes[i].childNodes[0].innerText = i + 1;
				$totalPoint += Number(questionListBody.childNodes[i].childNodes[3].innerText);
			}
			questionListBody.lastChild[1].innerText = totalPoint + "点";

			form.question_idx.value = questionIdxs.join(",");
		}
		else {
			alert("削除する問題を選択してください。");
		}
	}

	function ReadData() {
		const postForm = new FormData();
		const xhr = new XMLHttpRequest();
		xhr.open("POST", "./read/question", true);
		xhr.send(postForm);
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
				console.log(result);

				// Check is json
				try {
					questionDatas = JSON.parse(result);
				} catch (e) {
					alert("error");
					console.log(result);
					return false;
				}

				UpdateQuestionDatas(questionDatas);
				selectCheckboxs = questionSelectBody.getElementsByTagName("input");

				xhr.open("POST", "./read/list", true);
				xhr.send(postForm);
				xhr.onload = () => {
					if (xhr.status == 200) {
						const result = xhr.responseText;
						console.log(result);

						// Check is json
						try {
							questionIdxs = JSON.parse(result);
						} catch (e) {
							alert("error");
							console.log(result);
							return false;
						}

						checkboxIdxs = [];
						for (let i = 0; i < selectCheckboxs.length; i++) {
							for (let j = 0; j < questionIdxs.length; j++) {
								if (questionIdxs[j] == selectCheckboxs[i].value) {
									checkboxIdxs.push(i);
									break;
								}
							}
						}
						AddQuestionByIdxs(checkboxIdxs);
					}
				}
			}
		}
	}

	function UpdateQuestionDatas(questionDatas) {
		questionSelectBody.replaceChildren();
		
		for (let i = 0; i < questionDatas.length; i++) {
			let tr = document.createElement("tr");

			let td = document.createElement("td");
			td.innerText = i + 1;
			tr.appendChild(td);

			td = document.createElement("td");
			td.classList.add("left");
			td.style.overflow = "hidden";
			td.style.textOverflow = "ellipsis";
			td.style.whiteSpace = "nowrap";

			td.setAttribute("data-bs-toggle", "popover");
			td.setAttribute("data-bs-placement", "bottom");
			td.setAttribute("data-bs-title", questionDatas[i]["question"]);

			let popoverContent = numTexts[0] + ChangeSymbol(questionDatas[i]["answer1"]);
			for (let j = 2; j <= 5; j++) {
				if (questionDatas[i]["answer" + j] == null) { break; }
				popoverContent += "<br/>" + numTexts[j - 1] + ChangeSymbol(questionDatas[i]["answer" + j]);
			}
			td.setAttribute("data-bs-content", popoverContent);
			td.setAttribute("data-bs-html", "true");
			td.innerText = questionDatas[i]["title"];
			tr.appendChild(td);

			td = document.createElement("td");
			td.innerText = questionDatas[i]["type"];
			tr.appendChild(td);

			td = document.createElement("td");
			td.innerText = questionDatas[i]["point"];
			tr.appendChild(td);

			td = document.createElement("td");
			let checkbox = document.createElement("input");
			checkbox.type = "checkbox";
			checkbox.value = questionDatas[i]["idx"];
			td.appendChild(checkbox);
			tr.appendChild(td);

			questionSelectBody.appendChild(tr);
		}
		popoverTriggerList = document.querySelectorAll("[data-bs-toggle='popover']");
		popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));
	}

	function ChangeSymbol(string) {
		string = string.replace(/</g, "＜");
		string = string.replace(/>/g, "＞");
		return string;
	}
	
	function AddQuestionByIdxs(checkboxIdxs) {
		questionListBody.replaceChildren();

		console.log(checkboxIdxs)

		questionIdxs = [];
		totalPoint = 0;
		for (let i = 0; i < checkboxIdxs.length; i++) {
			let row = selectCheckboxs[checkboxIdxs[i]].parentNode.parentNode.cloneNode(true);
			row.hidden = false;
			row.childNodes[0].innerText = i + 1;
			row.childNodes[4].childNodes[0].checked = false;
			questionListBody.appendChild(row);
			totalPoint += Number(row.childNodes[3].innerText);

			questionIdxs.push(selectCheckboxs[checkboxIdxs[i]].value);
		}

		let tr = document.createElement("tr");
		let td = document.createElement("td");
		td.style.gridColumn = "1 / 4";
		tr.appendChild(td);

		td = document.createElement("td");
		td.innerText = totalPoint + "点";
		tr.appendChild(td);

		td = document.createElement("td");
		tr.appendChild(td);
		questionListBody.appendChild(tr);

		popoverTriggerList = document.querySelectorAll("[data-bs-toggle='popover']");
		popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl));

		form.question_idx.value = questionIdxs.join(",");
	}
</script>