<?php
	$levelTexts = ["権限なし", "承認者"];

	$picTexts["n"] = "権限なし";
	$picTexts["y"] = "担当者";
	
	if (!isset($_SESSION)) { session_start(); }

	// Check create or update
	$isUpdate = false;
	if (isset($adminData["idx"])) { $isUpdate = true; }
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

<div class="emegra card">
	<div class="card-header">管理者情報</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.setting { grid-template-columns: 140px 1fr; }
		</style>

		<?php if ($isUpdate): ?>
			<input name="idx" value="<?php echo $adminData["idx"]; ?>" hidden/>
		<?php endif; ?>

		<dl class="emegra setting">
			<dt>固有番号</dt>
			<dd><?php echo $adminData["code"]; ?></dd>

			<dt>職別コード</dt>
			<dd><?php echo $adminData["code"]; ?></dd>

			<dt>権限</dt>
			<dd><?php echo $levelTexts[$adminData["level"]]; ?></dd>

			<dt>ログインID</dt>
			<dd><?php echo $adminData["id"]; ?></dd>

			<?php if (!$isUpdate): ?>
				<dt>パスワード</dt>
				<dd><?php echo $adminData["password"]; ?></dd>
			<?php endif; ?>

			<dt>名前</dt>
			<dd><?php echo $adminData["name"]; ?></dd>

			<dt>担当者</dt>
			<dd><?php echo $picTexts[$adminData["pic"]]; ?></dd>

			<?php if (isset($adminData["smtp_password"])): ?>
				<dt>SMTP パスワード</dt>
				<dd><?php echo $adminData["smtp_password"]; ?></dd>
			<?php endif; ?>
		</dl>
	</div>
</div>

<form id="form" method="post" action="./<?php echo ($isUpdate) ? "modify" : "input"; ?>">
	<?php foreach ($adminData as $key => $data): ?>
		<input type="hidden" name="<?php echo $key; ?>" value="<?php echo $data; ?>"/>
	<?php endforeach; ?>
</form>


<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="Return();">戻る</button>

	<?php if ($isUpdate): ?>
		<button class="emegra" onclick="Update();">修正</button>
	<?php else: ?>
		<button class="emegra" onclick="Regist();">登録</button>
	<?php endif; ?>
</div>

<script type="text/javascript">
	const form = document.getElementById("form");

	<?php if ($isUpdate): ?>
		function Update() {
			const postForm = new FormData(form);
			const xhr = new XMLHttpRequest();
			xhr.open("POST", "./update", true);
			xhr.send(postForm);
			xhr.onload = () => {
				if (xhr.status == 200) {
					const result = xhr.responseText;
					if (result == "success") {
						alert("修正しました。");
						self.location.href = "./detail/<?php echo $adminData["code"]; ?>";
					}
					else {
						alert("Error");
						console.log(result);
					}
				}
			}
		}
	<?php else: ?>
		function Regist() {
			const postForm = new FormData(form);
			const xhr = new XMLHttpRequest();
			xhr.open("POST", "./create", true);
			xhr.send(postForm);
			xhr.onload = () => {
				if (xhr.status == 200) {
					const result = xhr.responseText;
					if (result == "success") {
						alert("登録しました。");
						self.location.href = "./list";
					}
					else if (result == "code overlapped") {
						alert("コードが重複しています");
						form.submit();
					}
					else if (result == "id overlapped") {
						alert("IDが重複しています");
						form.submit();
					}
					else {
						alert("Error");
						console.log(result);
					}
				}
			}
		}
	<?php endif; ?>

	function Return() {
		form.submit();
	}
</script>