<?php
	$levelTexts = ["無し", "承認", "マスター"];
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: end;
	}

	.search-place {
		width: 100%;
		margin-top: 20px;
		display: grid;
		grid-template-columns: 50px 150px 150px 1fr 65px 150px 110px 65px 200px;
		column-gap: 10px;

		text-align: center;
	}
	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		
		font-size: 15px;
		font-weight: 400;
	}

	.pagination-place, .button-place {
		margin-top: 10px;
		display: flex;
		justify-content: center;
	}
	.button-place { justify-content: space-between; }
</style>
<content class="header">
	<div class="title">ITスキル診断管理者管理</div>
</content>

<content class="main">
  <div class="emegra-table">
    <table class="table table-bordered">
      <thead>
        <tr class="index">
          <th>No</th>
          <th>ログインID</th>
          <th>名前</th>
          <th>権限</th>
          <th>担当者</th>
          <th>最終ログイン</th>
          <th>更新日</th>
        </tr>
      </thead>
      <tbody>
        <?php if (empty($adminDatas)): ?>
          <td colspan="7">管理者情報がありません。</td>
        <?php else: ?>
          <?php foreach($adminDatas as $data): ?>
            <tr>
              <td><?php echo $data["num"]; ?></td>
              <td class="link start"><a onclick="self.location.href='./detail/<?php echo $data['code']; ?>'"><?php echo $data["id"]; ?></a></td>
              <td class="start"><?php echo $data["name"]; ?></td>
              <td><?php echo $levelTexts[$data["level"]]; ?></td>
              <td><?php echo ($data["pic"] == "y") ? "o" : "x"; ?></td>
              <td class="start"><?php echo (empty($data["date_login"])) ? "無し" : date("Y/m/d h:i:s", strtotime($data["date_login"])); ?></td>
              <td class="start"><?php echo date("Y/m/d h:i:s", strtotime($data["date_start"])); ?></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>

	<div class="pagination-place">
		<?php echo $this->paginationControl($this->noticelist, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
	</div>
	<div class="button-place">
		<div></div>

		<div>
			<button class="emegra" onclick="self.window.location='./input'">新規登録</button>
		</div>	
	</div>
</content>