<?php
	if (!isset($_SESSION)) { session_start(); }

	$isApprover = false;
	if ($_SESSION["user"]["level"] >= 1) { $isApprover = true; }

	function ChkDeleter($data, $optionDatas) {
		if ($optionDatas[$data["status"]] == "新規") { return true; }
		return false;
	}
	
	$url = $_SERVER["REQUEST_URI"];
	$url = $url . "?";
	$query = explode("?", $url)[1];
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: end;
	}

	.search-place {
		width: 100%;
		margin-top: 20px;
		display: grid;
		grid-template-columns: 50px 150px 150px 1fr 65px 150px 110px 65px 200px;
		column-gap: 10px;

		text-align: center;
	}
	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		
		font-size: 15px;
		font-weight: 400;
	}

	table.emegra tr { grid-template-columns: 50px 1fr 100px 70px 50px repeat(2,150px); }
	table.emegra tr.index {
		padding-top: 8px;
		padding-bottom: 4px;
		grid-template-areas:
		"no id name level ipc date_login date_start";
	}
	table.emegra tr.index > th {
		padding: 4px 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.list-title {
		text-align: left;
		
		cursor: pointer;
	}
	.list-title:hover { text-decoration: underline; }

	.button-place {
		display: flex;
		justify-content: space-between;
	}
</style>
<content class="header">
	<div class="title">管理者管理一覧</div>
</content>

<content class="main">
	<?php if ( 	empty($questionDatas)): ?>
		<div class="table-empty" style="margin-top: 16px;">
			データがありません。
		</div>
		
	<?php else: ?>
		<table class="emegra" style="margin-top: 8px;">
			<thead>
				<tr class="index">
					<th style="grid-area: no">no</th>
					<th style="grid-area: id">ログインID</th>
					<th style="grid-area: name">名前</th>
					<th style="grid-area: level">レベル</th>
					<th style="grid-area: ipc">担当者</th>
					<th style="grid-area: date_login">最終ログイン</th>
					<th style="grid-area: date_start">更新日</th>
				</tr>
			</thead>
			<tbody>
				<?php /*foreach($questionDatas as $data): ?>
					<tr>
						<td><?php echo $data["num"]; ?></td>
						<td><?php echo $optionDatas[$data["status"]]; ?></td>
						<td><?php echo $optionDatas[$data["class1st"]]; ?></td>
						<td><?php echo $optionDatas[$data["class2nd"]]; ?></td>
						<td><?php echo $optionDatas[$data["level"]]; ?></td>
						<td class="list-title" onclick="self.location.href='./detail/<?php echo $data['idx']; ?>';"><?php echo $data["title"]; ?></td>
						<td><?php echo $optionDatas[$data["type"]]; ?></td>
						<td><?php echo $data["point"]; ?></td>
						<td><?php echo date("y.m.d", strtotime($data["date_regist"])); ?></td>
						<td><?php echo (isset($data["date_approve"])) ? date("y.m.d", strtotime($data["date_approve"])) : "未承認"; ?></td>
						<td><input name="checkIdx" type="checkbox" value="<?php echo $data["idx"]; ?>" onclick="Checking(this);" style="cursor: pointer;"<?php echo ($isApprover || ChkDeleter($data, $optionDatas)) ? "" : " disabled"; ?>></td>
					</tr>
				<?php endforeach; */?>
					<tr onclick="self.location.href='./detail'">
						<td>1</td>
						<td style="text-align: start;">manage@gngs.co.jp</td>
						<td style="text-align: start;">マスター</td>
						<td style="text-align: start;">マスター</td>
						<td>x</td>
						<td><?= date("Y-m-d H:m:s"); ?></td>
						<td><?= date("Y-m-d H:m:s"); ?></td>
					</tr>
			</tbody>
		</table>
	<?php endif; ?>

	<div class="button-place" style="margin-top: 10px;">
		<div>
			<?php echo $this->paginationControl($this->noticelist, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
		</div>
		<div>
			<button class="emegra" onclick="self.window.location='./regist'">新規登録</button>
		</div>	
	</div>
</content>

<script type="text/javascript">
</script>
