<?php
	echo $this->doctype();

	if ($this->title == "") { $this->title = "G&GService"; }
?>

<html lang="jp">
	<head>
		<meta charset="utf-8">	
		<?php
			echo $this->headTitle($this->title)->setSeparator(" - ")->setAutoEscape(false);
			
			echo $this->headMeta()
				->appendName("title", $this->title)
				->appendName("description", $this->description)
				->appendName("keywords", $this->keywords)
				->appendName("robots", "ALL")
				->appendName("Distribution", "GNGService")
				->appendName("author", "drapiece@gngs.co.jp")
				->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
				->appendHttpEquiv("X-UA-Compatible", "IE=edge");
		?>
		<meta name="viewport" content="height=device-height">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="/css/applicant_layout.css" rel="stylesheet" type="text/css">
	</head>

<body>
<header>
	<div class="left-column"><img src="/img/hd_logo.png" alt="logo" height="56px" width="auto"></div>
	<div class="middle-column" style="font-size:bold">株式会社ジエンジサービス</div>
	<div class="right-column" id="date-container"></div>
</header>	
<main>
		<?php echo $this->content; ?>
		<button type="button" class="btn btn-primary" id="loadPage" data-bs-toggle="modal" data-bs-target="#exampleModal" style="display:none">
</button>

<div class="modal fade" id="exampleModal" style="backdrop-filter: blur(5px);" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style=" display:inline" >
        <h3 class="modal-title" id="exampleModalLabel"style="text-align: center;">案内</h3>
      </div>
      <div class="modal-body">
	  <h5 style="font-size:18px;text-align:center; padding:15px;">
            株式会社ジエンジサービスの
            ITスキル診断申込です。
            <br>    <br>
            項目に沿って必要事項を入力してください。
            </h5>
      </div>
    </div>
  </div>
</div>

</main>


<script>
function getDayOfWeek(day) {
    const weekdays = ['日', '月', '火', '水', '木', '金', '土'];
    return weekdays[day];
}

function getCurrentDate() {
    const today = new Date();
    const year = today.getFullYear();
    const month = today.getMonth() + 1;
    const date = today.getDate();
    const day = getDayOfWeek(today.getDay());

    return year + '年 ' + addZero(month) + '月 ' + addZero(date) + '日（' + day + '）';
}

function addZero(num) {
    return (num < 10 ? '0' : '') + num;
}

function displayCurrentDate() {
    const dateContainer = document.getElementById('date-container');
    dateContainer.textContent = getCurrentDate();
}

window.onload = displayCurrentDate;

	function onLoadEvent() {
		loadPage.click();
	}
	window.onload = function() {
    onLoadEvent();
    displayCurrentDate();
};

</script>
