<!-- 構造の改善
	作成：朴昰成
	作成日：2024/03/13
-->
<?php
	echo $this->doctype();

	if ($this->title == "") { $this->title = "G&GService"; }
?>

<html lang="jp">
	<head>
		<meta charset="utf-8">	
		<?php
			echo $this->headTitle($this->title)->setSeparator(" - ")->setAutoEscape(false);
			
			echo $this->headMeta()
				->appendName("title", $this->title)
				->appendName("description", $this->description)
				->appendName("keywords", $this->keywords)
				->appendName("robots", "ALL")
				->appendName("Distribution", "GNGService")
				->appendName("author", "drapiece@gngs.co.jp")
				->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
				->appendHttpEquiv("X-UA-Compatible", "IE=edge");
		?>
		<meta name="viewport" content="height=device-height">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="/css/applicationLogin_layout.css" rel="stylesheet" type="text/css">
	</head>

	<body class="login">
		<div class="vector" id="vector"></div>
		<div class="gngLogo_back"></div>
		<header class="logo">
			<img src="/img/hd_logo.png" alt="logo" height="64px" width="auto"/>
			<a class="logo-title">試験診断申込サイト</a>
		</header>
			
		<main>
				<?php echo $this->content; ?>
		</main>

		<footer class="descript"><a>GOMS Order・Received・Service.</a> Copyright G&GService. All Right Reserved.</footer>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	</body>
</html>
<!-- ここまで -->