<!-- 構造の変更
	作成：朴昰成
	修正：朴昰成
	修正日：2024/03/15
-->

<!-- 修正前： <?php /* ?>
<!doctype html>
<html lang="jp">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
  html {
    height: 100%
  }
  </style>
  <title>G&G Service</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
  <style type='text/css'>
  body,
  p,
  div,
  span,
  a,
  textarea,
  input,
  select,
  i,
  button,
  h5,
  h4,
  h3,
  h2,
  h1 {
    font-family: 'Noto Sans JP', sans-serif;
  }
  </style>
</head>

<body class="h-100">
  <div class="position-relative h-100" id="content">
    <div class="d-flex flex-column align-items-center position-absolute top-50 start-50 translate-middle">
      <?php foreach ($message as $string) : ?>
      <label class="text-center"><?= $string ?></label>
      <?php endforeach; ?>
      <button class="btn btn-primary mt-3" id="bt_return" type="button">閉じる</button>
    </div>
  </div>

  <script>
  const form = document.getElementById("form_main");

  document.getElementById("bt_return").addEventListener("click", () => {
    window.location.href = "/user/main";
  });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

</body>

</html>
<?php */ ?> -->

<!-- 修正後： -->
<style type="text/css">
	label { margin-bottom: 8px; }
</style>

<div class="emegra card">
	<?php foreach ($message as $string): ?>
		<label class="text-left"><?php echo $string; ?></label>
	<?php endforeach; ?>
</div>

<div class="btn-place" style="margin-bottom: 32px;">
	<button class="emegra big cancel" style="margin-top: 40px;" onclick="window.location.href='/user/main';">戻る</button>
</div>
<!-- ここまで -->