<!doctype html>
<html lang="jp">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
  html {
    height: 100%
  }
  </style>
  <title>G&G Service</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
  <style type='text/css'>
  body,
  p,
  div,
  span,
  a,
  textarea,
  input,
  select,
  i,
  button,
  h5,
  h4,
  h3,
  h2,
  h1 {
    font-family: 'Noto Sans JP', sans-serif;
  }
  </style>
</head>

<body class="d-flex flex-column align-items-center">
  <div>
    <div class="align-self-start">
      <br>
      <h1><?= $examData["name"] ?> 様</h1>
      <br>
      <p>試験を受けて誠にありがとうございます。</p>
      <p>以下の問題の正しい答えを選択してください。</p>
      <br>
    </div>

    <form class=" text-start" id="form_exam" method="post">
      <?php foreach ($questionDatas as $questionIdx => $data) : ?>
      <div class="card">
        <div class="card-header">
          <h6><?= $questionIdx + 1 . ". " . $data["question"] ?></h6>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <?php foreach (explode("|", $data["answers"]) as $answerIdx => $answer) : ?>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="question<?= $questionIdx ?>"
                id="Q<?= $questionIdx ?>.A<?= $answerIdx ?>" value="<?= $answerIdx + 1 ?>">
              <label class="form-check-label" for="Q<?= $questionIdx ?>.A<?= $answerIdx ?>">
                <?= $answer ?>
              </label>
            </div>
            <?php endforeach; ?>
          </blockquote>
        </div>
      </div>
      <?php endforeach; ?>
    </form>

    <div class="border-0 mb-1 d-flex flex-column text-center align-items-center">
      <div class="text-start">
        <br><br>
        <p>お疲れさまでした。</p>
        <p>以下の送信ボタンをクリックしてください。</p>
        <br>
      </div>
      <button type="button" class="btn btn-primary w-25" id="bt_chk">送信</button>
      <br><br>
    </div>

    <div class="modal fade" id="modal" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5">回答確認</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body d-flex flex-column">
            <label>回答を登録しますか？</label>
            <?php foreach ($questionDatas as $questionIdx => $data) : ?>
            <label id="answer<?= $questionIdx ?>"></label>
            <?php endforeach; ?>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="bt_submit">OK</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          </div>
        </div>
      </div>
    </div>

    <script>
    const form = document.getElementById("form_exam");

    window.addEventListener("DOMContentLoaded", () => {
      if (sessionStorage.getItem("id") == null) {
        alert("ログインをしてください。");
        self.location.href = "/user/main";
      } else {
        sessionStorage.removeItem("id");
      }
    });

    document.getElementById("bt_chk").addEventListener("click", () => {
      <?php foreach ($questionDatas as $index => $data) : ?>
      var selected = Array.from(form.question<?= $index ?>).find(radio => radio.checked);
      if (selected == null) {
        alert("答えなかった問題があります。");
        form.question<?= $index ?>[0].focus();
        return false;
      } else {
        console.log(selected.value);
        document.getElementById("answer<?= $index ?>").innerText = "<?= $index + 1 ?>. " + selected.value;
      }
      <?php endforeach; ?>
      const modal = new bootstrap.Modal(document.getElementById("modal"), {
        keyboard: false
      });
      modal.show();
    });

    document.getElementById("bt_submit").addEventListener("click", () => {
      form.submit();
    });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</body>

</html>