
  <div id="content">
    <div>
      <p>G&G Service 試験受け</p>
      <form class="d-flex flex-column" id="form_login" style="width: 350px;" method="post">
        <div>
          <span style="min-width: 80px;">ID</span>
          <input class="form-control" name="id" type="text" placeholder="IDを入力ください">
        </div>
        <div>
          <span style="min-width: 80px;">Password</span>
          <input class="form-control" name="password" type="password" placeholder="パスワードを入力ください">
        </div>
        <button class="btn btn-primary mt-3" id="bt_login" type="button">ログイン</button>
      </form>
    </div>
  </div>

  <script>
  const form = document.getElementById("form_login");
  const url = window.location.href;

  document.getElementById("bt_login").addEventListener("click", function() {
    if (form.id.value == "") {
      alert("IDを入力ください");
      form.id.focus();
      return false;
    }

    if (form.password.value == "") {
      alert("パスワードを入力ください");
      form.password.focus();
      return false;
    }

    const postForm = new FormData();
    postForm.append("id", form.id.value);
    postForm.append("password", form.password.value);

    const xhr = new XMLHttpRequest();
    console.log(url);
    xhr.open("POST", url, true);
    xhr.send(postForm);

    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        if (result == "wrong id") {
          alert("有効ではないIDです");
          form.id.focus();
        } else if (result == "wrong password") {
          alert("パスワードを確認してください");
          form.password.focus();
        } else if (result == "success") {
          sessionStorage.setItem("id", form.id.value);
          self.location.href = "../exam/" + url.substring(url.indexOf("login/", 0) + 6, url.length);
        }
      }
    }
  });
  </script>
