<!doctype html>
<html lang="jp">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
  html {
    height: 100%
  }

  #logo {

    color: #000000;
    font-weight: bold;
    font-size: 32px;
    text-transform: uppercase;
    padding: 5px;
    margin-bottom: 20px;
    background: linear-gradient(to right, #270a09, #8ca6ce);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  </style>
  <title>G&G Service</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">
  <style type='text/css'>
  body,
  p,
  div,
  span,
  a,
  textarea,
  input,
  select,
  i,
  button,
  h5,
  h4,
  h3,
  h2,
  h1 {
    font-family: 'Noto Sans JP', sans-serif;
  }
  </style>
</head>

<body class="h-100">
  <div class="position-relative h-100" id="content">
    <div class="d-flex flex-column align-items-center position-absolute top-50 start-50 translate-middle">
      <p class="h1 text-center" id="logo">G&G Service 試験受け</p>
      <form class="d-flex flex-column" id="form_main" style="width: 350px;" method="post">
        <div class="d-flex border-0 mb-1 align-items-baseline">
          <span style="min-width: 80px;">URL</span>
          <input class="form-control" name="url" type="text" placeholder="URLを入力ください">
        </div>
        <button class="btn btn-primary mt-3" id="bt_next" type="button">次へ</button>
      </form>
    </div>
  </div>

  <script>
  const form = document.getElementById("form_main");

  document.getElementById("bt_next").addEventListener("click", function() {
    if (form.url.value == "") {
      alert("URLを入力ください");
      form.url.focus();
      return false;
    }

    const postForm = new FormData();
    postForm.append("url", form.url.value);

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "./main", true);
    xhr.send(postForm);

    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        if (result == "success") {
          window.location.href = "./login/" + form.url.value;
        } else if (result == "fail") {
          alert("有効ではないURLです。")
        }
      }
    }
  });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

</body>

</html>