<style type="text/css">
	span { margin-bottom: 8px; }
	input { height: 48px; }
</style>

<div class="emegra card">
	<div class="card-header">G&G Service 試験受け</div>

	<div class="card-body" style="display: flex; flex-direction: column;">
		<span>URL</span>
		<input class="form-control" id="url" type="text" placeholder="URLを入力ください">

		<button class="emegra big" style="margin-top: 40px;" onclick="submit();">次へ</button>
	</div>
</div>

<script>
	const url = document.getElementById("url");

	function submit () {
		if (url.value.trim() == "") {
			alert("URLを入力ください");
			url.focus();
			return false;
		}

		const postForm = new FormData();
		postForm.append("url", url.value);

		const xhr = new XMLHttpRequest();
		xhr.open("POST", window.location.href, true);
		xhr.send(postForm);

		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
				if (result == "success") {
					window.location.href = "./login/" + url.value;
				} else if (result == "fail") {
				alert("有効ではないURLです。")
				}
			}
		}
	}
</script>