<!-- 画面変更
	作成：丁錫圓
	修正：朴昰成
	修正日：2027/03/12
-->

<!-- 修正前： <?php /* ?>
!-- 
html修正
作成日：2024/02/22
--
!--修正前：　<?php !*?> 
<?php
$level[1] = "初級";
$level[2] = "中級";
$level[3] = "高級";
?>

<div class="p-5 align-self-center w-75">
  <p class="mb-5 h2">問題一覧</p>
  <table class="table striped mt-5 table-bordered">
    <tr>
      <th class="col-1 bg-secondary text-white">No.</th>
      <th class="col-1 bg-secondary text-white">レベル</th>
      <th class="col-1 bg-secondary text-white">種別</th>
      <th class="col-7 bg-secondary text-white">問題</th>
      <th class="col-2 bg-secondary text-white">登録日</th>
    </tr>

    <?php foreach ($questionDatas as $index => $data) : ?>
      <tr style="cursor: pointer;" onclick="Move2Detail(<?= $data['idx'] ?>)">
        <td><?= $dataIndex - $index ?></td>
        <td><?= $level[$data["question_level"]] ?></td>
        <td><?= $typeTitles[$index] ?></td>
        <td><?= $data["question"] ?></td>
        <td><?= date("Y-m-d", strtotime($data["wdate"])) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>

  <nav class="mt-2 d-flex flex-row justify-content-center gap-3">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="list?page=1">first</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != 1 ? "1" : $cPage - 1 ?>">
          <span class=" unclick">&laquo;</span>
        </a>
      </li>
      <?php for ($page = 1; $page <= $totalPage; $page = $page + 1) : ?>
        <li class=" page-item <?php echo $page == $cPage ? "active" : "" ?>">
          <a class="page-link" href="list?page=<?= $page ?>"><?= $page ?></a>
        </li>
      <?php endfor; ?>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != $totalPage ? $totalPage : $cPage + 1 ?>">
          <span class="unclick">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?= $totalPage ?>">last</a>
      </li>
    </ul>
  </nav>
</div>

<script>
  function Move2Detail(idx) {
    sessionStorage.setItem("listPage", <?= $cPage ?>);
    window.location.href = " ./list/detail/" + idx;
  }
</script>
<?php *! ?> --
!-- 修正後： --
<?php
$level[0] = "その他";
$level[1] = "高等学校";
$level[2] = "専門学校";
$level[3] = "短期大学";
$level[4] = "大学";
$level[5] = "大学院";

$cert=array("無","有");
?>

<div class="p-5 align-self-center w-75">
  <p class="mb-5 h2">問題一覧</p>
  <table class="table striped mt-5 table-bordered">
    <tr>
      <th class="col-1 bg-secondary text-white">No.</th>
      <th class="col-2 bg-secondary text-white">アカデミック</th>
      <th class="col-1 bg-secondary text-white">キャリア</th>
      <th class="col-1 bg-secondary text-white">資格(IT)</th>
      <th class="col-1 bg-secondary text-white">種別</th>
      <th class="col-5 bg-secondary text-white">問題</th>
      <th class="col-1 bg-secondary text-white">登録日</th>
    </tr>

    <?php foreach ($questionDatas as $index => $data) : ?>
      <tr style="cursor: pointer;" onclick="Move2Detail(<?= $data['idx'] ?>)">
        <td><?= $dataIndex - $index ?></td>
				!-- 表示するデータの変更
					作成：丁錫圓
					修正：朴昰成
					修正日：2024/03/08
				--

				!-- 修正前： <?php !* ?>
        <td><?= $level[$data["academic"]] ?></td>
				<?php *! ?> --

				!-- 修正後： --
        <td>
					<?php echo $level[$data["academic"] / 2]; ?>
					<?php echo ($data["academic"] % 2 == 1) ? "" : "&nbspIT専攻"; ?>
				</td>
				!-- ここまで --
        <td><?= $data["career"]?>年</td>
        <td><?= $cert[$data["certificate"]] ?></td>
        <td><?= $typeTitles[$index] ?></td>
        <td><?= $data["question"] ?></td>
        <td><?= date("Y-m-d", strtotime($data["wdate"])) ?></td>
      </tr>
    <?php endforeach; ?>
  </table>

  <nav class="mt-2 d-flex flex-row justify-content-center gap-3">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="list?page=1">first</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != 1 ? "1" : $cPage - 1 ?>">
          <span class=" unclick">&laquo;</span>
        </a>
      </li>
      <?php for ($page = 1; $page <= $totalPage; $page = $page + 1) : ?>
        <li class=" page-item <?php echo $page == $cPage ? "active" : "" ?>">
          <a class="page-link" href="list?page=<?= $page ?>"><?= $page ?></a>
        </li>
      <?php endfor; ?>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != $totalPage ? $totalPage : $cPage + 1 ?>">
          <span class="unclick">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?= $totalPage ?>">last</a>
      </li>
    </ul>
  </nav>
</div>

<script>
  function Move2Detail(idx) {
    sessionStorage.setItem("listPage", <?= $cPage ?>);
    window.location.href = " ./list/detail/" + idx;
  }
</script>
!-- ここまで --
<?php */ ?> -->

<!-- 修正後： -->
<?php
	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	$certificateTexts = array("無", "有");
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">問題一覧</h1>

<style text="text/css">
	table.emegra tr { grid-template-columns: 40px 3fr 1fr 1fr 2fr 2fr 1fr 1fr; }
</style>
<table class="emegra">
	<thead>
		<tr>
			<th>No.</th>
			<th>学歴</th>
			<th>履歴</th>
			<th>資格(IT)</th>
			<th>種別</th>
			<th>問題</th>
			<th>登録日</th>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($questionDatas as $index => $data): ?>
			<tr onclick="self.location.href='./list/detail/<?php echo $data['idx']; ?>';">
				<td><?= $dataIndex - $index; ?></td>
				<td>
					<?php echo $academicTexts[$data["academic"] / 2]; ?>
					<?php echo ($data["academic"] % 2 == 1) ? "&nbspIT専攻" : ""; ?>
				</td>
				<td><?php echo $data["career"]; ?>年</td>
				<td><?php echo $certificateTexts[$data["certificate"]]; ?></td>
				<td><?php echo $typeTitles[$index]; ?></td>
				<td><?php echo $data["question"]; ?></td>
				<td><?php echo date("Y-m-d", strtotime($data["wdate"])); ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div style="margin-top: 32px;">
	<?php echo $this->partial("pagination", $paginationData); ?>
</div>
<!-- ここまで -->