<?php 
echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); 
$currentDate = date("Y-m-d H:i:s");
$dateSchedule = date("Y-m-d H:i", strtotime($currentDate . ' +30 minutes'));

$urlLink = "../../diagnosis/detail/";

// function InitStyle() { return " ; color: ;"; }
$isGenderNull = false;
$isGender = false;

$isMethod = false;
$isITMajor = false;
$isITSkill = false;
$isITEducation1 = false;
$isITEducation2 = false;
$isITEducation3 = false;
$isITEducation4 = false;
$isClass1st1 = false;
$isClass1st2 = false;
$isClass1st3 = false;
$isClass1st4 = false;
$isClass1st5 = false;
$isLevel0 = false;
$isLevel1 = false;
$isLevel2 = false;
$isLevel3 = false;
$isLanguage = false;
/* log
	作成：丁錫圓
	修正日：24/06/01
*/
$isMailNull = false;
$isMail = false;
// ここまで

// gender
if ($applicantArray["gender"] === NULL) {
    $isGenderNull = true;
}

if ($applicantArray["gender"] == "0") {
    $isGender = true;
}

// method
if ($recordArray["method"] == "WEB") {
    $isMethod = true;
}

// major
if ($recordArray["major"] == "IT・ソフトウェア専攻") {
    $isITMajor = true;
}

// skill
if ($recordArray["skill"] == 0) {
    $isITSkill = true;
}

// education
switch ($recordArray["education"]) {
    case "高卒":
        $isITEducation1 = true;
        break;
    case "専門卒":
        $isITEducation2 = true;
        break;
    case "大卒":
        $isITEducation3 = true;
        break;
    case "大学院卒":
        $isITEducation4 = true;
        break;
}

// class1st
switch ($recordArray["class1st"]) {
    case "WEB":
        $isClass1st1 = true;
        break;
    case "IT基礎":
        $isClass1st2 = true;
        break;
    case "モバイル":
        $isClass1st3 = true;
        break;
    case "サーバ":
        $isClass1st4 = true;
        break;
    case "インフラ":
        $isClass1st5 = true;
        break;
}

// level
if (isset($diagnosisData["level"]) && is_string($diagnosisData["level"])) {
  switch ($diagnosisData["level"]) {
      case "0":
          $isLevel0 = true;
          break;
      case "1":
          $isLevel1 = true;
          break;
      case "2":
          $isLevel2 = true;
          break;
      case "3":
          $isLevel3 = true;
          break;
      default:
          // Optional: handle unexpected values
          break;
  }
} else {
  // Handle the case where "level" is not set or not a string
  // For example, you might want to initialize the variables to false
  $isLevel0 = false;
  $isLevel1 = false;
  $isLevel2 = false;
  $isLevel3 = false;
}

/* log
	作成：丁錫圓
	修正日：24/06/01
*/
//mail Manual/Auto
if ($recordArray["mail_delay"] === NULL) {
  $isMailNull = true;
}
if ($recordArray["mail_delay"] !== NULL) {
  $isMail = true;
}
//言語
if ($recordArray["language"] == "0") {
  $isLanguage = true;
}

// ここまで
// editHTML show question_num
$question_num = isset($diagnosisData['question_num']) ? $diagnosisData['question_num'] : null;
?>


<h1 class="title">ITスキル診断状況管理</h1>

<form id="form" method="post" action="../editok" onsubmit="return handleSubmit()">
	<style type="text/css">
		option { color: black; }
		/* input::placeholder { font-style: italic; } */
  .modal {
    -webkit-backdrop-filter: blur(5px); /* Safari and older versions of Chrome */
    backdrop-filter: blur(5px); /* Standard syntax for modern browsers */
  }

	</style>

	<div class="emegra card">
		<div class="card-header">ITスキル診断者情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns:  repeat(2, 170px 1fr) }
			</style>
			<dl class="emegra info">
				<dt>ID</dt>
				<dd><input class="form-control" name="email" type="text" style="width:220px; " value="<?php echo $applicantArray["email"] ?>" readonly></dd>
				
                <dt class="essential">応募区分</dt>
				<select class="form-select" name="case" style="width:220px;" onchange="ChangeInputStyle(this)" value="<?php echo $recordArray["case"] ?>" >
                        <option value="<?php echo ($recordArray['case']) ?>" selected hidden>
						<?php
							if ($recordArray['case'] == NULL) {
								echo "なし";
							} elseif($recordArray['case']==0) {
								echo "新卒";
							}	else{echo "中途（経歴職）";
							}
							?>					
						</option>
                        <option value="0">新卒</option>
                        <option value="1">中途（経歴職）</option>
                    </select>

                <dt>パスワード</dt>
				<dd><input class="form-control" name="password" type="text" style="width:220px;" value=""></dd>

				<dt class="essential">お名前（漢字）</dt>
				<dd><input class="form-control" id="userInput" name="name" type="text" placeholder="漢字を記入してください。"style="width:220px" maxlength='20' value="<?php echo $applicantArray["name"] ?>"></dd>

                <dt>申込日</dt>
				<dd><input class="form-control" type="text" style="width:220px; " value="<?php echo $applicantArray["apply_date"] ?>" readonly></dd>
				
                <dt class="essential">お名前（カナ）</dt>
				<dd><input class="form-control" name="kana" type="text" placeholder="カナを記入してください。"style="width:220px" maxlength='50' value="<?php echo $applicantArray["kana"] ?>"></dd>

                <dt>性別</dt>
				<dd> 
				<select class="form-select"  name="gender" id="gender" style="width:220px">
					<option value="" <?php echo ($isGenderNull) ? "selected" : "" ?> hidden>未登録</option>
					<option value="0" <?php echo (!$isGenderNull && $isGender) ? "selected" : "" ?>>男</option>
					<option value="1" <?php echo (!$isGenderNull && !$isGender) ? "selected" : "" ?>>女</option>
				</select>


				</dd>
				
                <dt class="essential">学歴</dt>
				<dd>
					<select class="form-select" id="educationId"  style="width:220px" onchange="ChangeEducation(this)">
                        <option value="高卒" <?php echo($isITEducation1) ? "selected" : "" ;?>>高卒</option>
                        <option value="専門卒" <?php echo($isITEducation2) ? "selected" : "" ;?>>専門卒</option>
                        <option value="大卒" <?php echo($isITEducation3) ? "selected" : "" ;?>>大卒</option>
                        <option value="大学院卒" <?php echo($isITEducation4) ? "selected" : "" ;?>>大学院卒</option>
                        <option value="その他"<?php echo ($isITEducation1 || $isITEducation2 || $isITEducation3 || $isITEducation4 ) ? "" : "selected"; ?>>その他</option>
                    </select>
                        <input class="form-control"  style="margin-left: 10px; width:200px;" type="text" placeholder="その他の場合" id="educationInput" name="education" maxlength='20' value="<?php echo ($recordArray['education']) ?>">
				</dd>

				<dt>IT関連資格</dt>
				<dd><input class="form-control" id="certificatesId" name="certificates" type="text"  style="width:220px" placeholder="未登録" value="<?php echo ($applicantArray["certificates"] == null) ? "" : $applicantArray["certificates"]; ?>"></dd> 

        <dt class="essential">生年月日</dt>
				<dd><input class="form-control" id="birth" name="birth" type="text" placeholder="YYYY-MM-DD" autocomplete="off"  style="width:220px" value="<?php echo $applicantArray["birth"] ?>"></dd> 

				<dt>専攻</dt>
				<dd> 
					<select class="form-select" id="majorId" style="width:220px;" onchange="ChangeMajor(this)">
						<option value=""hidden>未登録</option>
            <option value="IT・ソフトウェア専攻"<?php echo ($isITMajor) ? " selected" : ""; ?>>IT・ソフトウェア専攻</option>
            <option value="other"<?php echo ($recordArray["major"] != null && !$isITMajor) ? " selected" : ""; ?>>IT・ソフトウェア以外</option>
            </select>
            <input class="form-control" style="margin-left: 10px; width:200px;" type="text" placeholder="その他の場合" id="majorInput"  name="major" maxlength='20' value='<?php echo ($recordArray['major']) ?>'  />
				</dd>

				<dt>その他</dt>
				<dd><input class="form-control" id="other" name="other" type="text"  style="width:220px" placeholder="未登録" value="<?php echo ($applicantArray["other"] == null) ? "" : $applicantArray["other"]; ?>"></dd> 
			</dl>
		</div>
	</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">診断者ITスキル有無</div>

	<div class="card-body">
		<style type="text/css">

		dl.emegra.setting { grid-template-columns: repeat(1, 180px 1fr); }
				</style>
			<dl class="emegra setting">
                <dt class="essential" id="ITskillTitle">ITスキル有無</dt>
				<dd>
					<select class="form-select" name="skill" id="ITskillId" style="width:220px;" onchange="SkillSelectChange(this.value)">
            <option value="0" <?php echo($isITSkill) ? "selected" : "" ;?>>有</option>
            <option value="1" <?php echo(!$isITSkill) ? "selected" : "" ;?>>無</option>
          </select>
				</dd>
                <dt class="essential" id="class1stTitle">経験分野</dt>
				
				<dd>
					<select class="form-select" name="class1st" id="class1stId" style="width:220px;" onchange="ChangeClass1st(this)">
          <option value="" selected hidden>選択してください。</option>
            <option value="WEB" <?php echo($isClass1st1) ? "selected" : "" ;?>>WEB</option>
            <option value="IT基礎" <?php echo($isClass1st2) ? "selected" : "" ;?>>IT基礎</option>
            <option value="モバイル" <?php echo($isClass1st3) ? "selected" : "" ;?>>モバイル</option>
            <option value="サーバ" <?php echo($isClass1st4) ? "selected" : "" ;?>>サーバ</option>
            <option value="インフラ" <?php echo($isClass1st5) ? "selected" : "" ;?>>インフラ</option>
            <option value="その他"<?php echo ($isClass1st1 || $isClass1st2 || $isClass1st3 || $isClass1st4 || $isClass1st5) ? "" : "selected";?>>その他</option>
          </select>
				</dd>

				<dt class="essential" id=class2ndTitle>経験分野詳細</dt>
				<dd>
				<select class="form-select" name="class2nd" id="class2ndId" style="width:220px;" onchange="ChangeInputStyle(this)">
				<?php if (true): ?>
					<?php
          if (!empty($optionDatas["class2nd"][$recordArray["class1st"]])) {
            $dataArray = $optionDatas["class2nd"][$recordArray["class1st"]];
          }else{
            $dataArray = $optionDatas["class2nd"]['11'];
          }						
					?>

          
          <?php
          $selectedClass2nd = isset($recordArray['class2nd']) ? $recordArray['class2nd'] : null;
          if (!empty($dataArray)) {
              foreach ($dataArray as $data) {
                  echo '<option value="' . $data['idx'] . '"';
                    if ($data['idx'] == $selectedClass2nd) {
                      echo ' selected';
                    }
                    echo '>' . $data['text'] . '</option>';
              }
          }
          ?>


				<?php endif; ?>

			</select>

				</dd>

				<dt id="careerTitle">経験年数</dt>
				<dd><input class="form-control" name="career" id="careerId" type="text" placeholder="記入" style="font-size:15px; width:80px" maxlength='2' value="<?php echo $applicantArray['career']?>">年</dd> 
		</dl>
    <!-- <input type="hidden" name="career" id="noSkillCareer"> -->

	</div>
</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">ITスキル診断問題詳細</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 140px 1fr); }
		</style>
		<dl class="emegra detail">
       <dt class="essential">レベル</dt>
				<dd><select class="form-select" id="levelId" name="level" type="text" style="width:100px;">
					<option value="0"<?php echo $isLevel0 ? "selected" : "" ;?>>無級</option>
					<option value="1"<?php echo $isLevel1 ? "selected" : "" ?>>初級</option>
					<option value="2"<?php echo $isLevel2 ? "selected" : "" ?>>中級</option>
					<option value="3"<?php echo $isLevel3 ? "selected" : "" ?>>高級</option>
					</select>
				</dd>

				<dt class="essential">問題ID</dt>
				<dd>
        <input name="code" type="hidden" style="width:220px;" value="<?php echo isset($diagnosisData['code']) ? htmlspecialchars($diagnosisData['code']) : ''; ?>">
            <div id="codeDisplay" name="codeName" style="padding-right:5px;cursor:pointer;" 
              <?php echo isset($diagnosisData['idx']) ? "onclick='Link(" . $diagnosisData['idx'] . ");'" : '' ?>>
              <?php echo isset($diagnosisData['code']) && $diagnosisData['code'] !== false ? $diagnosisData['code'] : "未登録" ?>
            </div>
             <!-- /* log
          作成：丁錫圓
          修正：丁錫圓
          修正日：24/06/03
        */ -->
        <!-- 修正前： -->
        <!-- <button type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" style="padding: 0px 10px ;border-radius: 8px; background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); color:white;" onclick="diagnosisData();">検索</button> -->
        <!-- 修正後： -->
					<button type="button" id="diagnosisId" style="padding: 0px 10px ;border-radius: 8px; background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); color:white;" onclick="diagnosisValidation();">検索</button>
          <!-- ここまで -->
				</dd> 
        <script>
          function Link(idx) {
            self.location.href = "../../diagnosis/detail/" + idx;
          }
        </script>
				
			<div class="modal modal-sheet py-5" tabindex="-1" role="dialog" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-scrollable" style="margin-top:150px;" role="document">
					<div class="modal-content rounded-4" style=>
            <div class="modal-header border-bottom-0" style="background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); color:white; height: 40px;border-top-left-radius:13px;border-top-right-radius:13px">
              <h3 class="modal-title fs-6" id="exampleModalLabel">診断問題検索</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="filter: invert(100%);"></button>
            </div>
              <div class="modal-body fs-5">
                <table class="table" style="text-align:center; font-size:12px;">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th style="text-align:left;">タイトル</th>
                      <th>問題ID番号</th>
                      <th>選択</th>
                    </tr>
                  </thead>
                    <tbody style="text-align:center">
                    </tbody>
                  </table>
              </div>
              <div class="modal-footer flex-column border-top-0" style="margin-bottom:8px;">
                <button type="button" class="btn btn-lg" data-bs-dismiss="modal" style="width: 180px; font-size: 1rem;background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); color:white;">閉じる</button>
              </div>
          </div>
				</div>
			</div>

				<dt class="essential">問題数</dt>
          <dd>
            <input id="question_numId" class="form-control" type="text" style="width:50px;text-align:center;" value="<?php echo $question_num ?>" readonly>問
          </dd>		             
				<dt class="essential">診断方法</dt>
          <dd>
            <select class="form-select" name="method" style="width:100px;" onchange="ChangeInputStyle(this)" >
              <option value="" selected disabled hidden><?php echo $recordArray['method']?></option>
              <option value="WEB" <?php echo($isMethod) ? "selected" : ""?>>WEB</option>
              <option value="対面"<?php echo(!$isMethod) ? "selected" : "" ;?>>対面</option>
            </select>
				  </dd>
        <dt class="essential">言語選択</dt>
        <dd>
          <select class="form-select" name="language" style="width:100px;" onchange="ChangeInputStyle(this)" >
            <option value="0" <?php echo($isLanguage) ? "selected" : "" ?>>日本語</option>
            <option value="1" <?php echo(!$isLanguage) ? "selected" : "" ?>>韓国語</option>
          </select>
				</dd>
        <!-- // 修正の時
        /*
          作成：名前
          修正：名前
          修正日：24/06/06
        */

        /* 修正前：
        メール転送
        */ -->
        <!-- /* 修正後： */ -->
        <dt class="essential">結果転送</dt>
        <!-- /* ここまで */ -->
        <dd>
        <!-- /* log
          作成：丁錫圓
          修正：丁錫圓
          修正日：24/06/01
        */ -->
        <!-- /* 修正前： -->
        <!-- <option value="<?php echo $recordArray['mail_delay']?>" hidden></option>
            <option value="" selected>手動</option>
            <option value="0">自動</option> -->
          <!-- ここまで -->

          <!-- /* 修正後： */ -->
          <select class="form-select" name="mail_delay" style="width:100px;" onchange="ChangeInputStyle(this)" >
            <option value="" <?php echo($isMailNull) ? "selected" : ""?>>手動</option>
            <option value="0" <?php echo($isMail) ? "selected" : ""?>>自動</option>
          </select>
          <!-- /* ここまで */ -->
				</dd>
		</dl>
	</div>
</div>
<div class="emegra card" style="margin-top: 32px;">
  <div class="card-header">ITスキル診断状況</div>

  <div class="card-body">
    <style type="text/css">
    dl.emegra.detail { grid-template-columns: repeat(2, 150px 1fr); }
    </style>
    <dl class="emegra detail"> 
      <!-- <dt>診断依頼</dt>
      <dd><input class="form-control" type="text" style="width:220px;" id="currentDateTime" readonly></dd> -->

      <dt class="essential">診断予定日</dt>
      <dd><input class="form-control" name="schedule" id="scheduleId" type="text" style="width:220px;" value="<?php echo $recordArray['date_schedule'] ? $recordArray['date_schedule'] : $dateSchedule ?>"></dd>

      <!-- <dt hidden>備考</dt>
      <dd><input class="form-control" name="note" type="text" style="width:220px; " value="<?php echo $recordArray['note']?>" hidden></dd> -->

      <input type="hidden" name="recordindex" value="<?php echo $index?>"></div>
      <input type="hidden" name="applicantindex" value="<?php echo $applicantArray['idx']?>"></div>
    </dl>
  </div>
</div>

  <!-- // 修正の時
/*
	作成：名前
	修正：名前
	修正日：24/06/06
*/ -->
<!-- /* 修正前：
<div class="btn-place" style="margin-top: 32px;">
	<button type="button" class="emegra cancel" onclick="self.location.href='../../situation/list';">戻る</button>
  <button class="emegra" id="btn_save" name="editDatas" value="btn_save"  style="width:150px;" onclick="saveConfirm()">一時保存</button>
	<button class="emegra" id="btn_submit" name="editDatas" value="btn_submit"  style="width:150px;" onclick="editConfirm()">ITスキル診断依頼</button>
</div>

 Request send modal 
<div class="modal" tabindex="-1" role="dialog" id="submitLoading">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h3 style="text-align:center;">依頼転送中です。</h3>
      </div>
    </div>
  </div>
</div>
*/ -->
<!-- /* 修正後： */ -->
<div class="btn-place" style="margin-top: 32px;">
	<button type="button" class="emegra cancel" onclick="self.location.href='../../situation/list';">戻る</button>
  <button class="emegra" id="btn_save" name="editDatas" value="btn_save"  style="width:150px;" onclick="saveConfirm()">保存</button>
	<button class="emegra" id="btn_submit" name="editDatas" value="btn_submit"  style="width:150px;" onclick="editConfirm()">ITスキル診断依頼</button>
</div>

<!-- Request send modal -->
<div class="modal" tabindex="-1" role="dialog" id="submitLoading">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h3 style="text-align:center;" id="processing" style="margin-top: -200px;"></h3>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('processing').innerHTML = "<div class='spinner-border' role='status'></div> <span style='font-size: 20px;'> 診断依頼中。。。<br>少々お待ちください。</span>";

</script>
<!-- /* ここまで */ -->
</form>
<script type="text/javascript">
	const form = document.getElementById("form");
    var selectElement = document.getElementById('majorId');
    var inputElement = document.getElementById('majorInput');
	if (selectElement.value != "other" || selectElement.value == "なし") {
        inputElement.hidden = true;
    } else if (selectElement.value === "other" && selectElement.value !="IT・ソフトウェア専攻") {
        inputElement.hidden = false;
    }
	function ChangeGender(element) {
		ChangeInputStyle(element);
		if (form.gender.value != "other") { 
			form.gender.value = element.value;
		}
	}

	function ChangeMajor(element) {
		ChangeInputStyle(element);
		if (form.major.value != "other") { 
			form.major.value = element.value;
		}
	}

	var selectElement2 = document.getElementById('educationId');
    var inputElement2 = document.getElementById('educationInput');
	if (selectElement2.value != "その他") {
        inputElement2.hidden = true;
    } else if (selectElement2.value === "その他") {
        inputElement2.hidden = false;
    }
	function ChangeEducation(elements) {
		ChangeInputStyle(elements);
		if (form.education.value != "その他") { 
			form.education.value = elements.value;
		}
	}

	// var selectElement3 = document.getElementById('class1stId');
  //   var inputElement3 = document.getElementById('otherclass1st');
	// if (selectElement3.value != "その他") {
  //       inputElement3.hidden = true;
  //   } else if (selectElement3.value === "その他") {
  //       inputElement3.hidden = false;
  //   }


</script>
<!-- <script>
        function ChangeClass1stValue(selectElement) {
            var otherInput = document.getElementById('otherclass1st');
            if (ITskillId.value=="1" && selectElement.value === "その他") {
                otherInput.style.display = 'none';
            } else if(selectElement.value === "その他"){
                otherInput.style.display = 'block';
            } else{
                otherInput.style.display = 'none';
                otherInput.value = selectElement.value;
              }
            }

        function handleSubmit() {
            var selectElement = document.getElementById('class1stId');
            var otherInput = document.getElementById('otherclass1st');
            if (selectElement.value !== "その他") {
                otherInput.value = selectElement.value;
            }
            return true; 
        }

        document.addEventListener('DOMContentLoaded', function() {
            ChangeClass1stValue(document.getElementById('class1stId'));
        });
    </script> -->
<script>
	function ChangeInputStyle(element) {
		element.style.fontStyle = "normal";
		element.style.color = "black";
	}
</script>

<script>
window.onload = function() {
  randomPW();

  var selectedClass2nd = <?php echo json_encode($selectedClass2nd); ?>;

  if (form.skill.value == 1 && selectedClass2nd == null) {
    SkillSelectChange();
  }
  else if(form.skill.value ==1){
    SkillSelectChange2();
  }

  // 作成：丁錫圓
	// 作成日：2406012
  if (form.code.value != "") {
    skillSelect.addEventListener("mousedown", disableEvent);
      class1stBox.addEventListener("mousedown", disableEvent);
      class2ndSelect.addEventListener("mousedown", disableEvent);
      careerSelect.addEventListener("mousedown", disableEvent);
      document.getElementById("levelId").addEventListener("mousedown", disableEvent);
      skillSelect.style.background = "#E2E2E2"
      class1stBox.style.background = "#E2E2E2"
      class2ndSelect.style.background = "#E2E2E2"
      careerSelect.style.background = "#E2E2E2"
      document.getElementById("levelId").style.background = "#E2E2E2"
      diagnosisId.hidden = true;

      const diagnosisCancel = document.createElement("button");
      diagnosisCancel.innerText = "取り消し";
      diagnosisCancel.id = "diagnosisCancel"; 
      diagnosisCancel.style="background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); padding: 0px 10px; color:white; border-radius:5px;"

      const parentElement = diagnosisId.parentNode; 
      parentElement.appendChild(diagnosisCancel);
      diagnosisCancel.addEventListener("click", () => {
        codeDisplay.innerText="";
        form.code.value="";
        skillSelect.removeEventListener("mousedown", disableEvent);
        class1stBox.removeEventListener("mousedown", disableEvent);
        class2ndSelect.removeEventListener("mousedown", disableEvent);
        careerSelect.removeEventListener("mousedown", disableEvent);
        document.getElementById("levelId").removeEventListener("mousedown", disableEvent);

        // Reset styles
        skillSelect.style.background = "";
        class1stBox.style.background = "";
        class2ndSelect.style.background = "";
        careerSelect.style.background = "";
        document.getElementById("levelId").style.background = "";
        diagnosisCancel.hidden = true;
        diagnosisId.hidden = false;

        event.preventDefault();
      });
      
      function disableEvent(event) {
        event.preventDefault(); 
      }  
    }
// ここまで
};
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.ja.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

  <script>
    $(document).ready(function(){
      var birth = document.getElementById("birth");
      $(birth).datepicker({
        format: 'yyyy-mm-dd',
        autohide: true,
        language: 'ja',
        startDate: '1980-01-01',
        endDate: '2010-12-31'
      });
    });
  </script>

<script>
	let skillSelect = document.getElementById('ITskillId');
  let class1stBox = document.getElementById('class1stId');
	let class2ndSelect = document.getElementById('class2ndId')
	let careerSelect = document.getElementById('careerId')
  let hiddenCareer= document.getElementById('noSkillCareer');
  function SkillSelectChange2(value){
    if (form.skill.value === '1') {
      class1stId.replaceChildren();

      var class1stOption2 = document.createElement("option");
      class1stOption2.value = "その他";
      class1stOption2.textContent = "その他";
      class1stBox.appendChild(class1stOption2);}
  }
  function SkillSelectChange(value){
    class2ndSelect.replaceChildren();
    // 作成：丁錫圓
	  // 作成日：2406012
    codeDisplay.innerText="";
    form.code.value="";
    /* ここまで */
    if (form.skill.value === '1') {
      class1stId.replaceChildren();
      var class1stOption1 = document.createElement("option");
      class1stOption1.textContent = "選択してください。";
      class1stOption1.hidden = true;
      class1stBox.appendChild(class1stOption1);

      var class1stOption2 = document.createElement("option");
      class1stOption2.value = "その他";
      class1stOption2.textContent = "その他";
      class1stBox.appendChild(class1stOption2);

      var option = document.createElement("option");
      option.hidden = true;
      option.innerText = "選択してください。";
      class2ndSelect.appendChild(option);
      
      careerSelect.value = "0";
      careerId.readOnly =  true;

    } else {
      // 作成：丁錫圓
      // 作成日：2406012      
      codeDisplay.innerText="";
      form.code.value="";
      /* ここまで */
      class1stId.replaceChildren();
      var class1stOption1 = document.createElement("option");
      class1stOption1.textContent = "選択してください。";
      class1stOption1.hidden = true;
      class1stBox.appendChild(class1stOption1);

      var class1stOption2 = document.createElement("option");
      class1stOption2.value = "WEB";
      class1stOption2.textContent = "WEB";
      class1stBox.appendChild(class1stOption2);

      var class1stOption3 = document.createElement("option");
      class1stOption3.value = "IT基礎";
      class1stOption3.textContent = "IT基礎";
      class1stBox.appendChild(class1stOption3);

      var class1stOption4 = document.createElement("option");
      class1stOption4.value = "モバイル";
      class1stOption4.textContent = "モバイル";
      class1stBox.appendChild(class1stOption4);

      var class1stOption5 = document.createElement("option");
      class1stOption5.value = "サーバ";
      class1stOption5.textContent = "サーバ";
      class1stBox.appendChild(class1stOption5);

      var class1stOption6 = document.createElement("option");
      class1stOption6.value = "インフラ";
      class1stOption6.textContent = "インフラ";
      class1stBox.appendChild(class1stOption6);

      var class1stOption7 = document.createElement("option");
      class1stOption7.value = "その他";
      class1stOption7.textContent = "その他";
      class1stBox.appendChild(class1stOption7);

      var defaultOption = document.createElement("option");
      defaultOption.hidden = true;
      defaultOption.value = "";
      defaultOption.innerText = "選択してください。";
      class2ndSelect.appendChild(defaultOption);
      class2ndSelect.value = "";

      careerSelect.value = "";
      careerId.readOnly =  false;
    }
  }	

</script>

<script>
document.getElementById('educationId').addEventListener('change', function(event) {
    var selectedOption = event.target.value;

    if (selectedOption === "その他") {
		form.education.value = "";
        form.education.hidden = false;
    } else if(selectedOption != "その他") {
        form.education.hidden = true;
		// form.education.style.display = 'none';
    }
});


document.getElementById('majorId').addEventListener('change', function(event) {
    var selectedOption = event.target.value;

    if (selectedOption === "other") {
		    form.major.value = "";
        form.major.style.display = 'block';
        form.major.hidden = false;
    } else {
        form.major.hidden = true;
		    form.major.style.display = 'none';
    }
});

// document.getElementById('class1stId').addEventListener('change', function(event) {
// 	var selectedOption = event.target.value;

// 	if (selectedOption === "その他") {
// 		  form.class1st.value = "";
//       form.class1st.hidden = false;
//     } else if(selectedOption != "その他") {
//         form.class1st.hidden = true;
// 		// form.education.style.display = 'none';
//     }
// });
</script>

<script>
	function ChangeClass1st(element) {

class2ndSelect.replaceChildren();
switch (element.value) {
<?php foreach ($optionDatas["class2nd"] as $value => $class2nd): ?>
	case "<?php echo $optionDatas["class1st"][array_search($value, array_column($optionDatas["class1st"], "idx"))]["text"]; ?>":
		var option = document.createElement("option");
		option.hidden = true;
		option.innerText = "選択してください。";
		class2ndSelect.appendChild(option);

		<?php foreach ($class2nd as $data): ?>
			var option = document.createElement("option");
			option.value = <?php echo $data["idx"]; ?>;
			option.innerText = "<?php echo $data["text"]; ?>";
			class2ndSelect.appendChild(option);
		<?php endforeach; ?>
		break;
		<?php endforeach; ?>
		
	}
}
</script>
<!-- 漢字カナ入力時有効性検査 -->
<script>
function emailValidationCheck(input){
    var emailValidation =  /^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-Za-z0-9\-]+/;
    return emailValidation.test(input);
}

function isZenkaku(str) {
  for (var i = 0; i < str.length; i++) {
    var code = str.charCodeAt(i);
    if ((code >= 0x21 && code <= 0x7E) || 
        (code >= 0xAC00 && code <= 0xD7A3)) { 
      return str.charAt(i);
    }
  }
  return null;
}

function checkKana(input) {
  var katakanaRegex = /^[\u30A0-\u30FFー\s]+$/; 
  return katakanaRegex.test(input);
}
</script>

<script>
	function editConfirm(){
    let scheduleInput = document.getElementById('scheduleId').value;
    if (form.name.value == "" || isZenkaku(form.name.value)) {
          alert("お名前（漢字）を入力してください。");
          setTimeout("form.name.focus()",100);
          return false;
      }

      if (form.kana.value == "" || !checkKana(form.kana.value)) {
          alert("お名前（カナ）を入力してください。");
          setTimeout("form.kana.focus()",100);
          return false;
      }
        if (form.skill.value == "") {
            alert("ITスキル有無を入力してください。");
            setTimeout("form.skill.focus()",100);
            event.preventDefault();
            return false;
        }

        if (form.class1stId.value === "" || form.class1stId.value === "選択してください。") {
          alert("経験分野を入力してください。");
          setTimeout("form.class1stId.focus()",100);
          event.preventDefault();
          return false;
        }

        // if (form.class1stId.value == "その他" && form.otherclass1st.value=="") {
        //     alert("その他の場合の、記入してください");
        //     setTimeout("form.class1stId.focus()",100);
        //     return false;
        // }

        if (form.class2ndId.value == "" ||  form.class2ndId.value === "選択してください。") {
            alert("経験分野詳細を入力してください。");
            setTimeout("form.class2ndId.focus()",100);
            event.preventDefault();
            return false;
        }
        // console.log(class2nd.value);
        if ((isNaN(form.careerId.value))) {
            alert("IT経験年数を入力してください。");
            setTimeout("form.careerId.focus()",100);
            event.preventDefault();
            return false;
        }
        if (form.code.value == "") {
          alert("問題IDを入力してください。");
          setTimeout("form.code.focus()",100);
          event.preventDefault();
          return false;
        }
        if (form.scheduleId.value == "") {
          alert("診断予定日を入力してください。");
          setTimeout("form.scheduleId.focus()",100);
          event.preventDefault();
          return false;
        }
        var submitConfirm = confirm("診断予定日は " + scheduleInput + " です。\n依頼しますか？");
        if (!submitConfirm){
          event.preventDefault();
          return false;
        }
        else if(submitConfirm==true){
        form.submit();
        $('#submitLoading').modal('show');

        }
        // form.submit();

		
	}
  function saveConfirm(){
    if (form.name.value == "" || isZenkaku(form.name.value)) {
        alert("漢字を入力してください。");
        setTimeout("form.name.focus()",100);
        event.preventDefault();
        return false;
      }

      if (form.kana.value == "" || !checkKana(form.kana.value)) {
        alert("カナを入力してください。");
        setTimeout("form.kana.focus()",100);
        event.preventDefault();
        return false;
      }
      if (form.skill.value == "") {
        alert("ITスキル有無を入力してください。");
        setTimeout("form.skill.focus()",100);
        event.preventDefault();
        return false;
      }

        if (form.class1stId.value === "" || form.class1stId.value === "選択してください。") {
          alert("経験分野を入力してください。");
          setTimeout("form.class1stId.focus()",100);
          event.preventDefault();
          return false;
        }

        // if (form.class1stId.value == "その他" && form.otherclass1st.value=="") {
        //     alert("その他の場合の、記入してください");
        //     setTimeout("form.class1stId.focus()",100);
        //     return false;
        // }

        if (form.class2ndId.value == "" ||  form.class2ndId.value === "選択してください。") {
          alert("経験分野詳細を入力してください。");
          setTimeout("form.class2ndId.focus()",100);
          event.preventDefault();
          return false;
        }
        if ((isNaN(form.careerId.value))) {
          alert("IT経験年数を入力してください。");
          setTimeout("form.careerId.focus()",100);
          event.preventDefault();
          return false;
        }
        // if (form.code.value == "") {
        //     alert("問題IDを入力してください。");
        //     setTimeout("form.code.focus()",100);
        //     event.preventDefault();
        //     return false;
        // }
        var submitConfirm=confirm("保存しますか？");
          if (!submitConfirm){
            event.preventDefault();
            return false;
          }
        form.submit();
  }
	function randomPW(){
		const pwLength = 8;
		const pwEncoding = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

		let randomPw = "";

		for (let i = 0; i < pwLength; i++) {
			const randomIndex = Math.floor(Math.random() * pwEncoding.length);
			randomPw += pwEncoding.charAt(randomIndex);
		}
		form.password.value = randomPw;
	}
</script>

<script>
function diagnosisValidation(){
  // <!-- /* log
  //         作成：丁錫圓
  //         修正日：24/06/03
  //       */ -->
  //       <!-- 修正前： -->
  if (form.class1stId.value === "選択してください。") {
    alert("経験分野を入力してください。");
    setTimeout("form.class1stId.focus()",100);
    document.getElementById('diagnosisId').setAttribute('data-bs-toggle', 'false');
    return false;
  }
  if (form.class2ndId.value == "選択してください。") {
    alert("経験分野詳細を入力してください。");
    setTimeout("form.class2ndId.focus()",100);
    document.getElementById('diagnosisId').setAttribute('data-bs-toggle', 'false');
    return false;
  }
  var diagnosisIdModal = new bootstrap.Modal(document.getElementById('staticBackdrop'));
  diagnosisIdModal.show();
  diagnosisData();
}
// ここまで
function diagnosisData() {
  var skillElement = document.querySelector('select[name="skill"]');
  var levelElement = document.querySelector('select[name="level"]');
  var class2ndElement = document.querySelector('select[name="class2nd"]');
  var skillValue = skillElement.options[skillElement.selectedIndex].value;
  var levelValue = levelElement.options[levelElement.selectedIndex].value;
  var class2ndValue = class2ndElement.options[class2ndElement.selectedIndex].value;
 
  // const url = window.location.href;
  const postForm = new FormData();
  postForm.append("level", levelValue);
  postForm.append("class2nd", class2ndValue);
  const xhr = new XMLHttpRequest();
  xhr.open("POST", "../getdiagnosisdata", true);
  xhr.send(postForm);
  xhr.onload = () => {
    if (xhr.status == 200) {
      const result = xhr.responseText;
      console.log(result);

      try {
        let resultData = JSON.parse(result);
        if (result === "wrong") {
          updateTable("wrong");
          return;
        }
        updateTable(resultData);

        return false;
        } catch (e) {
          let alertString = ErrorString();
          alertString += "\nexception error in situation_edit diagnosisData";
          alertString += "\nexception message: " + e;
          alertString += "\nresponseText: " + result;
          alert(alertString);
          console.log(result);

          return false;
        }
    }
    else {
      let alertString = ErrorString();
      alertString += "\nxhr error in situation_edit diagnosisData";
      alertString += "\nerror code: " + xhr.status;
      alert(alertString);

      return false;
    }
}
}

    function updateTable(data) {
    const tableBody = document.querySelector(".table tbody");
    tableBody.innerHTML = ""; 
    if (data === "wrong" || data.length === 0) {
      const row = document.createElement("tr");
      const messageCell = document.createElement("td");
      messageCell.setAttribute("colspan", "4");
      messageCell.innerHTML = "該当する診断問題がありません。<br>経験分野、経験分野詳細、レベルを確認ください。";
      row.appendChild(messageCell);
      tableBody.appendChild(row);
    } else {
      data.forEach((item, index) => {
        const row = document.createElement("tr");

        const indexCell = document.createElement("td");
        indexCell.style="align-content:center;";
        indexCell.textContent = index + 1;
        row.appendChild(indexCell);

        const titleCell = document.createElement("td");
        titleCell.style="align-content:center;text-align:left;";
        titleCell.textContent = item.title; 
        row.appendChild(titleCell);

        const codeCell = document.createElement("td");
        codeCell.style="align-content:center";
        codeCell.textContent = item.code;
        row.appendChild(codeCell);

        const selectCell = document.createElement("td");
        selectCell.style="align-content:center";

        const button = document.createElement("button");
        button.type = "button";
        button.textContent = "選択";
        button.style="background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); padding: 5px 10px; color:white; border-radius:5px;";
        button.addEventListener("click", () => {
          selectCode(item.code,item.title);
          selectQuestionNum(item.question_num);
          document.querySelector('.btn-close').click();        
          // 作成：丁錫圓
          // 作成日：2406012  
          skillSelect.addEventListener("mousedown", disableEvent);
          class1stBox.addEventListener("mousedown", disableEvent);
          class2ndSelect.addEventListener("mousedown", disableEvent);
          careerSelect.addEventListener("mousedown", disableEvent);
          document.getElementById("levelId").addEventListener("mousedown", disableEvent);
          skillSelect.style.background = "#E2E2E2"
          class1stBox.style.background = "#E2E2E2"
          class2ndSelect.style.background = "#E2E2E2"
          careerSelect.style.background = "#E2E2E2"
          document.getElementById("levelId").style.background = "#E2E2E2"
          diagnosisId.hidden = true;

          const diagnosisCancel = document.createElement("button");
          diagnosisCancel.innerText = "取り消し";
          diagnosisCancel.id = "diagnosisCancel"; 
          diagnosisCancel.style="background:linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); padding: 0px 10px; color:white; border-radius:5px;"

          const parentElement = diagnosisId.parentNode; 
          parentElement.appendChild(diagnosisCancel);

          diagnosisCancel.addEventListener("click", () => {
            SkillSelectChange();
            skillSelect.removeEventListener("mousedown", disableEvent);
            class1stBox.removeEventListener("mousedown", disableEvent);
            class2ndSelect.removeEventListener("mousedown", disableEvent);
            careerSelect.removeEventListener("mousedown", disableEvent);
            document.getElementById("levelId").removeEventListener("mousedown", disableEvent);

            // Reset styles
            skillSelect.style.background = "";
            class1stBox.style.background = "";
            class2ndSelect.style.background = "";
            careerSelect.style.background = "";
            document.getElementById("levelId").style.background = "";
            diagnosisCancel.hidden = true;
            diagnosisId.hidden = false;

            event.preventDefault();
          });

          function disableEvent(event) {
            event.preventDefault(); 
          }
        /* ここまで */
        });
        
        selectCell.appendChild(button);
        row.appendChild(selectCell);

        tableBody.appendChild(row);
    });
}}

function selectCode(code, title) {
  const codeElement = document.querySelector('input[name="code"]');
  const displayElement = document.querySelector('#codeDisplay');
  codeElement.value =code ;
  displayElement.textContent = title+ " ("+code+")";
}
</script>

<!-- 診断書問題数's javascript -->
<script>
document.addEventListener('DOMContentLoaded', function() {
var questionNum = "<?php echo $question_num ?>";
if (!questionNum) {
    selectQuestionNum('0');
}
});

function selectQuestionNum(question_num) {
const questionNumElement = document.getElementById('question_numId');
if (questionNumElement) {
    questionNumElement.value = question_num;
}
}
</script>

<script>
  function ErrorString() {
  let alertString = "予期せぬエラーが発生しました。";
  alertString += "\n管理者にエラー内容をお知らせくださいますようお願いいたします。";
  alertString += "\n\nエラー内容：";
  return alertString;
  }
</script>