<?php
	$caseTexts = ["新卒", "中途"];
  $levelTexts = ["無級", "初級", "中級", "高級"];

	if (!isset($_SESSION)) { session_start(); }
	$url = explode("?", $_SERVER["REQUEST_URI"]);
	$route = $url[0];
	if (isset($url[1])) {
		$queryDatas = explode("&", $url[1]);
	}

  $selectTypeDatas = array(
    "status" => "ステータス",
    "case" => "応募区分",
    "education" => "最終学歴",
    "rank" => "等級結果",
  );
  $selectValueDatas = array(
    "status" => array(
      "apply" => "新規",
      "request" => "診断",
      "execute" => "終了",
      "unexecute" => "失格",
    ),
    "case" => ["新卒", "中途"],
    "education" => array(
      "high" => "高卒", 
      "voca" => "専門卒",
      "uni" => "大学卒",
      "grad" => "大学院卒",
    ),
    "rank" => array(
      "A" => "等級A",
      "B" => "等級B",
      "C" => "等級C",
      "D" => "等級D",
    ),
  );

  $isSearch = array(
    "select" => false,
  );
  $queryDatasN = array();
  if (isset($queryDatas)) {

    $queryDatasN = array();
    foreach ($queryDatas as $query) {
      $queryData = explode("=", $query);

      if ($queryData[0] == "select") {
        $queryDatasN["select"] = explode("-", $queryData[1]);
        $isSearch["select"] = true;
      }
      else {
        $queryDatasN[$queryData[0]] = $queryData[1];
        $isSearch[$queryData[0]] = true;
      }
    }
  }

	$firstNo = $this->noticelist->getTotalItemCount();
	$firstNo -= (($this->noticelist->getCurrentPageNumber() - 1) * $this->noticelist->getitemCountPerPage());

	$isPick = false;
	if (isset($searchDatas["pick"])) {
		$isPick = true;
	}
?>
<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: space-between ;
	}

	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		
		font-size: 15px;
		font-weight: 400;
	}

	.pagination-place, .button-place {
		margin-top: 10px;
		display: flex;
		justify-content: center;
	}
	.button-place { justify-content: space-between; }
</style>

<content class="header">
	<div class="title">ITスキル診断状況管理</div>
</content>

<content class="main">
	<div style="width: 100%; display:grid; align-items:end; text-align: center;">
		<div class="info-num">
			<div style="display: flex;">
        <style type="text/css">
          div.count {
            display: flex;
            justify-content: space-between;
          }
          div.count span.num {
            margin-right: 10px;

            line-height: 40px;
            font-size: 40px;
          }
        </style>

        <div class="count"><p>新規申込</p><p><span class="num"><?php echo $totalApply; ?></span>名</p></div>
        <div class="count" style="margin-left:50px;"><p>診断中</p><p><span class="num"><?php echo $totalRequest; ?></span>名</p></div>
        <div class="count" style="margin-left:50px;"><p>診断完了</p><p><span class="num"><?php echo $countOver; ?></span>名</p></div>
      </div>
      <div class="count"><p>診断状況</p><p><span class="num"><?php echo $totalData; ?></span>名</p></div>
    </div>

		<div style="display: flex; justify-content: right;padding-top: 24px;">
      <input type="text" class="form-control form-control-sm" id="search-name" style="width: 150px; margin-right: 8px;" placeholder="診断者名" value="<?php echo (isset($searchDatas["name"])) ? $searchDatas["name"] : ""; ?>">
      <input type="date" class="form-control form-control-sm" id="search-date" style="width: 150px; margin-right: 8px;" value="<?php echo (isset($searchDatas["date"])) ? date("Y-m-d", strtotime($searchDatas["date"])) : ""; ?>" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="診断予定日" data-bs-html="false">
			<button class="emegra search confirm" style="margin-right: 8px;" onclick="Search()">検索</button>
      <select class="form-select form-select-sm" id="select-select_type" style="width: 150px; margin-right: 8px;" onchange="ChangeValue(this)">
        <option value="">全て</option>

        <?php foreach ($selectTypeDatas as $value => $text): ?>
          <option value="<?= $value; ?>"<?php echo ($isSearch["select"] && $queryDatasN["select"][0] == $value) ? " selected" : ""; ?>><?= $text; ?></option>
        <?php endforeach; ?>
      </select>

      <select class="form-select form-select-sm" id="select-select_value" style="width: 150px;" onchange="Selecting(this)">
        <option hidden>選択</option>

        <?php if ($isSearch["select"]): ?>
          <?php foreach ($selectValueDatas[$queryDatasN["select"][0]] as $value => $text): ?>
            <option value="<?= $value; ?>"<?php echo ($queryDatasN["select"][1] == $value) ? " selected" : ""; ?>><?= $text; ?></option>
          <?php endforeach; ?>
        <?php endif; ?>
      </select>



      <script type="text/javascript">
        const selectType = document.getElementById("select-select_type");
        const selectValue = document.getElementById("select-select_value");

        function ChangeValue(element) {
          if (element.value == "") { Selecting(element); return false; }

          selectValue.replaceChildren();

          var option = document.createElement("option");
          option.hidden = true;
          option.innerText = "選択";
          selectValue.appendChild(option);
          
          switch (element.value) {
            <?php foreach ($selectValueDatas as $type => $datas): ?>
              case "<?= $type; ?>":
                <?php foreach ($datas as $value => $text): ?>
                  var option = document.createElement("option");
                  option.value = "<?= $value; ?>";
                  option.innerText = "<?= $text; ?>";
                  selectValue.appendChild(option);
                <?php endforeach; ?>
                break;
            <?php endforeach; ?>
          }
        }

        function Selecting(element) {
          <?php
            $newQuery = "?";

            if (!empty($queryDatasN)) {
              foreach ($queryDatasN as $key => $data) {
                if ($key == "select") { continue; }

                $newQuery .= $key . "=" . $data . "&";
              }
            }

            $url = $route . $newQuery;
          ?>

          let url = "<?= $url; ?>";

          if (element.value != "") { url += "select=" + selectType.value + "-" + element.value + "&"; }
          url = url.slice(0, -1);

          self.window.location = url;
        }
      </script>
		</div>
	</div>

  <div class="emegra-table">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th rowspan="2">No</th>
          <th rowspan="2">ステータス</th>
          <th colspan="5">IT診断者情報</th>
          <th colspan="4">診断問題詳細</th>
          <th colspan="5">診断状況</th>
          <th rowspan="2"><input id="checkAll" type="checkbox" onclick="Checking(this);" style="cursor: pointer;"></th>
        </tr>
        
        <tr>
          <th>申込日</th>
          <th>応募区分</th>
          <th>名前</th>
          <th>学歴</th>
          <th>ITスキル有無</th>

          <th>大分類</th>
          <th>小分類</th>
          <th>レベル</th>
          <th>診断問題ID</th>

          <th>診断依頼</th>
          <th>診断予定日</th>
          <th>診断時間</th>
          <th>得点</th>
          <th>結果通知</th>
        </tr>
      </thead>
      <tbody id="table-body-list">
        <?php if (empty($recordDatas)): ?>
          <td colspan="17">診断者情報がありません。</td>
        <?php else: ?>
          <?php foreach ($recordDatas as $index => $data): ?>
            <tr <?php echo ($data["diagnosis_code"] == null || $data["diagnosis_code"] == "") ? "style='background: lightcyan;'" : ""; ?>>
              <td><?php echo $firstNo - $index; ?></td>
              <td><?php echo $data["status"]; ?></td>

              <td><?php echo date("y.m.d", strtotime($data["apply_date"])); ?></td>
              <td><?php echo $caseTexts[$data["case"]]; ?></td>
              <td><a onclick="self.location.href='./<?php echo ($data['diagnosis_date'] == null) ? 'edit' : 'detail'; ?>/<?php echo $data['idx']; ?>';"><?php echo $data["name"]; ?></a></td>
              <td><?php echo $data["education"]; ?></td>
              <td><?php echo ($data["skill"] == 1) ? "無" : "有"; ?></td>

              <td><?php echo (isset($data["class1st"])) ? $data["class1st"] : "未設定"; ?></td>
              <td><?php echo (isset($data["class2nd"])) ? $optionDatas[$data["class2nd"]] : "未設定"; ?></td>
              <td><?php echo (isset($data["level"])) ? $levelTexts[$data["level"]] : "未設定"; ?></td>
              <td><?php echo (isset($data["diagnosis_code"])) ? $data["diagnosis_code"] : "未設定"; ?></td>

              <td><?php echo (isset($data["request_date"])) ? "依頼" : "未依頼"; ?></td>
              <?php
                $isExpire = false;
                if (isset($data["date_schedule"])) {
                  if ((strtotime($data["date_schedule"]) < time()) && is_null($data["rank"])) {
                    $isExpire = true;
                  }
                }
              ?>
              <!--
                作成：朴昰成
                修正：朴昰成
                修正日：24/06/19
              -->

              <!-- 修正前： <?php /* />
              <td style="<?php echo ($isExpire) ? "color: red;" : "" ?>"><?php echo (isset($data["date_schedule"])) ?  date("y.m.d H:i:m", strtotime($data["date_schedule"])) : "未設定"; ?></td>
              <?php */ ?> -->

              <!-- 修正後： -->
              <td style="<?php echo ($isExpire) ? "color: red;" : "" ?>"><?php echo (isset($data["date_schedule"])) ?  date("y.m.d H:i:s", strtotime($data["date_schedule"])) : "未設定"; ?></td>
              <!-- ここまで -->
              <?php if (isset($data["rank"])): ?>
                <td><?php echo (isset($data["solve_time"])) ? $data["solve_time"] : "0"; ?>分</td>
                <td><?php echo ($data["rank"] != "F") ? $data["get_point"] . "/100" : "失格"; ?></td>
              <?php else: ?>
                <td>未受験</td>
                <td>未受験</td>
              <?php endif; ?>
              <td><?php echo (isset($data["date_mail"])) ? "通知" : "未通知"; ?></td>

              <?php
                $isAbleCheck = false;
                if ($data["diagnosis_code"] != "" && $data["request_date"] == null) { $isAbleCheck = true; }
                if ($data["rank"] != null && $data["date_mail"] == null) { $isAbleCheck = true; }
              ?>
              <td><input name="checkIdx" type="checkbox" value="<?php echo $data["idx"]; ?>" onclick="Checking(this);" style="cursor: pointer;"<?php echo ($isAbleCheck) ? "" : " disabled"; ?>></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>

<div class="pagination-place" style="margin-top: 10px;">
  <?php echo $this->paginationControl($this->noticelist, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
</div>

<div class="button-place" style="margin-top: 10px; justify-content:space-between;">
	<div></div>
	
  <div>
    <button class="emegra" style="margin-right:10px;" onclick="SendMail(this)">結果送信</button>
    <button class="emegra" style="width:150px; margin-right:10px;" onclick="Request(this)">ITスキル診断依頼</button>
		<button class="emegra" onclick="self.window.location='./input'">新規登録</button>
		</div>	
	</div>
</content>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript">
	const searchName = document.getElementById("search-name");
	const searchAlign = document.getElementById("search-align");
	const searchDate = document.getElementById("search-date");
	const check_all = document.getElementById("checkAll");
	const check_idxs = document.getElementsByName("checkIdx");
  const tableBodyList = document.getElementById("table-body-list");
  const buttonElements = document.getElementsByTagName("button");

	function Checking(element) {
		if (element == check_all) {
			if (element.checked) {
				check_idxs.forEach(e => {
					if (!e.disabled) { e.checked = true; }
				});
			}
			else {
				check_idxs.forEach(e => { e.checked = false; });
			}
		}

		if (element != check_all) {
			let allChecked = true;
			for (let i = 0; i < check_idxs.length; i++) {
				if (check_idxs[i].checked == false) {
					if (check_idxs[i].disabled == true) { continue; }
					allChecked = false;
					break;
				}
			}

			check_all.checked = allChecked;
		}
	}

	function Select(value) {
		<?php
			$newQuery = "?";

			if (!empty($queryDatas)) {
				foreach ($queryDatas as $data) {
					if (explode("=", $data)[0] == "page") { continue; }
					if (explode("=", $data)[0] == "pick") { continue; }

					$newQuery .= $data . "&";
				}
			}

			$url = $route . $newQuery;
		?>

		let url = "<?php echo $url; ?>";

		if (value == "") { url = url.slice(0, -1); }
		else { url += "pick=" + value; }
		self.window.location = url;
	}
	function Search(value) {
		<?php
			$newQuery = "?";

			if (!empty($queryDatas)) {
				foreach ($queryDatas as $data) {
					if (explode("=", $data)[0] == "page") { continue; }
					if (explode("=", $data)[0] == "name") { continue; }
          if (explode("=", $data)[0] == "date") { continue; }

					$newQuery .= $data . "&";
				}
			}

			$url = $route . $newQuery;
		?>

		let url = "<?php echo $url; ?>";

    if (searchName.value.trim() != "") { url += "name=" + searchName.value + "&"; }
    if (searchDate.value != "") { url += "date=" + searchDate.value + "&"; }
    url = url.slice(0, -1);

    self.window.location = url;
	}

	function Request(button) {
		idxs = [];
		isChecked = false;
    isExpired = [];
		for (let i = 0; i < check_idxs.length; i++) {
			if (check_idxs[i].checked == true) {
        if (check_idxs[i].parentNode.parentNode.children[12].style.color == "red") {
          isExpired.push(i);
          break;
        }

				isChecked = true;
				idxs.push(check_idxs[i].value);
			}
		}

    if (isExpired.length != 0) {
      let alertString = "依頼予定日を確認してください。\n";

      for (let i = isExpired.length - 1; i >= 0 ; i--) {
        alertString += "\n" + check_idxs[isExpired[i]].parentNode.parentNode.children[0].innerText + "．" + check_idxs[isExpired[i]].parentNode.parentNode.children[4].innerText;
      }
      alert(alertString);
      return false;
    }

		if (!isChecked) {
      alert("依頼する診断者情報を選択してください。");
			return false;
		}

		idxs = idxs.join(",");

		if (confirm("依頼しますか？") === false) { return false; }

    ChangeButton(button, "送信中...");

    formDatas = [{"key":"idxs", "value":idxs}];
    const xhr = SendXhr("./request", formDatas);
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
        console.log(result);

				if (result === "success") {
					alert("依頼しました。");
					location.reload(true);
				}
				else {
          try {
            recordDatas = JSON.parse(result);
          }
          catch (e) {
            let alertString = ErrorString();
            alertString += "\nexception error in situation_list Request";
            alertString += "\nexception message: " + e;
            alertString += "\nresponseText: " + result;
            alert(alertString);

            ReturnButton(button, "ITスキル診断依頼");
            return false;
          }

          $alertString = "依頼ができない診断者がいます。";
          $alertString += "\n\n依頼ができない診断者";
          for (let i = 0; i < recordDatas.length; i++) {
            for (let j = 0; j < tableBodyList.children.length; j++) {
              if (recordDatas[i]["idx"] == tableBodyList.children[j].lastElementChild.children[0].value) {
                applicantNo = tableBodyList.children[j].firstElementChild.innerText;
                applicantName = tableBodyList.children[j].children[4].innerText;
                $alertString += "\n" + applicantNo + "．" + applicantName;
                break;
              }
            }
          }
          alert($alertString);
          ReturnButton(button, "ITスキル診断依頼");
          return false;
				}
			}
      else {
        let alertString = ErrorString();
        alertString += "\nxhr error in situation_list Request";
        alertString += "\nerror code: " + xhr.status;
        alert(alertString);

        ReturnButton(button, "ITスキル診断依頼");
        return false;
      }
		}
	}

  function SendMail(button) {
		idxs = [];
		isChecked = false;
		for (let i = 0; i < check_idxs.length; i++) {
			if (check_idxs[i].checked == true) {
				isChecked = true;

				idxs.push(check_idxs[i].value);
			}
		}

		if (!isChecked) {
      alert("送信する診断者情報を選択してください。");
			return false;
		}
		idxs = idxs.join(",");

    if (confirm("結果を送信しますか？") === false) { return false; }

    ChangeButton(button, "送信中...");

    formDatas = [{"key":"idxs", "value":idxs}];
    const xhr = SendXhr("./mail", formDatas);
    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        console.log(result);

        if (result === "success") {
          alert("送信しました。");
          location.reload(true);
        }
        else {
          try {
            let recordDatas = JSON.parse(result);
          }
          catch (e) {
            let alertString = ErrorString();
            alertString += "\nexception error in situation_list SendMail";
            alertString += "\nexception message: " + e;
            alertString += "\nresponseText: " + result;
            alert(alertString);

            ReturnButton(button, "結果送信");
            return false;
          }

          let alertString = "送信できない診断者がいます。\n\n";
          alertString += "送信できない診断者";
          for (let i = 0; i < recordDatas.length; i++) {
            let applicantNo = "";
            for (let j = 0; j < tableBodyList.children.length; j++) {
              if (recordDatas[i]["idx"] = tableBodyList.children[j].children[16].children[0].value) {
                applicantNo = tableBodyList.children[j].children[0].innerText;
              }
            }
            $alertString += "\n" + applicantNo + "．" + recordDatas[i]["name"];
          }
          alert($alertString);

          ReturnButton(button, "結果送信");
          return false;
        }
      }
      else {
        let alertString = ErrorString();
        alertString += "\nxhr error in situation_list SendMail";
        alertString += "\nerror code: " + xhr.status;
        alert(alertString);

        ReturnButton(button, "結果送信");
        return false;
      }
    }
  }



  function ErrorString() {
    let alertString = "予期せぬエラーが発生しました。";
    alertString += "\n管理者にエラー内容をお知らせくださいますようお願いいたします。";
    alertString += "\n\nエラー内容：";
    return alertString;
  }

  function ChangeButton(button, text) {
    button.replaceChildren();

    var span = document.createElement("span");
    span.classList.add("spinner-border");
    span.classList.add("spinner-border-sm");
    span.ariaHidden = "true";
    button.appendChild(span);

    var span = document.createElement("span");
    span.role = "status";
    span.innerText = text;
    button.appendChild(span);
    
    for (let i = 0; i < buttonElements.length; i++) {
      buttonElements[i].disabled = true;
    }
  }

  function ReturnButton(button, text) {
    button.replaceChildren();
    button.innerText = text;
    
    for (let i = 0; i < buttonElements.length; i++) {
      buttonElements[i].disabled = false;
    }
  }

  function SendXhr(route, datas = new Array()) {
    const postForm = new FormData();
    for (let i = 0; i < datas.length; i++) {
      postForm.append(datas[i]["key"], datas[i]["value"]);
    }

    const xhr = new XMLHttpRequest();
    xhr.open("POST", route, true);
    xhr.send(postForm);
    return xhr;
  }
</script>
