<?php
	$caseTexts = ["新卒", "中途"];
	$levelTexts = array("0級", "初級", "中級", "高級");

	$url = explode("?", $_SERVER["REQUEST_URI"])[0];
	if (!isset($_SESSION)) { session_start(); }
?>
<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: space-between ;
	}

	table.emegra tr {
		min-width: 1200px;
		grid-template-columns: 30px repeat(13, 1fr) 30px;
	}
	table.emegra tr.index {
		padding-top: 8px;
		padding-bottom: 4px;
		grid-template-areas:
		"no  status  applicant_info applicant_info        applicant_info applicant_info applicant_info  applicant_info  dianosis_detail dianosis_detail dianosis_detail  dianosis_status  dianosis_status  dianosis_status check "
		"no  status  applicant_date application_category  name           education      develop         career          request_date    level           test             execute_date     get_point        grade           check";
	}

	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		
		font-size: 15px;
		font-weight: 400;
	}

	table.emegra tr.index > th {
		padding: 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.pagination-place, .button-place {
		margin-top: 10px;
		display: flex;
		justify-content: center;
	}
	.button-place { justify-content: space-between; }
</style>

<content class="header">
	<div class="title">ITスキル診断状況管理</div>
</content>

<content class="main">
	<div style="width: 100%; display:grid; align-items:end; text-align: center;">
		<div class="info-num">
			<div style="display: flex;">
				<div class="count">新規申込<div class="num"><?php echo $totalApply; ?></div>名</div>
				<div class="count" style="margin-left:50px;">診断中<div class="num"><?php echo $totalRequest; ?></div>名</div>
			</div>
			<div class="count">診断状況<div class="num"><?php echo $totalData; ?></div>名</div>
		</div>

		<div style="display: flex; justify-content: right;padding-top: 24px;">
			<input class="form-control" type="text" id="search-name" style="width:15%; height:30px;margin-right:10px;" placeholder="診断者名" value="<?php echo (isset($searchDatas["name"])) ? $searchDatas["name"] : ""; ?>">
			<div id="div-search" style="width: 150px; margin-right: 8px;">
			<select class="form-select form-select-sm" id="search-align" style="width: 150px; margin-right: 8px;">
			<!-- <?php /* ?>
					<option value="status-DESC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "status-DESC") ? " selected" : ""; ?>>ステータス（昇順）</option>
					<option value="status-ASC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "status-ASC") ? " selected" : ""; ?>>ステータス（降順）</option>
					<?php */ ?> -->
					<option value="case-DESC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "case-DESC") ? " selected" : ""; ?>>応募区分（昇順）</option>
					<option value="case-ASC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "case-ASC") ? " selected" : ""; ?>>応募区分（降順）</option>
					<option value="education-DESC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "education-DESC") ? " selected" : ""; ?>>最終学歴（昇順）</option>
					<option value="education-ASC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "education-ASC") ? " selected" : ""; ?>>最終学歴（降順）</option>
					<option value="class1st-DESC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "class1st-DESC") ? " selected" : ""; ?>>経験分野（昇順）</option>
					<option value="class1st-ASC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "class1st-ASC") ? " selected" : ""; ?>>経験分野（降順）</option>
					<option value="rank-DESC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "rank-DESC") ? " selected" : ""; ?>>試験結果（昇順）</option>
					<option value="rank-ASC"<?php echo (isset($searchDatas["align"]) && $searchDatas["align"] == "rank-ASC") ? " selected" : ""; ?>>試験結果（降順）</option>
				</select>
			</div>
			<button class="emegra search confirm" onclick="Search()">検索</button>
		</div>
	</div>

	<?php if (false): ?>
		<div class="table-empty" style="margin-top: 16px;">
			データがありません。
		</div>
		
		<!-- 건드릴 부분 -->
	<?php else: ?>
		<table class="emegra" style="margin-top: 8px;">
			<thead>
				<tr class="index">
					<th style="grid-area: no">No</th>
					<th style="grid-area: status">ステータス</th>
					<th style="grid-area: applicant_info">IT診断者情報</th>
					<th style="grid-area: dianosis_detail ">診断問項詳細</th>
					<th style="grid-area: dianosis_status  ">診断状況</th>
					<th style="grid-area: check;"><input id="checkAll" type="checkbox" onclick="Checking(this);" style="cursor: pointer;"></th>

					<th style="grid-area: applicant_date">申込日</th>
					<th style="grid-area: application_category">応募区分</th>
					<th style="grid-area: name">名前</th>
					<th style="grid-area: education">学歴</th>
					<th style="grid-area: develop">経験分野</th>
					<th style="grid-area: career">経験年数</th>

					<th style="grid-area: request_date">診断依頼</th>
					<th style="grid-area: level">レベル</th>
					<th style="grid-area: test">診断問題</th>

					<th style="grid-area: execute_date">試験日</th>
					<th style="grid-area: get_point">得点</th>
					<th style="grid-area: grade ">等級</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($recordDatas as $data): ?>
					<tr <?php echo ($data["diagnosis_code"] == null) ? "style='background: skyblue;'" : ""; ?>>
						<td><?php echo $data["num"]; ?></td>
						<td><?php echo $data["status"]; ?></td>
						<td><?php echo date("y.m.d", strtotime($data["apply_date"])); ?></td>
						<td><?php echo $caseTexts[$data["case"]]; ?></td>
						<td class="link" onclick="self.location.href='./<?php echo ($data['diagnosis_date'] == null) ? 'edit' : 'detail'; ?>/<?php echo $data['idx']; ?>';" style="text-align: center; color: blue"><?php echo $data["name"]; ?></td>
						<td><?php echo $data["education"]; ?></td>
						<td><?php echo ($data["major"] != null) ? $data["major"] : "無"; ?></td>
						<td><?php echo ($data["career"] != null) ? $data["career"] . "年" : "無"; ?></td>
						<td><?php echo ($data["request_date"] != null) ? date("y.m.d", strtotime($data["request_date"])) : "未依頼"; ?></td>
						<td><?php echo (isset($data["level"])) ? $levelTexts[$data["level"]] : "未設定"; ?></td>
						<td><?php echo ($data["diagnosis_code"] != null) ? $data["diagnosis_code"] : "未設定"; ?></td>
						<?php if ($data["execute_date"] != null): ?>
							<td><?php echo date("y.m.d", strtotime($data["execute_date"])); ?></td>
							<td><?php echo $data["get_point"]; ?>/100</td>
							<td><?php echo $data["rank"]; ?></td>
						<?php else: ?>
							<td>未実行</td>
							<td>未実行</td>
							<td>未実行</td>
						<?php endif; ?>
						<td><input name="checkIdx" type="checkbox" value="<?php echo $data["idx"]; ?>" onclick="Checking(this);" style="cursor: pointer;"<?php echo ($data["request_date"] == null) ? "" : " disabled"; ?>></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php endif; ?>
<!-- 여기가끼 -->

<div class="pagination-place" style="margin-top: 10px;">
	<?php echo $this->paginationControl($this->noticelist, "sliding", array("pagination2", "Notice"), array("url" => "")); ?>
</div>

<div class="button-place" style="margin-top: 10px; justify-content:space-between;">
	<div></div>
	
	<div>
		<button class="emegra" style="width:150px; margin-right:10px;" onclick="Request()">ITスキル診断依頼</button>
		<button class="emegra" onclick="self.window.location='../situ/input'">新規登録</button>
		</div>	
	</div>
</content>

<script type="text/javascript">
	const seachName = document.getElementById("search-name");
	const seachAlign = document.getElementById("search-align");
	const check_all = document.getElementById("checkAll");
	const check_idxs = document.getElementsByName("checkIdx");

	function Checking(element) {
		if (element == check_all) {
			if (element.checked) {
				check_idxs.forEach(e => {
					if (!e.disabled) { e.checked = true; }
				});
			}
			else {
				check_idxs.forEach(e => { e.checked = false; });
			}
		}

		if (element != check_all) {
			check_all.checked = false;

			check_idxs.forEach(e => {
				if (e.checked) { check_all.checked = true; return true; }
			});
		}
	}

	function Search(value) {
		let url = "<?= $url ?>?align=" + seachAlign.value;
		if (seachName.value.trim() != "") {
			url += "&name=" + seachName.value;
		}
		self.window.location = url;
	}

	function Request() {
		idxs = [];
		isChecked = false;
		for (let i = 0; i < check_idxs.length; i++) {
			if (check_idxs[i].checked == true) {
				isChecked = true;

				idxs.push(check_idxs[i].value);
			}
		}

		if (!isChecked) {
			alert("依頼するデータを選んでください。");
			return false;
		}
		idxs = idxs.join(",");

		if (confirm("依頼しますか？") === false) { return false; }

		const postForm = new FormData();
		postForm.append("idxs", idxs);
		const xhr = new XMLHttpRequest();
		xhr.open("POST", "./request", true);
		xhr.send(postForm);
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;

				if (result === "success") {
					alert("依頼しました。");
					location.reload(true);
				}
				else {
					alert("error");
					console.log(result);
				}
			}
		}
	}
</script>
