<?php
	$caseTexts = ["新卒", "中途"];
	$genderTexts = ["男", "女"];
	$skillTexts = ["有", "無"];
  $levelTexts = ["無級", "初級", "中級", "高級"];
  $languageTexts = ["日本語", "韓国語"];

	$isRequest = false;
	$isExecute = false;
	if ($recordData["request_date"] != null) {
		$isRequest = true;
    /*
      作成：朴昰成
      修正：朴昰成
      修正日：24/06/03
    */

    /* 修正前：
      if ($recordData["execute_date"] != null) {
        $isExecute = true;
      }
    */

    /* 修正後： */
    if (isset($recordData["rank"])) {
      $isExecute = true;
    }
    /* ここまで */
	}
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">ITスキル診断状況管理</h1>

<style type="text/css">
	option { color: black; }
	input::placeholder { font-style: italic; }
</style>

<div class="emegra card">
	<div class="card-header">ITスキル診断者情報</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.info { grid-template-columns:  repeat(2, 170px 1fr) }
		</style>
		<dl class="emegra info">			<dt>ID</dt>
			<dd><?php echo $recordData["email"]; ?></dd>

			<dt>応募区分</dt>
			<dd><?php echo $caseTexts[$recordData["case"]]; ?></dd>

			<dt>パスワード</dt>
			<dd><?php echo $recordData["password"]; ?></dd>

			<dt>お名前（漢字）</dt>
			<dd><?php echo $recordData["name"]; ?></dd>

			<dt>申込日</dt>
			<dd><?php echo date("y.m.d", strtotime($recordData["apply_date"])); ?></dd>

			<dt>お名前（カナ）</dt>
			<dd><?php echo $recordData["kana"]; ?></dd>

			<dt>性別</dt>
			<dd><?php echo ($recordData["gender"] == null) ? "未設定" : $genderTexts[$recordData["gender"]]; ?></dd>

			<dt>学歴</dt>
			<dd><?php echo $recordData["education"]; ?></dd>

			<dt>IT関連資格</dt>
			<dd><?php echo ($recordData["certificates"] == null) ? "未設定" : $recordData["certificates"]; ?></dd>

			<dt>生年月日</dt>
			<dd><?php echo date("Y.m.d", strtotime($recordData["birth"])); ?></dd>

			<dt>専攻</dt>
			<dd><?php echo ($recordData["major"] == null) ? "未設定" : $recordData["major"]; ?></dd>

			<dt>その他</dt>
			<dd><?php echo $recordData["other"]; ?></dd>
		</dl>
	</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">ITスキル診断問項詳細</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.setting { grid-template-columns: repeat(2, 170px 1fr); }
		</style>
		<dl class="emegra setting">
      <!-- debug
        作成：朴昰成
        修正：朴昰成
        修正日：24/06/05
      -->

      <!-- 修正前： <?php /* ?>
        <dt>ITスキル有無</dt>
        <dd><?php echo $skillTexts[$recordData["skill"]]; ?></dd>

        <dt>経験分野</dt>
        <dd><?php echo $recordData["class1st"]; ?></dd>

        <dt>IT経験年数</dt>
        <dd><?php echo ($recordData["career"] != null) ? $recordData["career"] . "年" : "無"; ?></dd>

        <dt>問題種別</dt>
        <dd><?php echo $optionDatas[$recordData["class2nd"]]; ?></dd>

        <dt>診断問項ID</dt>
        <dd><?php echo $recordData["diagnosis_code"]; ?></dd>

        <dt>レベル</dt>
        <dd><?php echo $levelTexts[$recordData["level"]]; ?></dd>

        <dt>問項数別</dt>
        <dd><?php echo $recordData["question_num"]; ?>問項</dd>

        <dt>診断方法</dt>
        <dd><?php echo $recordData["method"]; ?></dd>
    
        <dt>診断依頼</dt>
        <dd><?php echo ($recordData["request_date"] != null) ? date("y.m.d", strtotime($recordData["request_date"])) : "未依頼"; ?></dd>

        <dt>言語</dt>
        <dd><?php echo ($recordData["language"] == null) ? "未設定" : $languageTexts[$recordData["language"]]; ?></dd>
      <?php */ ?> -->

      <!-- 修正後： -->
      <dt>ITスキル有無</dt>
      <dd><?php echo $skillTexts[$recordData["skill"]]; ?></dd>

      <dt>IT経験年数</dt>
      <dd><?php echo ($recordData["career"] != null) ? $recordData["career"] . "年" : "無"; ?></dd>

      <dt>経験分野</dt>
      <dd><?php echo $recordData["class1st"]; ?></dd>

      <dt>問題種別</dt>
      <dd><?php echo $optionDatas[$recordData["class2nd"]]; ?></dd>

      <dt>診断問項ID</dt>
      <dd><?php echo $recordData["diagnosis_code"]; ?></dd>

      <dt>レベル</dt>
      <dd><?php echo $levelTexts[$recordData["level"]]; ?></dd>

      <dt>問項数別</dt>
      <dd><?php echo $recordData["question_num"]; ?>問項</dd>

      <dt>言語</dt>
      <dd><?php echo (is_null($recordData["language"])) ? "未設定" : $languageTexts[$recordData["language"]]; ?></dd>

      <dt>診断方法</dt>
      <dd><?php echo $recordData["method"]; ?></dd>

      <dt>メール転送</dt>
      <dd><?php echo (is_null($recordData["mail_delay"])) ? "手動" : "自動"; ?></dd>
  
      <dt>診断予定日時</dt>
      <dd><?php echo (is_null($recordData["date_schedule"])) ? "未依頼" : date("y.m.d H:i", strtotime($recordData["date_schedule"])); ?></dd>
  
      <dt>診断依頼</dt>
      <dd><?php echo (is_null($recordData["request_date"])) ? "未依頼" : date("y.m.d", strtotime($recordData["request_date"])); ?></dd>
      <!-- ここまで -->
		</dl>
	</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">ITスキル診断状況</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 150px 1fr); }
		</style>
		<dl class="emegra detail">
			<?php if ($isExecute): ?>
				<dt>診断実施日</dt>
				<dd><?php echo date("y.m.d", strtotime($recordData["execute_date"])); ?></dd>

        <!-- move from 217
          作成：朴昰成
          作成日：24/06/05
        -->
        <dt>結果送信日</dt>
        <dd><?php echo ($recordData["date_mail"] != null) ? date("y.m.d", strtotime($recordData["date_mail"])) : "未送信"; ?></dd>

        <!-- ここまで -->
				<dt>得点</dt>
				<dd><?php echo $recordData["get_point"]; ?></dd>

				<dt>評価等級</dt>
				<dd><?php echo $recordData["rank"]; ?></dd>

				<dt>診断者のコメント</dt>
        <!-- debug
          作成：朴昰成
          修正：朴昰成
          修正日：24/06/05
        -->

        <!-- 修正前： <?php /* ?>
          <dd><?php echo $recordData["comment"]; ?></dd>
        <?php */ ?> -->

        <!-- 修正後： -->
        <dd><?php echo $recordData["diagnosis_comment"]; ?></dd>
        <!-- ここまで -->

				<dt>備考</dt>
				<dd><?php echo $recordData["comment"]; ?></dd>
        <!-- move to 186
          作成：朴昰成
          削除：朴昰成
          削除日：24/06/05
        
        削除前： <?php /* ?>

          <dt>結果送信日</dt>
          <dd><?php echo ($recordData["date_mail"] != null) ? date("y.m.d", strtotime($recordData["date_mail"])) : "未送信"; ?></dd>
        <?php */ ?> -->
			<?php else: ?>
				<div style="grid-column: 1 / 6; display: flex; align-items: center; justify-content: center;">未受験</div>
			<?php endif; ?>
		</dl>
	</div>
</div>

<div class="btn-place" style="margin-top: 32px;">
  <button class="emegra cancel" onclick="history.back();">戻る</button>
	<?php if (!$isRequest): ?>
    <button class="emegra" style="background:orange;" onclick="self.location.href='../edit/<?php echo $recordData['idx']	?>';">修正</button>
    <!--
      作成：朴昰成
      修正：朴昰成
      修正前：24/06/07
    -->

    <!-- 修正前： <?php /* ?>
      <button class="emegra" style="width:150px;" onclick="Request();">ITスキル診断依頼</button>
    <?php */ ?> -->

    <!-- 修正前： -->
    <button class="emegra" style="width:150px;" onclick="Request(this);">ITスキル診断依頼</button>
    <!-- ここまで -->
  <?php else: ?>
    <?php if ($recordData["rank"] != null && $recordData["date_mail"] == null): ?>
      <!--
        作成：朴昰成
        修正：朴昰成
        修正前：24/06/07
      -->

      <!-- 修正前： <?php /* ?>
        <button class="emegra" onclick="SendMail();">メール送信</button>
      <?php */ ?> -->

      <!-- 修正前： -->
      <button class="emegra" onclick="SendMail(this);">結果送信</button>
      <!-- ここまで -->
    <?php endif; ?>
	<?php endif; ?>
</div>

<script type="text/javascript">
	const idx = <?php echo $recordData["idx"]; ?>

  /*
    作成：朴昰成
    修正：朴昰成
    修正日：24/06/07
  */

  /* 修正前：
    function Request() {
  */

  /* 修正後： */
  function Request(button) {
  /* ここまで */
		if (confirm("依頼しますか？") === false) { return false; }

    /*
      作成：朴昰成
      修正：朴昰成
      修正日：24/06/03
    */

    /* 修正前：
      if (confirm("メールを送信しますか？") === false) { return false; }
    */

    /* 修正後： */
    if (confirm("結果を送信しますか？") === false) { return false; }
    /* ここまで */

    /*
      作成：朴昰成
      作成日：24/06/07
    */
    button.replaceChildren();

    var span = document.createElement("span");
    span.classList.add("spinner-border");
    span.classList.add("spinner-border-sm");
    span.ariaHidden = "true";
    button.appendChild(span);

    var span = document.createElement("span");
    span.role = "status";
    span.innerText = "送信中...";
    button.appendChild(span);

    /* ここまで */
		const postForm = new FormData();
		postForm.append("idxs", idx);
		const xhr = new XMLHttpRequest();
		xhr.open("POST", "../request", true);
		xhr.send(postForm);
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;

				if (result === "success") {
					alert("依頼しました。");
					self.location.href = "../list";
				}
				else {
					alert("error");
					console.log(result);
				}
			}
		}
	}

  /*
    作成：朴昰成
    修正：朴昰成
    修正日：24/06/07
  */

  /* 修正前：
    function SendMail() {
  */

  /* 修正後： */
  function SendMail(button) {
  /* ここまで */
    /*
      作成：朴昰成
      修正：朴昰成
      修正日：24/06/03
    */

    /* 修正前：
      if (confirm("メールを送信しますか？") === false) { return false; }
    */

    /* 修正後： */
    if (confirm("結果を送信しますか？") === false) { return false; }
    /* ここまで */

    /*
      作成：朴昰成
      修正：朴昰成
      修正日：24/06/03
    */

    /* 修正前：
      if (confirm("メールを送信しますか？") === false) { return false; }
    */

    /* 修正後： */
    if (confirm("結果を送信しますか？") === false) { return false; }
    /* ここまで */

    /*
      作成：朴昰成
      作成日：24/06/07
    */
    button.replaceChildren();

    var span = document.createElement("span");
    span.classList.add("spinner-border");
    span.classList.add("spinner-border-sm");
    span.ariaHidden = "true";
    button.appendChild(span);

    var span = document.createElement("span");
    span.role = "status";
    span.innerText = "送信中...";
    button.appendChild(span);

    /* ここまで */
    const postForm = new FormData();
    postForm.append("idxs", idx);
    const xhr = new XMLHttpRequest();
    xhr.open("POST", "../mail", true);
    xhr.send(postForm);
    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;

        if (result === "success") {
          alert("送信しました。");
          location.reload(true);
        }
        else {
          try {
            let idxDatas = JSON.parse(result);
            alert("すでに送信しました。");
            /*
              作成：朴昰成
              作成日：24/06/03
            */
            location.reload(true);
            /* ここまで */
            return false;
          } catch (e) {
            alert("error");
            console.log(result);
            return false;
          }
        }
      }
    }
  }
</script>