<?php 
echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); 
function InitStyle() { return " font-style: italic; color: grey;"; }
	$isITMajor = false;
	if ($recordArray["major"] == "IT・ソフトウェア専攻") {
		$isITMajor = true;
	}
?>


<h1 class="title">ITスキル診断状況管理</h1>

<form id="form" method="post" action="">
	<style type="text/css">
		option { color: black; }
		/* input::placeholder { font-style: italic; } */
	</style>

	<div class="emegra card">
		<div class="card-header">ITスキル診断者情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns:  repeat(2, 170px 1fr) }
			</style>
			<dl class="emegra info">
				<dt>ID</dt>
				<dd><input class="form-control" name="email" type="text" style="width:220px; " value="<?php echo $applicantArray["email"] ?>" readonly></dd>
				
                <dt class="essential">応募区分</dt>
				<select class="form-select" name="case" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" value="<?php echo $recordArray["case"] ?>" >
                        <option value="<?php echo ($recordArray['case']) ?>" selected hidden>
						<?php
							if ($recordArray['case'] == NULL) {
								echo "なし";
							} elseif($recordArray['case']==0) {
								echo "新卒";
							}	else{echo "中途（経歴職）";
							}
							?>					
						</option>
                        <option value="0">新卒</option>
                        <option value="1">中途（経歴職）</option>
                    </select>

                <dt>パスワード</dt>
				<dd><input class="form-control" name="password" type="text" style="width:220px;" value="123" readonly></dd>

				<dt class="essential">お名前（漢字）</dt>
				<dd><input class="form-control" id="userInput" name="name" type="text" placeholder="漢字を記入してください。"style="width:220px" maxlength='20' value="<?php echo $applicantArray["name"] ?>"></dd>

                <dt>申込日</dt>
				<dd><input class="form-control" name="apply_date" type="text" style="width:220px; " value="<?php echo $applicantArray["apply_date"] ?>" readonly></dd>
				
                <dt class="essential">お名前（カナ）</dt>
				<dd><input class="form-control" name="kana" type="text" placeholder="カナを記入してください。"style="width:220px" maxlength='50' value="<?php echo $applicantArray["kana"] ?>"></dd>

                <dt>性別</dt>
				<dd> 
					<select class="form-select"  name="gender" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" value="<?php echo $applicantArray["gender"] ?>" >
                        <option selected disabled hidden>
						<?php
							if ($applicantArray['gender'] == NULL) {
								echo "なし";
							} elseif($applicantArray['gender']==0) {
								echo "男";
							}	else{echo "女";
							}
							?>						
						</option>
                        <option value="0">男</option>
                        <option value="1">女</option>
                    </select>
				</dd>
				
                <dt class="essential">学歴</dt>
				<dd>
					<select class="form-select" name="education" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" id="educationSelect" >
                        <option value="<?php echo $recordArray['education'] ?>" selected  hidden>
						<?php
							if ($recordArray['education'] == 0) {
								echo "高卒";
							}elseif($recordData['education']==1) {
								echo "専門卒";
							}elseif($recordData['education']==2) {
								echo "大卒";
							}elseif($recordData['education']==3) {
								echo "大学院卒";
							}elseif($recordData['education']==4) {
								echo "その他";
							}
						?>				
						</option>
                        <option value="高卒">高卒</option>
                        <option value="専門卒">専門卒</option>
                        <option value="大卒">大卒</option>
                        <option value="大学院卒">大学院卒</option>
                        <option value="その他">その他</option>
                    </select>
                    <div id="otherEducationInput" style="margin-left: 10px; display:none;">
                        <input class="form-control" type="text" placeholder="その他の場合の、記入" id="otherEducation" name="education" maxlength='20'>
                    </div>
				</dd>

                <dt>生年月日</dt>
				<dd><input class="form-control" id="birth" name="birth" type="text" placeholder="YYYY-MM-DD" autocomplete="off"  style="width:220px" value="<?php echo $applicantArray["birth"] ?>"></dd> 

				<dt>IT関連資格</dt>
				<dd><input class="form-control" id="certificatesId" name="certificates" type="text"  style="width:220px" value="<?php echo $applicantArray["certificates"] ?>"></dd> 

				<dt>専攻</dt>
				<dd> 
					<select class="form-select" id="majorId" style="width:220px;" onchange="ChangeMajor(this)">
						<option value="" hidden>なし</option>
                        <option value="IT・ソフトウェア専攻"<?php echo ($isITMajor) ? " selected" : ""; ?>>IT・ソフトウェア専攻</option>
                        <option value="other"<?php echo ($recordArray["major"] != null && !$isITMajor) ? " selected" : ""; ?>>IT・ソフトウェア以外</option>
                    </select>
                    <input class="form-control w-50" style="margin-left: 10px;" type="text" placeholder="その他の場合の、記入" name="major" maxlength='20' value='<?php echo ($recordArray['major']) ?>' <?php echo ($isITMajor) ? "hidden" : ""; ?> />
				</dd>

				<dt>その他</dt>
				<dd><input class="form-control" id="other" name="other" type="text"  style="width:220px" value="<?php echo $applicantArray["other"] ?>"></dd> 
			</dl>
		</div>
	</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">診断者ITスキル有無</div>

	<div class="card-body">
		<style type="text/css">

		dl.emegra.setting { grid-template-columns: repeat(1, 180px 1fr); }
				</style>
			<dl class="emegra setting">
                <dt class="essential" id="ITskillTitle">ITスキル有無</dt>
				<dd>
					<select class="form-select" name="skill" id="ITskillId" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
					<option value="<?php echo ($recordArray['skill']) ?>" selected hidden>
						<?php
								if($recordArray['skill']==0){
									echo $recordArray['skill']="有";
								}
								else
									echo $recordArray['skill']="無";

								?>			
						</option>
                        <option value="0">有</option>
                        <option value="1">無</option>
                    </select>
				</dd>
                <dt class="essential" id="class1stTitle">経験分野</dt>
				<dd>
					<select class="form-select" name="class1st" id="class1stId" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)"  onclick="ChangeClass1st(this)" <?php echo $isDisabled ? 'disabled' : ''; ?>>
						<option value=""  selected disabled hidden>
							<?php
								if($recordArray['class1st']==NULL){
									$recordArray['class1st']="なし";
								}else
								echo $recordArray['class1st'];
								?>						
						</option>
						<?php foreach ($this->class1st as $row): ?>
							<?php $texts = explode(',', $row['text']); ?>
                            <?php foreach ($texts as $text): ?>
                                <option value="<?php echo $text; ?>"><?php echo $text; ?></option>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </select>
                    <div id="otherclass1stInput" style="margin-left: 10px; display:none;">
                        <input class="form-control" type="text" placeholder="その他の場合の、記入" id="otherclass1st" name="class1st" maxlength='20'>
                    </div>
				</dd>

				<dt class="essential" id=class2ndTitle>問題種別</dt>
				<dd>
					<select class="form-select" name="class2nd" id="class2ndId" style="width:220px;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)">
						<option value="" hidden>選択</option>
						<?php if (true): ?>
							<?php foreach ($optionDatas["class2nd"][$recordArray["class1st"]] as $data): ?>
								<option value="<?php echo $data["idx"]; ?>"<?php echo ($recordArray["class2nd"] == $data["idx"]) ? " selected" : ""; ?>>
									<?php echo $data["text"]; ?>
								</option>
							<?php endforeach; ?>
						<?php endif; ?>
                    </select>
				</dd>

				<dt class="essential" id="careerTitle">IT経験年数</dt>
				<dd><input class="form-control" name="career" id="careerId" type="text" placeholder="経歴を記入してください。" style="font-size:15px; width:220px" maxlength='2' value="<?php echo $applicantArray['career']?>"></dd> 
		</dl>
	</div>
</div>

    <div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">ITスキル診断問項詳細</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 140px 1fr); }
		</style>
		<dl class="emegra detail">
                <dt>診断依頼</dt>
				<dd><input class="form-control" name="request_date" type="text" style="width:220px; " value="<?php echo $recordArray['request_date']?>"readonly></dd>

				<dt class="essential">診断問項ID</dt>
				<dd><input class="form-control" name="" type="text" style="width:220px; " value="<?php echo $diagnosisArray['code']?>"></dd> 

				<dt class="essential">レベル</dt>
				<dd><input class="form-control" name="" type="text" style="width:80px; " 
				value="<?php if($diagnosisArray["level"]==0){
							echo "０級";}
						elseif($diagnosisArray["level"]==1){
							echo "初級";
						}
						elseif($diagnosisArray["level"]==2){
							echo "中級";
						}elseif($diagnosisArray["level"]==3){
							echo "高級";
						}
					 ?>">
				</dd>

				<dt class="essential">問項数別</dt>
				<dd><input class="form-control" name="request_date" type="text" style="width:50px;text-align:center " value="<?php echo $diagnosisArray['question_num']?>"> 問</dd>
		
				<dt class="essential">診断方法</dt>
                <dd style="grid-column: 2 / 5;">
					<select class="form-select" name="methods" style="width:13%;<?php echo ($isReturn) ? "" : InitStyle(); ?>" onchange="ChangeInputStyle(this)" >
                        <option value="" selected disabled hidden><?php echo $recordArray['method']?></option>
                        <option value="0">WEB</option>
                        <option value="1">対面</option>
                    </select>
				</dd>
		</dl>
	</div>
</div>
<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">ITスキル診断状況</div>

		<div class="card-body">
			<style type="text/css">
			dl.emegra.detail { grid-template-columns: repeat(2, 150px 1fr); }
			</style>
			<dl class="emegra detail">
				<dt>診断者のコメント</dt>
				<dd><input class="form-control" name="comment" type="text" style="width:220px; " value="<?php echo $recordArray['comment']?>"></dd>
		
				<dt>備考</dt>
				<dd><input class="form-control" name="note" type="text" style="width:220px; " value="<?php echo $recordArray['note']?>"></dd>

			</dl>
		</div>
	</div>

<div class="btn-place" style="margin-top: 32px;">
	<button type="button" class="emegra cancel" onclick="self.location.href='../../situation/list';">戻る</button>
	<button type="submit" class="emegra"  id="btn_submit" name="editDatas" value="btn_submit"  style="width:150px;">ITスキル診断依頼</button>
</div>
</form>

<script type="text/javascript">
	const smtp = document.getElementById("smtp");
	const form = document.getElementById("form");
	const pattern = /^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-za-z0-9\-]+/;

	function ActiveSmtp(value) {
		if (value == "y") { smtp.disabled = false; }
		else { smtp.disabled = true; }
	}

	function ChangeMajor(element) {
		ChangeInputStyle(element);
		if (form.major.value != "other") { 
			form.major.value = element.value;
		}
	}

	function Regist() {
		if (form.code.value == "") {
			alert("職別コードを入力してください");
			setTimeout("form.code.focus();", 100);
			return false;
		}
		
		if (form.id.value == "") {
			alert("IDを入力してください");
			setTimeout("form.id.focus()", 100);
			return false;
		}
		
		if (pattern.test(form.id.value) === false) {
			alert("IDを確認してください");
			setTimeout("form.id.focus()", 100);
			return false;
		}
		
		if (form.password.value == "") {
			alert("パスワードを入力してください");
			setTimeout("form.password.focus()", 100);
			return false;
		}
		
		if (form.name.value == "") {
			alert("名前を入力してください");
			setTimeout("form.name.focus()", 100);
			return false;
		}
		
		if (smtp.disabled == false && smtp.value == "") {
			alert("SMTPを入力してください");
			setTimeout("smtp.focus()", 100);
			return false;
		}

		form.submit();
	}
</script>
<script>
	function ChangeInputStyle(element) {
		element.style.fontStyle = "normal";
		element.style.color = "black";
	}
</script>

<script>
	window.onload=function(){
		console.log(form.major);
	}
</script>

<script>
	let skillSelect = document.getElementById('ITskillId');
	let class1stSelect = document.getElementById('class1stId')
	var class2ndSelect = document.getElementById('class2ndId')
	let careerSelect = document.getElementById('careerId')
	skillSelect.addEventListener('change', function() {
    var selectedValue = this.value;
			if (selectedValue === '1') {
				class1stSelect.diabled=true;
				class2ndSelect.diabled=true;
				careerSelect.diabled=true;
			}
			else{
				class1stSelect.diabled=false;
				class2ndSelect.diabled=false;
				careerSelect.diabled=false;
			}
			console.log(class1stSelect.diabled);
		}	
	)
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">

  <script>
    $(document).ready(function(){
      var birth = document.getElementById("birth");
      $(birth).datepicker({
        format: 'yyyy-mm-dd',
        autohide: true
      });
    });
  </script>

<script>
	 document.getElementById('educationSelect').addEventListener('change', function(event) {
    var selectedOption = event.target.value;
    var otherEducationInput = document.getElementById('otherEducationInput');

    if (selectedOption === "その他") {
        otherEducationInput.style.display = 'block';
    } else {
        otherEducationInput.style.display = 'none';
    }

    var otherEducation = document.getElementById('otherEducation');
    if (selectedOption === "その他") {
        otherEducation.removeAttribute('disabled');
    } else {
        otherEducation.setAttribute('disabled', 'disabled');
    }
});

document.getElementById('majorId').addEventListener('change', function(event) {
    var selectedOption = event.target.value;

    if (selectedOption === "other") {
		form.major.value = "";
        form.major.hidden = false;
    } else {
        form.major.hidden = true;
    }
});

document.getElementById('class1stId').addEventListener('change', function(event) {
    var selectedOption = event.target.value;
    var otherclass1stInput = document.getElementById('otherclass1stInput');

    if (selectedOption === "その他") {
        otherclass1stInput.style.display = 'block';
    } else {
        otherclass1stInput.style.display = 'none';
    }

    var otherclass1st = document.getElementById('otherclass1st');
    if (selectedOption === "その他") {
        otherclass1st.removeAttribute('disabled');
    } else {
        otherclass1st.setAttribute('disabled', 'disabled');
    }
});
</script>

<script>
	function ChangeClass1st(element) {

class2ndSelect.replaceChildren();

console.log(class2ndSelect);
switch (element.value) {
<?php foreach ($optionDatas["class2nd"] as $value => $class2nd): ?>
	case "<?php echo $value; ?>":
		var option = document.createElement("option");
		option.hidden = true;
		option.innerText = "選択してください。";
		class2ndSelect.appendChild(option);

		<?php foreach ($class2nd as $data): ?>
			var option = document.createElement("option");
			option.value = <?php echo $data["idx"]; ?>;
			option.innerText = "<?php echo $data["text"]; ?>";
			class2ndSelect.appendChild(option);
		<?php endforeach; ?>
		break;
		<?php endforeach; ?>
		default:
			var option = document.createElement("option");
			option.value = 7;
			option.innerText = "データがありません";
			class2ndSelect.appendChild(option);
			break;
	}
}
</script>