<?php if (!isset($_SESSION)) { session_start(); } ?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
	.header {
		height: 110px;
		display: flex;
		justify-content: space-between;
	}

	.info-num {
		height: 100%;
		display: flex;
		justify-content: end;
	}

	.search-place {
		width: 100%;
		margin-top: 20px;
		display: flex;
		align-items: center;
	}
	input.search {
		width: 150px;
	}
	button.emegra.search.confirm {
		height: 30px;
		width: 100px;
		
		font-size: 15px;
		font-weight: 400;
	}

	table.emegra tr { grid-template-columns: 50px 100px repeat(2, 60px) 60px 1fr 70px 50px repeat(2, 60px); }
	table.emegra tr.index {
		padding-top: 8px;
		padding-bottom: 4px;
		grid-template-columns: 50px 100px repeat(2, 60px) 60px 1fr 70px 50px repeat(2, 60px);
		grid-template-areas:
		"no status  class   class  level title type point confirm update"
		"no status class_l class_s level title type point confirm update";
	}
	table.emegra tr.index > th {
		padding: 4px 0;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.button-place {
		display: flex;
		justify-content: end;
	}
</style>
<content class="header">
	<div class="title">ITスキル診断問項管理</div>
	<div class="info-num">
		<div class="count">問項総計<div class="num">1,345</div>問項</div>
	</div>
</content>

<content class="main">
	<div class="search-place">
		<select class="form-select form-select-sm" style="width: 150px; margin-right: 10px;">
			<option value="status">ステータス</option>
			<option value="class1st">大分類</option>
			<option value="class2nd">小分類</option>
			<option value="level">レベル</option>
			<option value="title">タイトル</option>
			<option value="type">タイプ</option>
			<option value="point">点数</option>
		</select>
		<input class="form-control form-control-sm search" style="margin-right: 10px;"/>
		承認者
		<input class="form-control form-control-sm search" style="margin-left: 10px;" id="input_register" value="<?php echo (isset($inputDatas["register"])) ? $inputDatas["register"] : ""; ?>"/>

		<button class="emegra search confirm" style="margin-left: 10px;" onclick="SearchRegister()">検索</button>
	</div>

	<?php if (empty($questionDatas)): ?>
		<div class="table-empty" style="margin-top: 16px;">
			データがありません。
		</div>
		
	<?php else: ?>
	<table class="emegra" style="margin-top: 8px;">
		<thead>
			<tr class="index">
				<th style="grid-area: no">no</th>
				<th style="grid-area: status">ステータス</th>
				<th style="grid-area: class">問項種別</th>
				<th style="grid-area: level">レベル</th>
				<th style="grid-area: title">タイトル</th>
				<th style="grid-area: type">タイプ</th>
				<th style="grid-area: point">点数</th>
				<th style="grid-area: confirm">承認日</th>
				<th style="grid-area: update">更新日</th>
				<th style="grid-area: class_l">大分類</th>
				<th style="grid-area: class_s">小分類</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($questionDatas as $data): ?>
				<tr onclick="self.location.href='./detail/<?php echo $data['idx']; ?>';">
					<td><?php echo $data["num"]; ?></td>
					<td><?php echo $statusDatas[$data["status"]]; ?></td>
					<td><?php echo $class1stDatas[$data["class1st"]]; ?></td>
					<td><?php echo $class2ndDatas[$data["class2nd"]]; ?></td>
					<td><?php echo $levelDatas[$data["level"]]; ?></td>
					<td><?php echo $data["title"]; ?></td>
					<td><?php echo $typeDatas[$data["type"]]; ?></td>
					<td><?php echo $data["point"]; ?></td>
					<td><?php echo (isset($data["date_regist"])) ? date("y.m.d", strtotime($data["date_regist"])) : "未承認"; ?></td>
					<td><?php echo date("y.m.d", strtotime($data["date_update"])); ?></td>
				</tr>
			<?php endforeach; ?>
			<tr>
				<td>155</td>
				<td>承認依頼</td>
				<td>インフラ</td>
				<td>Python</td>
				<td>初級</td>
				<td>次の例問を見て答えてください</td>
				<td>4項選択</td>
				<td>1</td>
				<td>24.3.1</td>
				<td>23.4.1</td>
			</tr>
		</tbody>
	</table>
	<?php endif; ?>

	<div style="margin-top: 8px;">
		<?php echo $this->partial("pagination", $paginationData); ?>
	</div>

	<div class="button-place" style="margin-top: 10px;">
		<?php if ($_SESSION["user"]["level"] > 0): ?>
			<button class="emegra" style="margin-right: 8px;" onclick="self.window.location='./manage/regist'">一括承認</button>
		<?php endif; ?>
		<button class="emegra delete" style="margin-right: 8px;" onclick="self.window.location='./manage/delete'">一括削除</button>
		<button class="emegra" style="margin-right: 8px;">CSV登録</button>
		<button class="emegra" onclick="self.window.location='./regist'">新規登録</button>
	</div>	
</content>

<script type="text/javascript">
	const input_register = document.getElementById("input_register");

	function SearchRegister() {
		let register = input_register.value;
		self.window.location = window.location.pathname + "?register=" + register;
	}
</script>
