<?php
	$numTexts = array("①", "②", "③", "④", "⑤");

	function InitStyle() { return " font-style: italic; color: grey;"; }
	
	if (!isset($_SESSION)) { session_start(); }

	$isReturn = false;
	$answerNum = "";
	if (isset($questionData)) {
		$isReturn = true;
		$answers = explode(",", $questionData["answers"]);
		$answerNum = count($answers);
	}
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

<form id="form" method="post" action="./confirm">
	<style type="text/css">
		option { color: black; }
		input::placeholder { font-style: italic; }
	</style>

	<div class="emegra card">
		<div class="card-header">設定</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.setting { grid-template-columns: 140px 1fr; }
			</style>
			<dl class="emegra setting">
				<dt class="essential">大分類</dt>
				<dd>
					<select class="form-select" name="class1st" onchange="ChangeInputStyle(this)" style="width: 150px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php foreach($optionDatas["class1st"] as $data): ?>
							<option value="<?php echo $data["idx"]; ?>"<?php echo ($isReturn && $questionData["class1st"] == $data["idx"]) ? " selected" : ""; ?>>
								<?php echo $data["text"]; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt class="essential">小分類</dt>
				<dd>
					<select class="form-select" name="class2nd" onchange="ChangeInputStyle(this)" style="width: 150px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php foreach($optionDatas["class2nd"] as $idx => $data): ?>
							<option value="<?php echo $data["idx"]; ?>"<?php echo ($isReturn && $questionData["class2nd"] == $data["idx"]) ? " selected" : ""; ?>>
								<?php echo $data["text"]; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</dd>
		
				<dt class="essential">レベル</dt>
				<dd>
					<select class="form-select" name="level" onchange="ChangeInputStyle(this)" style="width: 100px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php foreach($optionDatas["level"] as $data): ?>
							<option value="<?php echo $data["idx"]; ?>"<?php echo ($isReturn && $questionData["level"] == $data["idx"]) ? " selected" : ""; ?>>
								<?php echo $data["text"]; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt class="essential">問題タイプ</dt>
				<dd>
					<select class="form-select" name="type" id="type" onchange="ChangeType(this)" style="width: 150px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php foreach($optionDatas["type"] as $data): ?>
							<option value="<?php echo $data["idx"]; ?>"<?php echo ($isReturn && $questionData["type"] == $data["idx"]) ? " selected" : ""; ?>>
								<?php echo $data["text"]; ?>
							</option>
						<?php endforeach; ?>
					</select>
				</dd>
		
				<dt class="essential">タイトル</dt>
				<dd><input class="form-control" name="title" type="text" placeholder="タイトルを入力してください" value="<?php echo ($isReturn) ? $questionData["title"] : ""; ?>"/></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">問題</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.question { grid-template-columns: 140px 1fr; }
			</style>
			<dl class="emegra question">
				<dt class="essential">問題</dt>
				<dd><input class="form-control" name="question" type="text" placeholder="問題を入力してください" value="<?php echo ($isReturn) ? $questionData["question"] : ""; ?>"/></dd>

				<dt class="essential">選択肢</dt>
				<div id="answers" name="answers" style="display: grid; grid-template-columns: 140px 1fr; grid-gap: 24px 8px;">
					<?php if ($isReturn): ?>
						<?php foreach ($answers as $index => $data): ?>
							<dt class="essential"><?php echo $numTexts[$index]; ?></dt>
							<dd><input class="form-control" name="answer<?= $index + 1; ?>" type="text" value="<?php echo $data; ?>"/></dd>
						<?php endforeach; ?>
					<?php else: ?>
						<dd style="grid-column: 1 / 3;">タイプを選択してください。</dd>
					<?php endif; ?>
				</div>

				<dt class="essential" id="correct-title">正解番号</dt>
				<dd>
					<select class="form-select" name="correct" id="correct" onchange="ChangeInputStyle(this)" style="width: 100px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php if ($isReturn): ?>
							<?php for ($i = 1; $i <= $answerNum; $i++): ?>
								<option value="<?= $i; ?>"<?php echo ($questionData["correct"] == $i) ? " selected" : ""; ?>><?= $numTexts[$i - 1]; ?></option>
							<?php endfor; ?>
						<?php endif; ?>
					</select>
				</dd>

				<dt class="essential">点数</dt>
				<dd>
					<select class="form-select" name="point" onchange="ChangeInputStyle(this)" style="width: 100px;<?php echo ($isReturn) ? "" : InitStyle(); ?>">
						<option value="" hidden>選択</option>
						<?php for($i = 1; $i <= 5; $i++): ?>
							<option value="<?= $i; ?>"<?php echo ($isReturn && $questionData["point"] == $i) ? " selected" : ""; ?>><?= $i; ?></option>
						<?php endfor; ?>
					</select>
				</dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns: 140px 1fr; }
			</style>
			<dl class="emegra info">
				<dt class="essential">作成者</dt>
				<dd>
					<select class="form-select" name="admin_regist" style="width: 150px;">
						<option value="" hidden>選択</option>
						<?php if ($isReturn): ?>
							<?php foreach($adminDatas as $data): ?>
								<option value="<?php echo $data["code"]; ?>"<?php echo ($data["code"] == $questionData["admin_regist"]) ? " selected" : ""; ?>><?php echo $data["name"]; ?></option>
							<?php endforeach; ?>
						<?php else: ?>
							<?php foreach($adminDatas as $data): ?>
								<option value="<?php echo $data["code"]; ?>"<?php echo ($data["code"] == $_SESSION["user"]["code"]) ? " selected" : ""; ?>><?php echo $data["name"]; ?></option>
							<?php endforeach; ?>
						<?php endif; ?>
					</select>
				</dd>

				<dt class="essential">作成日</dt>
				<dd><input class="form-control" name="date_regist" id="date_regist" type="date" style="width: 150px;" readonly value="<?php echo ($isReturn) ? date("Y-m-d", strtotime($questionData["date_regist"])) : date("Y-m-d"); ?>"></dd>
			
				<dt>備考</dt>
				<dd class="expand">
					<textarea class="form-control" name="note" rows="5"><?php echo ($isReturn) ? $questionData["note"] : ""; ?></textarea>
				</dd>
			</dl>
		</div>
	</div>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="self.location.href='./list'">戻る</button>
	<button class="emegra" onclick="Confirm();">登録</button>
</div>

<script type="text/javascript">
	const numTexts = ["①", "②", "③", "④", "⑤"];

	const type = document.getElementById("type");
	const answers = document.getElementById("answers");
	const correct = document.getElementById("correct");
	const dateRegist = document.getElementById("date_regist");
	const form = document.getElementById("form");

	let datetime = "";
	let answerCount = 0;

	// Get datetime data
	window.onload = function() {
		const now = new Date();
		datetime = now.toISOString().replace("T", " ").substring(0, 19);
	}

	// Change font style
	function ChangeInputStyle(element) {
		element.style.fontStyle = "normal";
		element.style.color = "black";
	}

	// Change 答え
	function ChangeType(element) {
		// Change font style for the first time
		if (answerCount == 0) { ChangeInputStyle(element); }

		text = element[element.selectedIndex].text.trim();
		switch(text) {
			case "3項選択":
				answerCount = 3;
				break;
			case "4項選択":
				answerCount = 4;
				break;
			case "5項選択":
				answerCount = 5;
				break;
		}

		// Delete 答え&正解番号
		answerChildren = Array.from(answers.children);
		answerChildren.forEach(element => { element.remove(); });

		correctChildren = Array.from(correct.children);
		correctChildren.forEach(element => { element.remove(); });
		
		// Change 正解番号 font style
		correct.style.fontStyle = "italic";
		correct.style.color = "grey";

		// Create 答え&正解番号 option
		var option = document.createElement("option");
		option.innerText = "選択";
		option.hidden = true;
		correct.appendChild(option);
		for (let i = 0; i < answerCount; i++) {
			let dt = document.createElement("dt");
			dt.classList.add("essential");
			dt.innerText = numTexts[i];
			answers.appendChild(dt);

			let dd = document.createElement("dd");
			let input = document.createElement("input");
			input.classList.add("form-control");
			input.name = "answer" + Number(i + 1);
			input.type = "text";
			dd.appendChild(input);
			answers.appendChild(dd);

			var option = document.createElement("option");
			option.value = Number(i) + 1;
			option.innerText = numTexts[i];
			correct.appendChild(option);
		}
	}

	function Confirm() {
		if (form.class1st.value == "") {
			RequestSelect(form.class1st, "大分類");
			return false;
		}

		if (form.class2nd.value == "") {
			RequestSelect(form.class2nd, "小分類");
			return false;
		}

		if (form.level.value == "") {
			RequestSelect(form.level, "レベル");
			return false;
		}

		if (form.type.value == "") {
			RequestSelect(form.type, "問題タイプ");
			return false;
		}

		if (form.title.value.trim() == "") {
			alert("タイトルを入力してください");
			setTimeout("form.title.focus()", 100);
			return false;
		}

		if (form.question.value.trim() == "") {
			alert("問題を入力してください");
			setTimeout("form.question.focus()", 100);
			return false;
		}

		for (let i = 1; i <= answerCount; i++) {
			var element = document.getElementsByName("answer" + i)[0];

			if (element.value.trim() == "") {
				alert("答え" + (Number(i) + 1) + "を入力してください");
				setTimeout("form.answer" + i + ".focus()", 100);
				return false;
			}
		}

		if (form.correct.value == "") {
			RequestSelect(form.correct, "正解番号");
			return false;
		}

		if (form.point.value == "") {
			RequestSelect(form.point, "点数");
			return false;
		}

		// Change 作成日 data
		dateRegist.type = "text";
		dateRegist.value = datetime;

		form.submit();
	}

	// For alert
	function RequestSelect(element, text) {
		alert(text + "を選択してください");
		element.focus();
	}
</script>