<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">CSV登録</h1>

<form enctype="multipart/form-data" id="form">
  <input class="form-control" type="file" name="file" id="file"/>
</form>
<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back();">戻る</button>
	<button class="emegra" onclick="Regist(this);">登録</button>
</div>

<script type="text/javascript">
	const form = document.getElementById("form");
  const file = document.getElementById("file");
  const buttonElements = document.getElementsByTagName("button");

	function Regist(button) {
    ChangeButton(button);

		const postForm = new FormData(form);
    postForm.append("file", file[0]);

		const xhr = new XMLHttpRequest();
		xhr.open("POST", "./createByCsv", true);
		xhr.send(postForm);

		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;	
				if (result == "success") {
					alert("登録しました。");
					self.location.href = "list";
				}
				else {
          try {
            noDatas = JSON.parse(result);
            let alertString = "登録できんかった問項があります。\n\n";
            alertString += "登録できなかった問項番号\n";
            alertString += noDatas.join(",");
            alert(alertString);
            console.log(result);
          } catch (e) {
            let alertString = "CSV形式ではありません。\n";
            alertString += "正しいCSVファイルを登録してください。";
            alert(alertString);
            console.log(result);
            console.log(e);
          }
          ChangeButton(button);
          return false;
				}
			}
		}
	}

  function ChangeButton(button) {
    button.replaceChildren();

    if (button.disabled == true) {
      button.innerText = "登録";

      for (let i = 0; i < buttonElements.length; i++) {
        buttonElements[i].disabled = false;
      }
    }
    else {
      var span = document.createElement("span");
      span.classList.add("spinner-border");
      span.classList.add("spinner-border-sm");
      span.ariaHidden = "true";
      button.appendChild(span);

      var span = document.createElement("span");
      span.role = "status";
      span.innerText = "登録中...";
      button.appendChild(span);

      for (let i = 0; i < buttonElements.length; i++) {
        buttonElements[i].disabled = true;
      }
    }
  }
</script>