<?php
	$numTexts = array("①", "②", "③", "④", "⑤");

	$answers = explode(",", $printDatas["answers"]);
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>
	<div class="emegra card">
		<div class="card-header">設定</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.setting { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra setting">
				<dt>大分類</dt>
				<dd><?php echo $optionDatas[$printDatas["class1st"]]; ?></dd>

				<dt>小分類</dt>
				<dd><?php echo $optionDatas[$printDatas["class2nd"]]; ?></dd>
		
				<dt>レベル</dt>
				<dd><?php echo $optionDatas[$printDatas["level"]]; ?></dd>

				<dt>問題タイプ</dt>
				<dd><?php echo $optionDatas[$printDatas["type"]]; ?></dd>
		
				<dt>タイトル</dt>
				<dd><?php echo $printDatas["title"]; ?></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">問題</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.question { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra question">
				<dt>問題</dt>
				<dd><?php echo $printDatas["question"]; ?></dd>

				<dt>答え</dt>
				<div id="answers" name="answers" style="display: grid; grid-template-columns: 15px 1fr; grid-gap: 24px 8px;">
					<?php foreach($answers as $index => $data): ?>
						<dt><?= $numTexts[$index]; ?></dt>
						<dd><?php echo $data; ?></dd>
					<?php endforeach; ?>
				</div>

				<dt>正解番号</dt>
				<dd><?php echo $numTexts[$printDatas["correct"] - 1]; ?></dd>

				<dt>点数</dt>
				<dd><?php echo $printDatas["point"]; ?></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra info">
				<dt>作成者</dt>
				<dd><?php echo $register; ?></dd>

				<dt>作成日</dt>
				<dd><?php echo date("y/m/d", strtotime($printDatas["date_regist"])); ?></dd>
			
				<dt>備考</dt>
				<dd><?php echo $printDatas["note"]; ?></dd>
			</dl>
		</div>
	</div>



<form id="form" method="post" action="./input">
	<?php foreach ($inputDatas as $key => $data): ?>
		<input type="hidden" name="<?php echo $key; ?>" value="<?php echo $data; ?>"/>
	<?php endforeach; ?>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="Return();">戻る</button>
	<button class="emegra" onclick="Regist();">確認</button>
</div>

<script type="text/javascript">
	const numTexts = ["①", "②", "③", "④", "⑤"];
	const form = document.getElementById("form");

	function Regist() {
		const postForm = new FormData();
		<?php foreach($inputDatas as $key => $data): ?>
			postForm.append("<?php echo $key; ?>", "<?php echo $data; ?>");
		<?php endforeach; ?>

		const xhr = new XMLHttpRequest();
		xhr.open("POST", "create", true);
		xhr.send(postForm);
		
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
				if (result == "success") {
					alert("登録しました。");
					self.location.href = "list";
				}
				else {
					alert("Error");
					console.log(result);
				}
			}
		}
	}

	function Return() {
		form.submit();
	}
</script>