<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">CSV登録</h1>

<form enctype="multipart/form-data" id="form">
  <input class="form-control" type="file" name="file" id="file"/>
</form>
<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back();">戻る</button>
	<button class="emegra" onclick="Regist(this);">登録</button>
</div>

<script type="text/javascript">
	const form = document.getElementById("form");
  const file = document.getElementById("file");
  const buttonElements = document.getElementsByTagName("button");

	function Regist(button) {
    ChangeButton(button);

		const postForm = new FormData(form);
    postForm.append("file", file[0]);

		const xhr = new XMLHttpRequest();
		xhr.open("POST", "./createByCsv", true);
		xhr.send(postForm);

		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;	
        console.log(result);

				if (result == "success") {
					alert("登録しました。");
					self.location.href = "list";
				}
				else {
          try {
            let resultData = JSON.parse(result);
            
            if (resultData.hasOwnProperty("reason")) {
              if (resultData["reason"] == "fail to open file") {
                alert("ファイルを開くことに失敗しました。");
              }
              else if (resultData["reason"] == "not csv file") {
                alert("CSVファイルを登録してください。");
              }

              console.log(resultData);
              ReturnButton(button);
              return false;
            }

            let alertString = "登録できんかった問項があります。";
            alertString += "\n\n登録できなかった問項番号";
            alertString += "\n" + resultData.join(",");
            alert(alertString);

            console.log(resultData);
            ReturnButton(button);
            return false;
          } catch (e) {
            let alertString = ErrorString();
            alertString += "\nexception error in question_csv Regist";
            alertString += "\nexception message: " + e;
            alertString += "\nresponseText: " + result;
            alert(alertString);

            ReturnButton(button);
            return false;
          }
				}
			}
      else {
        let alertString = ErrorString();
        alertString += "\nxhr error in diagnosis_input SetDiagnosisList";
        alertString += "\nerror code: " + xhr.status;
        alert(alertString);

        ReturnButton();
        return false;
      }
		}
	}



  function ErrorString() {
    let alertString = "予期せぬエラーが発生しました。";
    alertString += "\n管理者にエラー内容をお知らせくださいますようお願いいたします。";
    alertString += "\n\nエラー内容：";
    return alertString;
  }

  function ChangeButton(button) {
    button.replaceChildren();

    var span = document.createElement("span");
    span.classList.add("spinner-border");
    span.classList.add("spinner-border-sm");
    span.ariaHidden = "true";
    button.appendChild(span);

    var span = document.createElement("span");
    span.role = "status";
    span.innerText = "登録中...";
    button.appendChild(span);

    for (let i = 0; i < buttonElements.length; i++) {
      buttonElements[i].disabled = true;
    }
  }

  function ReturnButton(button) {
    button.replaceChildren();

    button.innerText = "登録";

    for (let i = 0; i < buttonElements.length; i++) {
      buttonElements[i].disabled = false;
    }
  }
</script>