<?php
	$numTexts = array("①", "②", "③", "④", "⑤");
  $levelTexts = array("無級", "初級", "中級", "高級");

	$answerNum = 0;
	for ($i = 1; $i <= 5; $i++) {
		if (!isset($questionData["answer" . $i])) { break; }
		$answerNum++;
	}
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

	<div class="emegra card">
		<div class="card-header">設定</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.setting { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra setting">
				<dt>大分類</dt>
				<dd><?php echo $optionDatas[$questionData["class1st"]]; ?></dd>

				<dt>小分類</dt>
				<dd><?php echo $optionDatas[$questionData["class2nd"]]; ?></dd>
		
				<dt>レベル</dt>
				<dd><?php echo $levelTexts[$questionData["level"]]; ?></dd>

				<dt>問題タイプ</dt>
				<dd><?php echo $optionDatas[$questionData["type"]]; ?></dd>
		
				<dt>タイトル</dt>
				<dd><?php echo htmlspecialchars($questionData["title"], ENT_QUOTES); ?></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">問題</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.question { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra question">
				<div style="grid-column: 1 / 3;">
					<nav style="margin-bottom: 30px;">
						<div class="nav nav-tabs" id="nav-tab" role="tablist">
							<button class="nav-link active" id="nav-tab" data-bs-toggle="tab" data-bs-target="#nav" type="button" role="tab" aria-controls="nav" aria-selected="true">日本語</button>

							<?php foreach ($languageCodeDatas as $code => $text): ?>
								<button class="nav-link" id="nav-<?php echo $code; ?>-tab" data-bs-toggle="tab" data-bs-target="#nav-<?php echo $code; ?>" type="button" role="tab" aria-controls="nav-<?php echo $code; ?>" aria-selected="false"><?php echo $text; ?></button>
							<?php endforeach; ?>
						</div>
					</nav>
					<div class="tab-content" id="nav-tabContent">
						<div class="tab-pane show active" id="nav" role="tabpanel" aria-labelledby="nav-tab">
							<dl class="emegra question">
								<dt>問題</dt>
                <!--
                  作成：朴昰成
                  修正：朴昰成
                  修正日：24/05/30
                -->
                <!-- 修正前： <?php /* ?>
                  <dd><?php echo htmlspecialchars($questionData["question"], ENT_QUOTES); ?></dd>
                <?php */ ?> -->

                <!-- 修正後： -->
                <dd class="expand"><?php echo str_replace("{{n}}", "<br/>", htmlspecialchars($questionData["question"], ENT_QUOTES)); ?></dd>
                <!-- ここまで -->

								<dt>選択肢</dt>
								<dd class="expand">
									<?php for ($i = 1; $i <= $answerNum; $i++): ?>
										<?= $numTexts[$i - 1]; ?>
										<?php echo htmlspecialchars($questionData["answer" . $i], ENT_QUOTES); ?></br>
									<?php endfor; ?>
								</dd>
							</dl>
						</div>

						<?php foreach ($languageCodeDatas as $code => $text): ?>
							<div class="tab-pane" id="nav-<?php echo $code; ?>" role="tabpanel" aria-labelledby="nav-<?php echo $code; ?>-tab">
								<dl class="emegra question">
									<dt>問題</dt>
                  <!--
                    作成：朴昰成
                    修正：朴昰成
                    修正日：24/05/30
                  -->
                  <!-- 修正前： <?php /* ?>
                    <dd><?php echo htmlspecialchars($questionData["question_" . $code], ENT_QUOTES); ?></dd>
                  <?php */ ?> -->

                  <!-- 修正後： -->
                  <dd class="expand"><?php echo str_replace("{{n}}", "<br/>", htmlspecialchars($questionData["question_" . $code], ENT_QUOTES)); ?></dd>
                  <!-- ここまで -->

									<dt>選択肢</dt>
									<dd class="expand">
										<?php for ($i = 1; $i <= $answerNum; $i++): ?>
											<?= $numTexts[$i - 1]; ?>
											<?php echo htmlspecialchars($questionData["answer" . $i . "_" . $code], ENT_QUOTES); ?></br>
										<?php endfor; ?>
									</dd>
								</dl>
							</div>
						<?php endforeach; ?>
					</div>
				</div>

				<dt>正解番号</dt>
				<dd><?php echo $numTexts[$questionData["correct"] - 1]; ?></dd>

				<dt>点数</dt>
				<dd><?php echo $questionData["point"]; ?></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra info">
				<dt>作成者</dt>
				<dd><?php echo $register; ?></dd>

				<dt>作成日</dt>
				<dd><?php echo date("y/m/d", strtotime($questionData["date_regist"])); ?></dd>
			
				<dt>備考</dt>
				<dd><?php echo $questionData["note"]; ?></dd>
			</dl>
		</div>
	</div>



<form id="form" method="post"	>
	<?php foreach ($questionData as $key => $data): ?>
		<input type="hidden" name="<?php echo $key; ?>" value="<?php echo $data; ?>"/>
	<?php endforeach; ?>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="Return();">戻る</button>
	<button class="emegra" onclick="Regist();">確認</button>
</div>

<script type="text/javascript">
	const numTexts = ["①", "②", "③", "④", "⑤"];
	const form = document.getElementById("form");

	function Regist() {
		const postForm = new FormData(form);
		const xhr = new XMLHttpRequest();
		xhr.open("POST", "regist", true);
		xhr.send(postForm);
		xhr.onload = () => {
			if (xhr.status == 200) {
				const result = xhr.responseText;
				if (result == "success") {
					alert("登録しました。");
					self.location.href = "list";
				}
				else {
					alert("Error");
					console.log(result);
				}
			}
		}
	}

	function Return() {
		setCookie("questionData", '<?php echo json_encode($questionData); ?>', {secure: true, "max-age": 30});
		history.back();
	}
</script>