<?php
	if (!isset($_SESSION)) { session_start(); }
	$numTexts = array("①", "②", "③", "④", "⑤");
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title"><?php echo $title; ?></h1>

<form id="form" method="post" action="./confirm">
	<div class="emegra card">
		<div class="card-header">設定</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.setting { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra setting">
				<dt>大分類</dt>
				<dd>
					<select class="form-select" name="class1st" style="width: 150px;">
						<?php foreach($class1stDatas as $idx => $data): ?>
							<option value="<?php echo $idx; ?>"><?php echo $data; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt>小分類</dt>
				<dd>
					<select class="form-select" name="class2nd" style="width: 150px;">
						<?php foreach($class2ndDatas as $idx => $data): ?>
							<option value="<?php echo $idx; ?>"><?php echo $data; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>
		
				<dt>レベル</dt>
				<dd>
					<select class="form-select" name="level" style="width: 100px;">
						<?php foreach($levelDatas as $idx => $data): ?>
							<option value="<?php echo $idx; ?>"><?php echo $data; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt>問題タイプ</dt>
				<dd>
					<select class="form-select" name="type" id="type" onchange="ChangeType(this.value)" style="width: 150px;">
						<?php foreach($typeDatas as $idx => $data): ?>
							<option value="<?php echo $idx; ?>"><?php echo $data; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>
		
				<dt>タイトル</dt>
				<dd><input class="form-control" name="title" type="text"></dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">問題</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.question { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra question">
				<dt>問題</dt>
				<dd><input class="form-control" name="question" type="text"></dd>

				<dt>答え</dt>
				<div id="answers" name="answers" style="display: grid; grid-template-columns: 15px 1fr; grid-gap: 24px 8px;"></div>

				<dt>正解番号</dt>
				<dd>
					<select class="form-select" name="correct" id="correct" style="width: 70px;"></select>
				</dd>

				<dt>点数</dt>
				<dd>
					<select class="form-select" name="point" style="width: 70px;">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
					</select>
				</dd>
			</dl>
		</div>
	</div>

	<div class="emegra card" style="margin-top: 32px;">
		<div class="card-header">情報</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns: 90px 1fr; }
			</style>
			<dl class="emegra info">
				<dt>作成者</dt>
				<dd>
					<select class="form-select" name="admin_create" style="width: 150px;">
						<?php foreach($adminDatas as $data): ?>
							<option value="<?php echo $data["code"]; ?>"<?php echo $data["code"] == $_SESSION["user"]["code"] ? " selected" : ""; ?>><?php echo $data["name"]; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>

				<dt>作成日</dt>
				<dd><input class="form-control" name="date_create" id="date_create" type="date" style="width: 150px;" disabled value="<?= date("Y-m-d"); ?>"></dd>

				<dt>承認者</dt>
				<dd>
					<select class="form-select" name="admin_regist" style="width: 150px;">
						<?php foreach($approvalDatas as $data): ?>
							<option value="<?php echo $data["code"]; ?>"><?php echo $data["name"]; ?></option>
						<?php endforeach; ?>
					</select>
				</dd>
			
				<dt>備考</dt>
				<dd class="expand">
					<textarea class="form-control" name="note" rows="5"></textarea>
				</dd>
			</dl>
		</div>
	</div>
</form>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra" onclick="Regist();">登録</button>
	<button class="emegra cancel" onclick="history.back();">戻る</button>
</div>

<script type="text/javascript">
	const numTexts = ["①", "②", "③", "④", "⑤"];

	const type = document.getElementById("type");
	const answers = document.getElementById("answers");
	const correct = document.getElementById("correct");
	const dateCreate = document.getElementById("date_create");

	const form = document.getElementById("form");

	let datetime = "";

	window.onload = function() {
		const now = new Date();
		datetime = now.toISOString().replace("T", " ").substring(0,19);
		
		ChangeType(type.value);
	}
	
	function ChangeType(value) {
		answerChildren = Array.from(answers.children);
		answerChildren.forEach(element => { element.remove(); });
		
		correctChildren = Array.from(correct.children);
		correctChildren.forEach(element => { element.remove(); });
		
		for (let i = 0; i < Number(value) + 3; i++) {
			let dt = document.createElement("dt");
			dt.innerText = numTexts[i];
			answers.appendChild(dt);

			let dd = document.createElement("dd");
			let input = document.createElement("input");
			input.classList.add("form-control");
			input.name = "answer" + i;
			input.type = "text";
			dd.appendChild(input);
			answers.appendChild(dd);

			let option = document.createElement("option");
			option.value = i;
			option.innerText = numTexts[i];
			correct.appendChild(option);
		}
	}

	function Regist() {
		dateCreate.disabled = false;
		dateCreate.type = "text";
		dateCreate.value = datetime;
		
		form.submit();
	}
</script>