<?php
  $levelTexts = ["無級", "初級", "中級", "高級"];

  $selectTypeDatas = array(
    "status" => "ステータス",
    "class" => "問項種別",
    "level" => "レベル",
  );

  $selectNumberDatas = array(
    "status" => 1,
    "class" => 2,
    "level" => 1,
  );

  /** check delete authority
   * @param array $data questionData
   * @param array $optionDatas ["idx" => "text"]
	 * @return bool
  */
  function ChkDeleter($data, $optionDatas) {
    if ($optionDatas[$data["status"]] == "新規") { return true; }
    return false;
  }

  if (!isset($_SESSION)) { session_start(); }
  $url = explode("?", $_SERVER["REQUEST_URI"]);
  $route = $url[0];

  $isSearch = array(
    "select" => false,
    "title" => false,
  );

  $queryDatas = array();
  if (isset($url[1])) {
    $querys = explode("&", $url[1]);
    foreach ($querys as $query) {
      $queryData = explode("=", $query);

      if ($queryData[0] == "page") { continue; }

      if ($queryData[0] == "select") {
        $queryDatas["select"] = explode("-", $queryData[1]);
        $isSearch["select"] = true;
      }
      else {
        $queryDatas[$queryData[0]] = $queryData[1];
        $isSearch[$queryData[0]] = true;
      }
    }
  }

  $firstNo = $questionDatas->getTotalItemCount();
  $firstNo -= (($questionDatas->getCurrentPageNumber() - 1) * $questionDatas->getitemCountPerPage());

  // check select
  $isSelect = false;
  if (isset($searchDatas["select"])) { $isSelect = true; }

  // check authority
  $isApprover = false;
  if ($_SESSION["user"]["level"] >= 1) { $isApprover = true; }
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<style type="text/css">
  p {
    display: flex;
    align-items: center;
  }
  .header {
    height: 110px;
    display: flex;
    justify-content: space-between;
  }

  .search-place {
    width: 100%;
    margin-top: 20px;

    display: flex;
    justify-content: space-between;

    text-align: center;
  }
  button.emegra.search.confirm {
    height: 30px;
    width: 100px;

    font-size: 15px;
    font-weight: 400;
  }

  .pagination-place, .button-place {
    margin-top: 10px;
    display: flex;
    justify-content: center;
  }
  .button-place { justify-content: space-between; }
</style>
<content class="header">
  <div class="title">ITスキル診断問項管理</div>
  <div class="info-num">
    <div class="count">問項総計<div class="num"><?php echo $totalNum; ?></div>問項</div>
  </div>
</content>

<content class="main">
  <div class="search-place">
    <div></div>

    <div style="display: flex;">
      <select class="form-select form-select-sm" id="select-select_key" style="width: 120px; margin-left: 8px;" onchange="SelectKey(this);">
        <option value="">全て</option>
        <?php foreach ($selectTypeDatas as $value => $text): ?>
          <option value="<?= $value; ?>"<?php echo ($isSearch["select"] && $queryDatas["select"][0] == $value) ? " selected" : ""?>><?= $text; ?></option>
        <?php endforeach; ?>
      </select>

      <select class="form-select form-select-sm" id="select-select_value" style="width: 120px; margin-left: 8px;" onchange="Select(this);">
        <?php if ($isSearch["select"]): ?>
          <option value=""></option>

          <?php if ($queryDatas["select"][0] == "level"): ?>
            <?php for ($i = 0; $i <= 3; $i++): ?>
              <option value="<?= $i; ?>"<?php echo (isset($queryDatas["select"][1]) && $queryDatas["select"][1] == $i) ? " selected" : ""?>><?= $levelTexts[$i]; ?></option>
            <?php endfor; ?>
          <?php elseif ($queryDatas["select"][0] == "class"): ?>
            <?php foreach($selectValueDatas["class1st"] as $data): ?>
              <option value="<?php echo $data["idx"]; ?>"<?php echo (isset($queryDatas["select"][1]) && $queryDatas["select"][1] == $data["idx"]) ? " selected" : ""?>><?php echo $data["text"]; ?></option>
            <?php endforeach; ?>
          <?php else: ?>
            <?php foreach($selectValueDatas[$queryDatas["select"][0]] as $data): ?>
              <option value="<?php echo $data["idx"]; ?>"<?php echo (isset($queryDatas["select"][1]) && $queryDatas["select"][1] == $data["idx"]) ? " selected" : ""?>><?php echo $data["text"]; ?></option>
            <?php endforeach; ?>
          <?php endif; ?>
        <?php endif; ?>
      </select>

      <select class="form-select form-select-sm" id="select-select_class" style="width: 120px; margin-left: 8px;" onchange="Select(this);"<?php echo ($isSearch["select"] && $selectNumberDatas[$queryDatas["select"][0]] >= 2) ? "" : " disabled"; ?>>
        <?php if ($isSearch["select"] && $queryDatas["select"][0] == "class" && isset($queryDatas["select"][1])): ?>
          <option value=""></option>

          <?php foreach($selectValueDatas["class2nd"][$queryDatas["select"][1]] as $data): ?>
            <option value="<?php echo $data["idx"]; ?>"<?php echo (isset($queryDatas["select"][2]) && $queryDatas["select"][2] == $data["idx"]) ? " selected" : ""?>><?php echo $data["text"]; ?></option>
          <?php endforeach; ?>
        <?php endif; ?>
      </select>
      <p style="margin-left: 8px;">タイトル</p>
      <input class="form-control form-control-sm"  style="width: 150px; margin-left: 8px;" id="input_title" value="<?php echo (isset($searchDatas["title"])) ? $searchDatas["title"] : ""; ?>"/>
      <button class="emegra search confirm" style="margin-left: 8px;" onclick="SearchTitle()">検索</button>
    </div>



    <script>
      const selectSelectKey = document.getElementById("select-select_key");
      const selectSelectValue = document.getElementById("select-select_value");
      const selectSelectClass = document.getElementById("select-select_class");

      function SelectKey(element) {
        let value = element.value;
        if (value == "") { Select(element); }

        selectSelectValue.replaceChildren();
        var option = document.createElement("option");
        option.value = "";
        selectSelectValue.appendChild(option);

        /*
          作成：朴昰成
          修正：朴昰成
          修正前：24/06/19
        */

        /* 修正前：
        if (value == "class") { selectSelectClass.disabled = false; }
        else { selectSelectClass.disabled = true; }
        */

        /* 修正後： */
        if (value == "class") {
          selectSelectClass.disabled = false;
        }
        else {
          selectSelectClass.replaceChildren();
          selectSelectClass.disabled = true;
        }
        /* ここまで */

        switch(value) {
          case "status":
            <?php foreach ($selectValueDatas["status"] as $data): ?>
              option = document.createElement("option");
              option.value = "<?php echo $data["idx"]; ?>";
              option.innerText = "<?php echo $data["text"]; ?>";
              selectSelectValue.appendChild(option);
            <?php endforeach; ?>
            break;
          case "class":
            <?php foreach ($selectValueDatas["class1st"] as $data): ?>
              option = document.createElement("option");
              option.value = "<?php echo $data["idx"]; ?>";
              option.innerText = "<?php echo $data["text"]; ?>";
              selectSelectValue.appendChild(option);
            <?php endforeach; ?>
            break;
          case "level":
            <?php for ($i = 0; $i <= 3; $i++): ?>
              option = document.createElement("option");
              option.value = "<?= $i; ?>";
              option.innerText = "<?= $levelTexts[$i]; ?>";
              selectSelectValue.appendChild(option);
            <?php endfor; ?>
            break;
        }
      }

      function Select(element) {
        <?php
          $newQuery = "?";

          if (!empty($queryDatas)) {
            foreach ($queryDatas as $key => $data) {
              if ($key == "page") { continue; }
              if ($key == "select") { continue; }
    
              if (gettype($data) == "string") { $newQuery .= $key . "=" . $data . "&"; }
              else { $newQuery .= $key . "=" . implode("-", $data) . "&"; }
            }
          }

          $url = $route . $newQuery;
        ?>
        let url = "<?= $url; ?>";

        if (selectSelectKey.value == "") {
          url = url.slice(0, -1);
          self.window.location = url;
          return true;
        }
        url += "select=" + selectSelectKey.value + "-";

        if (selectSelectValue.value == "") {
          url = url.slice(0, -1);
          self.window.location = url;
          return true;
        }
        url += selectSelectValue.value + "-";

        if (element == selectSelectValue || selectSelectClass.value == "") {
          url = url.slice(0, -1);
          self.window.location = url;
          return true;
        }
        url += selectSelectClass.value + "-";

        url = url.slice(0, -1);
        self.window.location = url;
        return true;
      }
    </script>
  </div>

  <div class="emegra-table">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th rowspan="2">No</th>
          <th rowspan="2">ステータス</th>
          <th colspan="2">問項種別</th>
          <th rowspan="2">レベル</th>
          <th rowspan="2">タイトル</th>
          <th rowspan="2">タイプ</th>
          <th rowspan="2">点数</th>
          <th rowspan="2">作成日</th>
          <th rowspan="2">承認日</th>
          <th rowspan="2"><input id="checkAll" type="checkbox" onclick="Checking(this);" style="cursor: pointer;"></th>
        </tr>
        <tr>
          <th>大分類</th>
          <th>小分類</th>
        </tr>
      </thead>
      <tbody>
        <?php if (empty(iterator_to_array($questionDatas))): ?>
          <td colspan="17">問項がありません。</td>
        <?php else: ?>
          <?php foreach($questionDatas as $index => $data): ?>
            <tr>
              <td><?php echo $firstNo - $index ; ?></td>
              <td><?php echo $optionDatas[$data["status"]]; ?></td>

              <td><?php echo $optionDatas[$data["class1st"]]; ?></td>
              <td><?php echo $optionDatas[$data["class2nd"]]; ?></td>

              <td><?php echo $levelTexts[$data["level"]]; ?></td>
              <td class="start"><a onclick="self.location.href='./detail/<?php echo $data['idx']; ?>';"><?php echo $data["title"]; ?></a></td>
              <td><?php echo $optionDatas[$data["type"]]; ?></td>
              <td><?php echo $data["point"]; ?></td>
              <td><?php echo date("y.m.d", strtotime($data["date_regist"])); ?></td>
              <td><?php echo (isset($data["date_approve"])) ? date("y.m.d", strtotime($data["date_approve"])) : "未承認"; ?></td>
              <td><input name="checkIdx" type="checkbox" value="<?php echo $data["idx"]; ?>" onclick="Checking(this);" style="cursor: pointer;"<?php echo ($isApprover || ChkDeleter($data, $optionDatas)) ? "" : " disabled"; ?>></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>

  <div class="pagination-place" style="margin-top: 10px;">
    <?php echo $this->paginationControl($questionDatas, "sliding", array("pagination", "Notice"), array("url" => "")); ?>
  </div>

  <div class="button-place" style="margin-top: 10px;">
    <div></div>

    <div>
      <?php if ($_SESSION["user"]["level"] >= 1): ?>
        <button class="emegra" style="margin-right: 8px;" onclick="Approve()">承認</button>
      <?php endif; ?>
      <button class="emegra delete" style="margin-right: 8px" onclick="Remove()">削除</button>
      <button class="emegra" style="margin-right: 8px;" onclick="self.window.location='./csv'">CSV登録</button>
      <button class="emegra" onclick="self.window.location='./input'">新規登録</button>
    </div>
  </div>
</content>

<script type="text/javascript">
  const input_approver = document.getElementById("input_approver");
  const input_title = document.getElementById("input_title");
  const div_search = document.getElementById("div_search");
  const check_all = document.getElementById("checkAll");
  const checkElements = document.getElementsByName("checkIdx");

  let searchData = "status";

	window.onpageshow = function(event) {
    if(event.persisted || (window.performance && window.performance.navigation.type == 2)) {
      check_all.checked = false;
      for (let i = 0; i < checkElements.length; i++) {
        checkElements[i].checked = false;
      }
    }
  }

  function Checking(element) {
    if (element == check_all) {
      for (let i = 0; i < checkElements.length; i++) {
        if (!checkElements[i].disabled) {
          checkElements[i].checked = element.checked;
        }
      }
    }
    else {
      let allChecked = true;
      for (let i = 0; i < checkElements.length; i++) {
        if (checkElements[i].checked == false) {
          if (checkElements[i].disabled == true) { continue; }
          allChecked = false;
          break;
        }
      }

      check_all.checked = allChecked;
    }
  }

  function SearchTitle() {
    <?php
      $newQuery = "?";

      if (!empty($queryDatas)) {
        foreach ($queryDatas as $key => $data) {
          if ($key == "title") { continue; }
          if ($key == "page") { continue; }

          $newQuery .= $key . "=" . implode("-", $data) . "&";
        }
      }

      $url = $route . $newQuery;
    ?>

    let url = "<?= $url; ?>";

    let title = input_title.value;
    if (title.trim() != "") { url += "title=" + title + "&"; }
    url = url.slice(0, -1);

    self.window.location = url;
  }

  function Approve() {
    let idxs = "";
    for (let i = 0; i < checkElements.length; i++) {
      if (checkElements[i].checked) {
        idxs += checkElements[i].value + ",";
      }
    }

    if (idxs == "") {
      alert("承認する問項を選択してください。");
      return false;
    }

    if (confirm("承認しますか？") === false) { return false; }

    const postForm = new FormData();
    postForm.append("idxs", idxs.slice(0, -1));

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "approve", true);
    xhr.send(postForm);
    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;

        if (result == "success") {
          alert("承認しました。");
          location.reload(true);
        }
        else {
          try {
            error = JSON.parse(result);

            switch (error["reason"]) {
              case "approved":
                let alertString = "承認できなかった問項があります。\n\n"
                alertString += "承認できなかった問項";

                let questionIdxDatas = error["data"];
                for (let i = 0; i < questionIdxDatas.length; i++) {
                  for (let j = 0; j < checkElements.length; j++) {
                    if (questionIdxDatas[i] == checkElements[j].value) {
                      alertString += "\n" + checkElements[j].parentNode.parentNode.children[0].innerText + "．" + checkElements[j].parentNode.parentNode.children[5].innerText;
                    }
                  }
                }

                alert(alertString);
                return false;
            }
            alert("error");
            console.log(result);
            return false;
          }
          catch (e) {
            alert("error");
            console.log(result);
            return false;
          }
        }
      }
    }
  }

  function Remove() {
    let idxs = "";
    for (let i = 0; i < checkElements.length; i++) {
      if (checkElements[i].checked) {
        idxs += checkElements[i].value + ",";
      }
    }

    if (idxs == "") {
      alert("削除する問項を選択してください。");
      return false;
    }

    if (confirm("削除しますか？") === false) { return false; }

    const postForm = new FormData();
    postForm.append("idxs", idxs.slice(0, -1));

    const xhr = new XMLHttpRequest();
    xhr.open("POST", "remove", true);
    xhr.send(postForm);
    xhr.onload = () => {
      if (xhr.status == 200) {
        const result = xhr.responseText;
        if (result == "success") {
          alert("削除しました。");
          location.reload(true);
        }
        else {
          alert("Error");
          console.log($result);
        }
      }
    }
  }
</script>
