<?php
if($this->data['idx']!=''):?>

	<nav aria-label="breadcrumb" style='margin:0;padding:0;'>
	  <ol class="breadcrumb" style='margin:0;'>
	    <li class="breadcrumb-item"><a href="/" style='margin-left:0;'>トップ</a></li>
	    <li class="breadcrumb-item active"><a href="#" style='margin-left:0;'>書類発行</a></li>
	  </ol>
	</nav>

	<div class="container-fluid">

		<div class='' style='padding-top:20px;'>
			<div class='col-xs-12'>
				申請した書類をダウンロードしてください。
			</div>
		</div>

		<table class='table table-bordered table-striped table-hover table-sm'>
			<thead class='thead-dark'>
				<tr style='text-align:center;vertical-align:middle;'>
					<th>書類番号</th>
					<th>区分</th>
					<th>発行日</th>
					<th>有効期間</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr style='text-align:center;vertical-align:middle;'>
					<td><?php echo $this->data['idx']?></td>
					<td><?php switch($this->data['kubun']){
						case "1":echo "在職証明書";break;
						case "2":echo "源泉徴収票";break;
					}?></td>
					<td><?php echo date("Y-m-d",strtotime($this->data['paid_date']))?></td>
					<td><?php echo date("Y-m-d",strtotime($this->data['expirydate']))?></td>
					<td style='min-width:120px;'><a class='btn btn-danger btn-sm' href='/application/applicationfiledownload?securitycode=<?php echo $this->data['idx']?>2x9a5ew<?php echo md5($this->pw)?>'>ダウンロード</a></td>
				</tr>
			</tbody>
		</table>


	</div>






<?php else:?>

	<nav aria-label="breadcrumb" style='margin:0;padding:0;'>
	</nav>

	<div class="container-fluid">

		<div class='justify-content-xs-center align-items-center' style='padding-top:60px;text-align:center;'>
			<div class='col-xs-12 text-center'>
				認証パスワードを入力してください。
			</div>
		</div>
		<script type='text/javascript'>
			function chksub(f){
				if(f.userpw.value.length==0){
					alert("パスワードを入力してください。");
					f.userpw.focus();
					return false;
				}

				f.submit();
			}
		</script>
		<div class='row justify-content-sm-center align-items-center' style='margin-top:20px;padding-bottom:20px;'>
			<div class='col-lg-5 col-md-7 col-sm-8 col-xs-12'>
				<form method='post' style='border:1px solid #aaaaaa;border-radius:10px;overflow:hidden;' onsubmit='chksub(this);return false;'>
					<div class="form-group row" style='margin-bottom:0;margin:10px;margin-bottom:20px;'>
						<label for="inputPassword" class="col-sm-4 col-form-label">パスワード</label>
						<div class="col-sm-8">
							<input type="password" name='userpw' class="form-control" id="inputPassword" placeholder="パスワードを入力">
						</div>
					</div>
					<div style='background-color:#dddddd;padding:10px;' class='text-center'>
						<button class='btn btn-danger'>ダウンロード</button>
					</div>
				</form>
			</div>
		</div>

		<div class='row justify-content-sm-center align-items-center text-center' style='padding-top:0px;padding-bottom:50px;height:;'>
			<div class='' style='margin:10px;'>
				パスワードを忘れた方は経営支援部にお知らせください。
			</div>
		</div>

		<script type='text/javascript'>
			document.addEventListener( 'DOMContentLoaded', function(){
				document.getElementById("userid").focus();
			});
		</script>
	</div>


<?php endif?>