<!-- 画面変更
	作成：朴昰成
	修正：朴昰成
	修正日：2027/03/11
-->

<!-- 修正前： <?php /* ?>
<?php
if (!isset($_SESSION)) {
  session_start();
}

$examData = $_SESSION["exam"];

	!* 機能の削除と追加
		作成：朴夏成
		修正：朴夏成
		修正日：2024/02/21
	*!

	!* 修正前：
$level[1] = "初級";
$level[2] = "中級";
$level[3] = "高級";

$levelTitle = "";
switch ($examData["level"]) {
  case 1:
    $levelTitle = "初級";
    break;
  case 2:
    $levelTitle = "中級";
    break;
  case 3:
    $levelTitle = "高級";
    break;
}
	*!

	!* 修正後： *!
	$setQ = $examData["setQuestion"];

	$certificateTexts = array("無", "有");
	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	!* ここまで *!
?>

<div class="p-5 align-self-center w-75">
  <form id="from_exam" method="post">
    <input name="url" type="hidden" value="<?= $rndUrl ?>">
    <input name="id" type="hidden" value="<?= $examData["id"] ?>">
    <input name="password" type="hidden" value="<?= $examData["password"] ?>">
    <input name="name" type="hidden" value="<?= $examData["name"] ?>">
		!-- 機能の削除と追加
			作成：朴夏成
			修正：朴夏成
			修正日：2024/02/21
		--

		!-- 修正前： <?php !* ?>
    <input name="level" type="hidden" value="<?= $examData["level"] ?>">
    <input name="num" type="hidden" value="<?= $examData["num"] ?>">
    <input name="question_data" type="hidden" value="<?= $question_data ?>">
		<?php *! ?> --

		!-- 修正後： --
		<input name="academic" type="hidden" value="<?php echo $examData["academic"]; ?>"/>
		<input name="career" type="hidden" value="<?php echo $examData["career"]; ?>"/>
		<input name="certificates" type="hidden"/>
		<input name="num" type="hidden" value="<?php echo $examData["num"]; ?>"/>

		<?php if ($setQ == "true"): ?>
			<input name="question_data" type="hidden" value="<?php echo $question_data; ?>"/>
		<?php endif; ?>
		!-- ここまで --
  </form>
  <p class="mb-5 h2">試験登録/確認</p>

  <p class="mt-4 mb-3">user information</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">応募者名 : </td>
        <td class="col-4 text-left border-light"><?= $examData["name"] ?></td>

        <td class="col-2 text-right border-light">固有URL :</td>
        <td class="col-4 text-left border-light">gngtest/user/login/<?= $rndUrl ?></td>
      </tr>

      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">ログインID : </td>
        <td class="col-4 text-left border-light"><?= $examData["id"] ?></td>

        <td class="col-2 text-right border-light">パスワード :</td>
        <td class="col-4 text-left border-light"><?= $examData["password"] ?></td>
      </tr>
    </table>
  </div>

	!-- 機能の修正
		作成：朴夏成
		修正：朴夏成
		修正日：2024/02/21
	--

	!-- 修正前： <?php !* ?>
  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">レベル : </td>
        <td class="col-4 text-left border-light"><?= $levelTitle ?></td>

        <td class="col-2 text-right border-light">問題種別 :</td>
        <td class="col-4 text-left border-light"><?= $examData["typeTitle"] ?></td>
      </tr>

      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">問題数 : </td>
        <td class="col-4 text-left border-light"><?= $examData["num"] ?></td>
      </tr>
    </table>

    <div class="d-flex flex-row mb-1 align-items-baseline">
      <table class="table striped mt-3 table-bordered">
        <tr>
          <th class="col-1 bg-secondary text-white">No.</th>
          <th class="col-1 bg-secondary text-white">レベル</th>
          <th class="col-1 bg-secondary text-white">種別</th>
          <th class="col-7 bg-secondary text-white">問題</th>
          <th class="col-2 bg-secondary text-white">登録日</th>
        </tr>

        <?php foreach ($questionDatas as $index => $data) : ?>
          <tr style="cursor: pointer;" onclick="Move2Detail(<?= $data['idx'] ?>)">
            <td><?= $index + 1 ?></td>
            <td><?= $level[$data["question_level"]] ?></td>
            <td><?= $typeTitles[$index] ?></td>
            <td><?= $data["question"] ?></td>
            <td><?= date("Y-m-d", strtotime($data["wdate"])) ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    </div>
  </div>
	<?php *! ?> --

	!-- 修正後： --
	<p>設定</p>
	<div>
		<p>最終学歴 : <?php echo ($examData["academic"] == "") ? "未設定" : $academicTexts[$examData["academic"] / 2]; ?></p>
		<p>
			IT専攻 :  
			<?php if ($examData["academic"] == ""): ?>
				未設定
			<?php else: ?>
				<?php echo (isset($examData["major"])) ? "O" : "X"; ?>
			<?php endif; ?>
		</p>
		<p>種別 : <?php echo ($examData["type"] == "") ? "未設定" : $examData["typeTitle"]; ?></p>
		<p>経歴 : <?php echo ($examData["career"] == "") ? "未設定" : $examData["career"]; ?></p>
		<p>
			資格(IT) : 
			<?php if ($examData["certificate"] == ""): ?>
				<?php if ($setQ == "true"): ?>
					無
				<?php else: ?>
					未設定
				<?php endif; ?>
			<?php else: ?>
				<?php echo $examData["certificates"]; ?>
			<?php endif; ?>
		</p>
		<p>問題数 : <?php echo $examData["num"]; ?></p>
		
		<?php if ($setQ == "true"): ?>
			<table>
				<thead>
					<tr>
						<th>No.</th>
						<th>問題</th>
						<th>登録日</th>
					</tr>
				</thead>

				<tbody>
					<?php foreach ($questionDatas as $index => $data): ?>
						<tr onclick="window.location.href='../../question/list/detail/<?php echo $data['idx'] ?>'">
							<td><?= $index + 1; ?></td>
							<td><?php echo $data["question"]; ?></td>
							<td><?php echo date("Y-m-d", strtotime($data["wdate"])); ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php endif; ?>
	</div>
	!-- ここまで --

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
		!-- 機能の追加
			作成：朴夏成
			修正：朴夏成
			修正日：2024/02/22
		--

		!-- 修正前： <?php !* ?>
    <button class="btn btn-primary" id="bt_regist">登録</button>
    <button class="btn btn-primary" id="bt_return">戻る</button>
		<?php *! ?> --

		!-- 修正後： --
    <button class="btn btn-primary" id="bt_regist" onclick="Submit()">登録</button>
		<button class="btn btn-primary" id="bt_return" onclick="history.back()">戻る</button>
		!-- ここまで --
  </div>
</div>

<script>
	!* 機能の削除と変更
		作成：朴夏成
		修正：朴夏成
		修正日：2024/02/22
	*!

	!* 修正前： <?php !* ?>
  document.getElementById("bt_regist").addEventListener("click", function() {
    var result = confirm("問題を登録しますか？");
    if (result === true) {
      document.getElementById("from_exam").submit();
    }
  });

  document.getElementById("bt_return").addEventListener("click", function() {
    sessionStorage.setItem("return", "exam");
    <?php foreach ($examData as $key => $data) : ?>
      sessionStorage.setItem("<?= $key ?>", "<?= $data ?>");
    <?php endforeach; ?>
    window.location.href = "../register";
  });
	<?php *! ?> *!

	!* 修正後： *!
	const form = document.getElementById("from_exam");

	function Submit() {
		<?php if (isset($examData["certificate"])): ?>
			<?php foreach ($examData["certificate"] as $data): ?>
				form.certificates.value += "<?php echo $data; ?>" + ",";
			<?php endforeach; ?>
			form.certificates.value = form.certificates.value.slice(0, -1);
		<?php endif; ?>

		if (<?php echo isset($examData["major"]) ? "true" : "false"; ?>) {
			form.academic.value = parseInt(form.academic.value) + 1;
		}

		var result = confirm("問題を登録しますか？");
		if (result === true) {
			form.submit();
		}
	}
	!* ここまで *!
</script>
<?php */ ?> -->

<!-- 修正後： -->
<?php
	if (!isset($_SESSION)) { session_start(); }
	
	$examData = $_SESSION["exam"];

	$setQ = $examData["setQuestion"];
	$certificateTexts = array("無", "有");
	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">試験登録/確認</h1>

<div class="emegra card">
		<div class="card-header">応募者情報	</div>

		<div class="card-body">
			<style type="text/css">
				dl.emegra.info { grid-template-columns: repeat(2, 100px 1fr); }
			</style>
			<dl class="emegra info">
				<dt>応募者名</dt>
				<dd><?php echo $examData["name"]; ?></dd>
				
				<dt>固有URL</dt>
				<dd><?php echo $rndUrl; ?></dd>
				
				<dt>ログインID</dt>
				<dd><?php echo $examData["id"]; ?></dd>
				
				<dt>パスワード</dt>
				<dd><?php echo $examData["password"]; ?></dd>
			</dl>
		</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">設定</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.setting { grid-template-columns: repeat(2, 100px 1fr); }
		</style>
		<dl class="emegra setting">
			<div style="grid-column: 1 / 3; display: grid; grid-template-columns: repeat(2, 100px 1fr);">
				<dt>最終学歴</dt>
				<dd><?php echo ($examData["academic"] == "") ? "未設定" : $academicTexts[$examData["academic"] / 2]; ?></dd>
			
				<dt>IT専攻</dt>
				<dd><?php echo (isset($examData["major"])) ? "O" : "X"; ?></dd>
			</div>
			
			<dt>種別</dt>
			<dd><?php echo ($examData["type"] == "") ? "未設定" : $examData["typeTitle"]; ?></dd>
			
			<dt>経歴</dt>
			<dd><?php echo ($examData["career"] == "") ? "未設定" : $examData["career"]; ?></dd>
			
			<dt>問題数</dt>
			<dd><?php echo $examData["num"]; ?></dd>

			<dt>資格(IT)</dt>
			<dd style="grid-column: 2 / 5;">
				<?php if ($examData["certificate"] == ""): ?>
					<?php if ($setQ == "true"): ?>
						無
					<?php else: ?>
						未設定
					<?php endif; ?>
				<?php else: ?>
					<?php echo $examData["certificates"]; ?>
				<?php endif; ?>
			</dd>
		</dl>
		
		<?php if ($setQ == "true"): ?>
			<style text="text/css">
				table.emegra tr { grid-template-columns: 40px 1fr 100px; }
			</style>
			<table class="emegra" style="margin-top: 24px;">
				<thead>
					<tr>
						<th>No.</th>
						<th>問題</th>
						<th>登録日</th>
					</tr>
				</thead>

				<tbody>
					<?php foreach ($questionDatas as $index => $data): ?>
						<tr onclick="window.location.href='../../question/list/detail/<?php echo $data['idx'] ?>'">
							<td><?= $index + 1; ?></td>
							<td style="text-align: left;"><?php echo $data["question"]; ?></td>
							<td><?php echo date("Y-m-d", strtotime($data["wdate"])); ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php endif; ?>
	</div>
</div>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancle" onclick="history.back();">戻る</button>
	<button class="emegra" onclick="submit();">登録</button>
</div>

<form id="form" method="post">
	<input name="name" type="hidden" value="<?php echo $examData["name"]; ?>"/>
	<input name="url" type="hidden" value="<?php echo $rndUrl; ?>"/>
	<input name="id" type="hidden" value="<?php echo $examData["id"]; ?>"/>
	<input name="password" type="hidden" value="<?php echo $examData["password"]; ?>"/>
	<input name="academic" type="hidden" value="<?php echo $examData["academic"]; ?>"/>
	<input name="career" type="hidden" value="<?php echo $examData["career"]; ?>"/>
	<input name="num" type="hidden" value="<?php echo $examData["num"]; ?>"/>
	<input name="certificates" type="hidden" value="<?php echo $examData["certificates"]; ?>"/>
	<?php if ($setQ == "true"): ?>
		<input name="question_data" type="hidden" value="<?php echo $question_data; ?>"/>
	<?php endif; ?>
</form>

<script>
	const form = document.getElementById("form");

	function submit() {
		if (<?php echo isset($examData["major"]) ? "true" : "false"; ?>) {
			form.academic.value = parseInt(form.academic.value) + 1;
		}

		var result = confirm("問題を登録しますか？");
		if (result === true) { form.submit(); }
	}
</script>
<!-- ここまで -->