<?php
if (!isset($_SESSION)) {
  session_start();
}

$examData = $_SESSION["exam"];

	/* 機能の削除と追加
		作成：朴夏成
		修正：朴夏成
		修正日：2024/02/21
	*/

	/* 修正前：
$level[1] = "初級";
$level[2] = "中級";
$level[3] = "高級";

$levelTitle = "";
switch ($examData["level"]) {
  case 1:
    $levelTitle = "初級";
    break;
  case 2:
    $levelTitle = "中級";
    break;
  case 3:
    $levelTitle = "高級";
    break;
}
	*/

	/* 修正後： */
	$certificateTexts = array("無", "有");
	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	/* ここまで */
?>

<div class="p-5 align-self-center w-75">
  <form id="from_exam" method="post">
    <input name="url" type="hidden" value="<?= $rndUrl ?>">
    <input name="id" type="hidden" value="<?= $examData["id"] ?>">
    <input name="password" type="hidden" value="<?= $examData["password"] ?>">
    <input name="name" type="hidden" value="<?= $examData["name"] ?>">
		<!-- 機能の削除と追加
			作成：朴夏成
			修正：朴夏成
			修正日：2024/02/21
		-->

		<!-- 修正前： <?php /* ?>
    <input name="level" type="hidden" value="<?= $examData["level"] ?>">
		<?php */ ?> -->

		<!-- 修正後： -->
		<input name="academic" type="hidden" value="<?= $examData["academic"]; ?>">
		<input name="career" type="hidden" value="<?= $examData["career"]; ?>">
		<input name="certificate" type="hidden" value="<?= $examData["certificate"]; ?>">
		<!-- ここまで -->
    <input name="num" type="hidden" value="<?= $examData["num"] ?>">
    <input name="question_data" type="hidden" value="<?= $question_data ?>">
  </form>
  <p class="mb-5 h2">試験登録/確認</p>

  <p class="mt-4 mb-3">user information</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">応募者名 : </td>
        <td class="col-4 text-left border-light"><?= $examData["name"] ?></td>

        <td class="col-2 text-right border-light">固有URL :</td>
        <td class="col-4 text-left border-light">gngtest/user/login/<?= $rndUrl ?></td>
      </tr>

      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">ログインID : </td>
        <td class="col-4 text-left border-light"><?= $examData["id"] ?></td>

        <td class="col-2 text-right border-light">パスワード :</td>
        <td class="col-4 text-left border-light"><?= $examData["password"] ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
		<!-- 機能の修正
			作成：朴夏成
			修正：朴夏成
			修正日：2024/02/21
		-->

		<!-- 修正前： <?php /* ?>
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">レベル : </td>
        <td class="col-4 text-left border-light"><?= $levelTitle ?></td>

        <td class="col-2 text-right border-light">問題種別 :</td>
        <td class="col-4 text-left border-light"><?= $examData["typeTitle"] ?></td>
      </tr>

      <tr style="height: 50px;">
        <td class="col-2 text-right border-light">問題数 : </td>
        <td class="col-4 text-left border-light"><?= $examData["num"] ?></td>
      </tr>
    </table>

    <div class="d-flex flex-row mb-1 align-items-baseline">
      <table class="table striped mt-3 table-bordered">
        <tr>
          <th class="col-1 bg-secondary text-white">No.</th>
          <th class="col-1 bg-secondary text-white">レベル</th>
          <th class="col-1 bg-secondary text-white">種別</th>
          <th class="col-7 bg-secondary text-white">問題</th>
          <th class="col-2 bg-secondary text-white">登録日</th>
        </tr>

        <?php foreach ($questionDatas as $index => $data) : ?>
          <tr style="cursor: pointer;" onclick="Move2Detail(<?= $data['idx'] ?>)">
            <td><?= $index + 1 ?></td>
            <td><?= $level[$data["question_level"]] ?></td>
            <td><?= $typeTitles[$index] ?></td>
            <td><?= $data["question"] ?></td>
            <td><?= date("Y-m-d", strtotime($data["wdate"])) ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    </div>
		<?php */ ?> -->

		<!-- 修正後： -->
		<p>最終学歴 : <?php echo $academicTexts[$examData["academic"]]; ?></p>
		<p>種別 : <?php echo $examData["typeTitle"]; ?></p>
		<p>経歴 : <?php echo $examData["career"]; ?></p>
		<p>資格(IT) : <?php echo $certificateTexts[$examData["certificate"]]; ?></p>
		<p>問題数 : <?php echo $examData["num"]; ?></p>
		
		<table>
			<thead>
				<tr>
					<th>No.</th>
					<th>最終学歴</th>
					<th>種別</th>
					<th>経歴</th>
					<th>資格(IT)</th>
					<th>問題</th>
					<th>登録日</th>
				</tr>
			</thead>

			<tbody>
				<?php foreach ($questionDatas as $index => $data): ?>
					<tr style="cursor: pointer;" onclick="window.location.href='../../question/list/detail/<?php echo $data['idx'] ?>'">
						<td><?= $index + 1; ?></td>
						<td><?php echo $academicTexts[$data["academic"]]; ?></td>
            <td><?php echo $typeTitles[$index] ?></td>
						<td><?php echo $data["career"]; ?></td>
						<td><?php echo $certificateTexts[$data["certificate"]]; ?></td>
						<td><?php echo $data["question"]; ?></td>
						<td><?php echo date("Y-m-d", strtotime($data["wdate"])); ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<!-- ここまで -->
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="bt_regist">登録</button>
		<!-- 機能の追加
			作成：朴夏成
			修正：朴夏成
			修正日：2024/02/22
		-->

		<!-- 修正前： <?php /* ?>
    <button class="btn btn-primary" id="bt_return">戻る</button>
		<?php */ ?> -->

		<!-- 修正後： -->
		<button class="btn btn-primary" id="bt_return" onclick="history.back()">戻る</button>
		<!-- ここまで -->
  </div>
</div>

<script>
  document.getElementById("bt_regist").addEventListener("click", function() {
    var result = confirm("問題を登録しますか？");
    if (result === true) {
      document.getElementById("from_exam").submit();
    }
  });

	/* 機能の削除
		作成：朴夏成
		削除：朴夏成
		削除日：2024/02/22

	削除前： <?php /* ?>
  document.getElementById("bt_return").addEventListener("click", function() {
    sessionStorage.setItem("return", "exam");
    <?php foreach ($examData as $key => $data) : ?>
      sessionStorage.setItem("<?= $key ?>", "<?= $data ?>");
    <?php endforeach; ?>
    window.location.href = "../register";
  });
	ここまで <?php */ ?> */
</script>