<!-- 機能の削除と追加
	作成：朴夏成
	修正：朴夏成
	修正日：20240/02/22
-->

<!-- 修正前： <?php /* ?>
<?php
$level[1] = "初級";
$level[2] = "中級";
$level[3] = "高級";
?>

<div class="p-5 align-self-center w-75">
  <p class="mb-5 h2">試験一覧</p>
  <table class="table striped mt-5 table-bordered">
    <tr>
      <th class="col-1 bg-secondary text-white">No.</th>
      <th class="col-1 bg-secondary text-white">レベル</th>
      <th class="col-2 bg-secondary text-white">応募者</th>
      <th class="col-2 bg-secondary text-white">登録日</th>
      <th class="col-2 bg-secondary text-white">実施日</th>
      <th class="col-2 bg-secondary text-white">問題数</th>
      <th class="col-2 bg-secondary text-white">得点</th>
    </tr>

    <?php foreach ($examDatas as $idx => $data) : ?>
      <tr style="cursor: pointer;" onclick="Move2Detail(<?= $data['idx'] ?>)">
        <td><?= $dataIndex - $idx ?></td>
        <td><?= $level[$data["question_level"]] ?></td>
        <td><?= $data["name"] ?></td>
        <td><?= date("Y-m-d", strtotime($data["write_date"])) ?></td>
        <td><?php echo $data["execute_date"] == null ? "未対応" : date("Y-m-d", strtotime($data["execute_date"])) ?></td>
        <td><?= $data["question_nums"] ?>問題</td>
        <td><?php echo $data["get_point"] == null ? "未対応" : $data["get_point"] ?></td>
      </tr>
    <?php endforeach; ?>
  </table>

  <nav class="mt-2 d-flex flex-row justify-content-center gap-3">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="list?page=1">first</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != 1 ? "1" : $cPage - 1 ?>">
          <span class=" unclick">&laquo;</span>
        </a>
      </li>
      <?php for ($page = 1; $page <= $totalPage; $page = $page + 1) : ?>
        <li class=" page-item <?php echo $page == $cPage ? "active" : "" ?>">
          <a class="page-link" href="list?page=<?= $page ?>"><?= $page ?></a>
        </li>
      <?php endfor; ?>
      <li class="page-item">
        <a class="page-link" href="list?page=<?php echo $cPage != $totalPage ? $totalPage : $cPage + 1 ?>">
          <span class="unclick">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="list?page=<?= $totalPage ?>">last</a>
      </li>
    </ul>
  </nav>
</div>

<script>
  function Move2Detail(idx) {
    sessionStorage.setItem("listPage", <?= $cPage ?>);
    self.location.href = " ./list/detail/" + idx;
  }
</script>
<?php */ ?> -->

<!-- 修正後： -->
<?php $academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院"); ?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">試験一覧</h1>

<style text="text/css">
	table.emegra tr { grid-template-columns: 40px 3fr 1fr 1fr 2fr 2fr 1fr 1fr; }
</style>
<table class="emegra">
	<thead>
		<tr>
			<th>No.</th>
			<th>最終学歴</th>
			<th>経歴</th>
			<th>応募者</th>
			<th>登録日</th>
			<th>実施日</th>
			<th>問題数</th>
			<th>得点</th>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($examDatas as $idx => $data): ?>
			<tr onclick="self.location.href='./list/detail/<?php echo $data['idx']; ?>'">
				<td><?= $dataIndex - $idx; ?></td>
				<td><?php echo ($data["academic"] == null) ? "未設定" : $academicTexts[$data["academic"]]; ?> <?php echo ($data["academic"] % 2 == 1) ? "IT専攻" : ""; ?></td>
				<td><?php echo ($data["career"] == null) ? "未設定" : $data["career"]; ?></td>
				<td><?php echo $data["name"]; ?></td>
				<td><?php echo date("Y-m-d", strtotime($data["write_date"])); ?></td>
				<td><?php echo ($data["execute_date"] == null) ? "未対応" : date("Y-m-d", strtotime($data["execute_date"])); ?></td>
				<td><?php echo ($data["question_nums"] == null) ? "未設定" : $data["question_nums"]; ?></td>
				<td><?php echo ($data["get_point"] == null) ? "未対応" : $data["get_point"]; ?></td>
				</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div style="margin-top: 32px;">
	<?php echo $this->partial("pagination", $paginationData); ?>
</div>
<!-- ここまで -->