<div class="p-5 align-self-center" style="width: 800px;">
  <p class="mb-5 h2">試験登録</p>
  <form id="form_exam" method="post">
    <input type="hidden" name="typeTitle">
			<!-- 機能の追加
				作成：朴夏成
				作成日：2024/03/01
			-->
    <input type="hidden" name="certificates">
			<!-- ここまで -->

    <p class="mt-4 mb-3">user information</p>
    <div class="p-3 rounded-3 bg-light">
      <div class="d-flex flex-row mb-3   align-items-baseline gap-2">
        <span class="w-25">(*)応募者名</span>
        <input class="form-control" name="name" placeholder="名前を入力してください">
      </div>
      <div class="d-flex flex-row mb-3 align-items-baseline gap-2">
				<!-- 表示するデータの変更
					作成：朴夏成
					修正：朴夏成
					修正前：2024/03/01
				-->

				<!-- 修正前： <?php /* ?>
        <span class="w-25">(*)ログインID</span>
        <input class="form-control" name="id" placeholder="ログインIDを入力してください" value="<?= $rndId ?>">
				<?php */ ?> -->

				<!-- 修正後： -->
        <span class="w-25">(*)ログインID(メイル)</span>
        <input class="form-control" name="id" placeholder="ログインID(メイル)を入力してください">
				<!-- ここまで -->
      </div>
      <div class="d-flex flex-row mb-1 align-items-baseline gap-2">
        <span class="w-25">(*)パスワード</span>
        <input class="form-control" name="password" placeholder="パスワードを入力してください" value="<?= $rndPassword ?>">
      </div>
    </div>

    <p class="mt-4 mb-3">setting</p>
    <div class="p-3 rounded-3 bg-light">
			<!-- 機能の変更
				作成：朴夏成
				修正：朴夏成
				修正日：2024/02/21
			-->

			<!-- 修正前： <?php /* ?>
      <div class="d-flex flex-row mb-3 align-items-baseline gap-2">
        <span class="w-25">(*)レベル</span>
        <select class="form-select w-50" name="level">
          <option value=1>初級</option>
          <option value=2>中級</option>
          <option value=3>高級</option>
        </select>

        <span class="w-25">(*)問題種別</span>
        <select class="form-select w-50" name="type">
          <?php foreach ($types as $type) : ?>
          <option value="<?= $type["question_type"] ?>"><?= $type["question_title"] ?></option>
          <?php endforeach; ?>
        </select>
      </div>
			<?php */ ?> -->

			<!-- 修正後： -->
			<style type="text/css">
				.essential:before { content: "(*)"; }
				.essential.not:before { content: ""; }
			</style>

			<input type="radio" name="setQuestion" id="set" value="true" onclick="chkSetQuestion(event)" checked="checked"/><label for="set">問題出題後配信（試験画面へ）</label><br/>
			<input type="radio" name="setQuestion" id="unset" value="false" onclick="chkSetQuestion(event)"/><label for="unset">情報確認後試験（情報確認画面へ）</label>

			<div id="setting_place">
				<span class="essential">最終学歴</span>
				<select name="academic">
					<option value="" selected disabled hidden>選択してください</option>
					<option value=1>高等学校</option>
					<option value=2>専門学校</option>
					<option value=3>短期大学</option>
					<option value=4>大学</option>
					<option value=5>大学院</option>
					<option value=0>その他</option>
				</select>

				<input type="checkbox" name="major"/>IT専攻
			
				<br/>
			
				<span class="essential">問題種別</span>
				<select name="type">
					<option value="" selected disabled hidden>選択してください</option>
					<?php foreach ($types as $type): ?>
						<option value="<?php echo $type["question_type"]; ?>"><?php echo $type["question_title"]; ?></option>
					<?php endforeach; ?>
				</select>
			
				<br/>
			
				<span class="essential">経歴</span>
				<input class="form-control" name="career" placeholder="年単位に数字だけ入力してください。">
			
				<br/>
			
				<span>資格</span>
				<button type="button" onclick="addCertificate()">+</button>
				<div id="place-certificate">
				</div>	
			<!-- ここまで -->

      <div class="d-flex flex-row mb-1 align-items-baseline">
        <span class="w-25">(*)問題数</span>
        <select class="form-select" name="num">
          <option value=10>10</option>
          <option value=20>20</option>
        </select>
      </div>
			<!-- div追加
				作成：朴夏成
				作成日：2024/02/27
			-->
			</div>
			<!-- ここまで -->
    </div>
  </form>
  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="bt_confirm">次へ</button>
    <button class="btn btn-primary" onclick="window.location.href='./list?page=1'">キャンセル</button>
  </div>
</div>

<script>
const form = document.getElementById("form_exam")
	/* 機能の追加と削除
		作成：朴夏成
		修正：朴夏成
		修正日：2024/02/21
	*/

	/* 修正前： <?php /* ?>
if (sessionStorage.getItem("return") == "exam") {
  sessionStorage.removeItem("return");
  form.name.value = sessionStorage.getItem("name");
  form.id.value = sessionStorage.getItem("id");
  form.password.value = sessionStorage.getItem("password");
  form.level.value = sessionStorage.getItem("level");
  form.type.value = sessionStorage.getItem("type");
  form.num.value = sessionStorage.getItem("num");
}
	<?php */ ?> */

	/* 修正後： */
	HTMLCollection.prototype.forEach = Array.prototype.forEach;
	const essentials = document.getElementsByClassName("essential");
	const certificatePlace = document.getElementById("place-certificate");

	function chkSetQuestion(event) {
		if (event.target.value == "false") {
			essentials.forEach(element => { element.classList.add("not"); })
		}
		else if (event.target.value == "true") {
			essentials.forEach(element => { element.classList.remove("not"); })
		}
	}

	function addCertificate() {
		const newDiv = document.createElement("div");
		newDiv.innerHTML =
			"<input class='form-control' name='certificate[]' placeholder='資格の名を入力してください。'>" +
			"<button type='button' onclick='event.target.parentNode.remove();'>-</button>";
		certificatePlace.appendChild(newDiv);
	}
	/* ここまで */

document.getElementById("bt_confirm").addEventListener("click", () => {
  if ((form.name.value.trim()) == "") {
    alert("名前を入力してください。");
    form.name.focus();
    return false;
  }

  if ((form.id.value.trim()) == "") {
    alert("ログインIDを入力してください。");
    form.id.focus();
    return false;
  }

  if ((form.password.value.trim()) == "") {
    alert("パスワードを入力してください。");
    form.password.focus();
    return false;
  }

		/* 機能の変更と追加
			作成：朴夏成
			作成日：2024/02/21
		*/

		/* 修正前：
  form.typeTitle.value = form.type.options[form.type.selectedIndex].text;
		*/

		/* 修正後： */
		if (form.setQuestion.value == "true") {
			if (form.academic.value == "") {
				alert("学歴を選択してください。");
				form.academic.focus();
				return false;
			}
		
			if (form.type.value == "") {
				alert("問題種別を選択してください。");
				form.type.focus();
				return false;
			}

			if (form.career.value.trim() == "") {
				alert("経歴を入力してください。");
				form.career.focus();
				return false;
			}
		}

		if (isNaN(form.career.value)) {
			alert("経歴に数字だけ入力してください。");
			form.career.focus();
			return false;
		}

		var certificates = document.getElementsByName("certificate");
		for (let i = 0; i < certificates.length; i++) {
			if (certificates[i].value.trim() == "") {
				alert("資格を入力してください。");
				certificates[i].focus();
				return false;
			}
			else { certificates[i].value = certificates[i].value.trim(); }
		}

		form.typeTitle.value = form.type.options[form.type.selectedIndex].text;
		/* ここまで */
  form.submit();
});
</script>