<!-- 画面の変更
	作成：丁錫圓
	修正：朴昰成
	作成日：2024
-->

<!-- 修正前： <?php /* ?>
!-- html修正
作成：丁錫圓
作成日：2024/02/21 --
!-- 修正前：<?php !* ?>
<?php
if (!isset($_SESSION)) {
  session_start();
}

$questionData = $_SESSION["question"];

$levelTitle = "";
switch ($questionData["level"]) {
  case 1:
    $levelTitle = "初級";
    break;
  case 2:
    $levelTitle = "中級";
    break;
  case 3:
    $levelTitle = "高級";
    break;
}

$nums[1] = "①";
$nums[2] = "②";
$nums[3] = "③";
$nums[4] = "④";
$nums[5] = "⑤";
?>

<form id="form_question" method="post">
  <input name="type" type="hidden" value="<?= $questionData["type"] ?>">
  <input name="level" type="hidden" value="<?= $questionData["level"] ?>">
  <input name="question" type="hidden" value="<?= $questionData["question"] ?>">
  <input name="answer1" type="hidden" value="<?= $questionData["answer1"] ?>">
  <input name="answer2" type="hidden" value="<?= $questionData["answer2"] ?>">
  <input name="answer3" type="hidden" value="<?= $questionData["answer3"] ?>">
  <input name="answer4" type="hidden" value="<?= $questionData["answer4"] ?>">
  <input name="answer5" type="hidden" value="<?= $questionData["answer5"] ?>">
  <input name="correct" type="hidden" value="<?= $questionData["correct"] ?>">
</form>

<div class="p-5 align-self-center" style="width: 800px;">

  <p class="mb-5 h2">問題登録/確認</p>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-3 text-right border-light">問題種別 : </td>
        <td class="col-3 text-left border-light"><?= $questionData["typeTitle"] ?></td>

        <td class="col-3 text-right border-light">レベル :</td>
        <td class="col-3 text-left border-light"><?= $levelTitle ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">question</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">問題 : </td>
        <td class="col-10 text-left"><?= $questionData["question"] ?></td>
      </tr>
      <?php
      for ($i = 1; $i <= 5; $i++) :
        if ($questionData["answer" . $i] != "") :
      ?>
      <tr style="height: 50px;">
        <td class="col-2 text-right"><?= $nums[$i] ?> :</td>
        <td class="col-10 text-left"><?= $questionData["answer" . $i] ?></td>
      </tr>
      <?php
        endif;
      endfor;
      ?>
    </table>
  </div>

  <p class="mt-4 mb-3">correct</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">正解番号 :</td>
        <td class="col-10 text-left"><?= $questionData["correct"] ?></td>
      </tr>
    </table>
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="regist-bt">登録</button>
    <button class="btn btn-primary" id="return-bt">戻る</button>
  </div>
</div>

<script>
document.getElementById("regist-bt").addEventListener("click", function() {
  var result = confirm("問題を登録しますか？");
  if (result === true) {
    document.getElementById("form_question").submit();
  }
});

document.getElementById("return-bt").addEventListener("click", function() {
  sessionStorage.setItem("return", "question");
  <?php foreach ($questionData as $key => $data) : ?>
  sessionStorage.setItem("<?= $key ?>", "<?= $data ?>");
  <?php endforeach; ?>
  window.location.href = "../register";
});
</script>
<?php *! ?> --
!-- 修正後： --
<?php
if (!isset($_SESSION)) {
  session_start();
}

$questionData = $_SESSION["question"];

	!* 値の変更とデバッグ
		作成：丁錫圓
		修正：朴昰成
		修正日：2024/03/08
	*!

	!* 修正前：
$academicTitle = "";
switch ($questionData["academic"]) {
  case 0:
    $academicTitle = "その他";
    break;
  case 1:
    $academicTitle = "高等学校";
    break;
  case 2:
    $academicTitle = "専門学校";
    break;
  case 3:
    $academicTitle = "短期大学";
    break;  
  case 4:
    $academicTitle = "大学";
    break;  
  case 5:
    $academicTitle = "大学院";
    break;    
}
	*!
	
	!* 修正後： *!
	$academicText = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	!* ここまで *!


$certificateTitle=array("無","有");

$nums[1] = "①";
$nums[2] = "②";
$nums[3] = "③";
$nums[4] = "④";
$nums[5] = "⑤";
?>

<form id="form_question" method="post">
  <input name="type" type="hidden" value="<?= $questionData["type"] ?>">
  <input name="academic" type="hidden" value="<?= $questionData["academic"] ?>">
  <input name="career" type="hidden" value="<?= $questionData["career"] ?>">
  <input name="certificate" type="hidden" value="<?= $questionData["certificate"] ?>">
  <input name="question" type="hidden" value="<?= $questionData["question"] ?>">
  <input name="answer1" type="hidden" value="<?= $questionData["answer1"] ?>">
  <input name="answer2" type="hidden" value="<?= $questionData["answer2"] ?>">
  <input name="answer3" type="hidden" value="<?= $questionData["answer3"] ?>">
  <input name="answer4" type="hidden" value="<?= $questionData["answer4"] ?>">
  <input name="answer5" type="hidden" value="<?= $questionData["answer5"] ?>">
  <input name="correct" type="hidden" value="<?= $questionData["correct"] ?>">
</form>

<div class="p-5 align-self-center" style="width: 800px;">

  <p class="mb-5 h2">問題登録/確認</p>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-3 text-right border-light">問題種別 : </td>
        <td class="col-3 text-left border-light"><?= $questionData["typeTitle"] ?></td>

        <td class="col-3 text-right border-light">アカデミック :</td>
				!-- 値の変更と機能の追加	
					作成：丁錫圓
					修正：朴昰成
					修正日：2024/03/08
				--

				!-- 修正前： <?php !* ?>
        <td class="col-3 text-left border-light"><?= $academicTitle ?></td>
				<?php *! ?> --

				!-- 修正後： --
        <td class="col-3 text-left border-light"><?= $academicText[$questionData["academic"] / 2]; ?></td>
				<td>IT専攻 : <?php echo (isset($questionData["major"])) ? "O" : "X"; ?></td>
				!-- ここまで --

        <td class="col-3 text-right border-light">キャリア :</td>
        <td class="col-3 text-left border-light"><?= $questionData['career'] ?>年</td>
        
        <td class="col-3 text-right border-light">資格(IT) :</td>
        <td class="col-3 text-left border-light"><?= $certificateTitle[$questionData["certificate"]] ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">question</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">問題 : </td>
        <td class="col-10 text-left"><?= $questionData["question"] ?></td>
      </tr>
      <?php
      for ($i = 1; $i <= 5; $i++) :
        if ($questionData["answer" . $i] != "") :
      ?>
      <tr style="height: 50px;">
        <td class="col-2 text-right"><?= $nums[$i] ?> :</td>
        <td class="col-10 text-left"><?= $questionData["answer" . $i] ?></td>
      </tr>
      <?php
        endif;
      endfor;
      ?>
    </table>
  </div>

  <p class="mt-4 mb-3">correct</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">正解番号 :</td>
        <td class="col-10 text-left"><?= $questionData["correct"] ?></td>
      </tr>
    </table>
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="regist-bt">登録</button>
    <button class="btn btn-primary" id="return-bt" onclick="history.back()">戻る</button>
  </div>
</div>

<script>
document.getElementById("regist-bt").addEventListener("click", function() {
  var result = confirm("問題を登録しますか？");
  if (result === true) {
    document.getElementById("form_question").submit();
  }
});

</script>
!-- ここまで --
<?php */ ?> -->

<!-- 修正後： -->
<!-- html修正
作成：丁錫圓
作成日：2024/02/21 -->
<!-- 修正前：<?php /* ?>
<?php
if (!isset($_SESSION)) {
  session_start();
}

$questionData = $_SESSION["question"];

$levelTitle = "";
switch ($questionData["level"]) {
  case 1:
    $levelTitle = "初級";
    break;
  case 2:
    $levelTitle = "中級";
    break;
  case 3:
    $levelTitle = "高級";
    break;
}

$nums[1] = "①";
$nums[2] = "②";
$nums[3] = "③";
$nums[4] = "④";
$nums[5] = "⑤";
?>

<form id="form_question" method="post">
  <input name="type" type="hidden" value="<?= $questionData["type"] ?>">
  <input name="level" type="hidden" value="<?= $questionData["level"] ?>">
  <input name="question" type="hidden" value="<?= $questionData["question"] ?>">
  <input name="answer1" type="hidden" value="<?= $questionData["answer1"] ?>">
  <input name="answer2" type="hidden" value="<?= $questionData["answer2"] ?>">
  <input name="answer3" type="hidden" value="<?= $questionData["answer3"] ?>">
  <input name="answer4" type="hidden" value="<?= $questionData["answer4"] ?>">
  <input name="answer5" type="hidden" value="<?= $questionData["answer5"] ?>">
  <input name="correct" type="hidden" value="<?= $questionData["correct"] ?>">
</form>

<div class="p-5 align-self-center" style="width: 800px;">

  <p class="mb-5 h2">問題登録/確認</p>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-3 text-right border-light">問題種別 : </td>
        <td class="col-3 text-left border-light"><?= $questionData["typeTitle"] ?></td>

        <td class="col-3 text-right border-light">レベル :</td>
        <td class="col-3 text-left border-light"><?= $levelTitle ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">question</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">問題 : </td>
        <td class="col-10 text-left"><?= $questionData["question"] ?></td>
      </tr>
      <?php
      for ($i = 1; $i <= 5; $i++) :
        if ($questionData["answer" . $i] != "") :
      ?>
      <tr style="height: 50px;">
        <td class="col-2 text-right"><?= $nums[$i] ?> :</td>
        <td class="col-10 text-left"><?= $questionData["answer" . $i] ?></td>
      </tr>
      <?php
        endif;
      endfor;
      ?>
    </table>
  </div>

  <p class="mt-4 mb-3">correct</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">正解番号 :</td>
        <td class="col-10 text-left"><?= $questionData["correct"] ?></td>
      </tr>
    </table>
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="regist-bt">登録</button>
    <button class="btn btn-primary" id="return-bt">戻る</button>
  </div>
</div>

<script>
document.getElementById("regist-bt").addEventListener("click", function() {
  var result = confirm("問題を登録しますか？");
  if (result === true) {
    document.getElementById("form_question").submit();
  }
});

document.getElementById("return-bt").addEventListener("click", function() {
  sessionStorage.setItem("return", "question");
  <?php foreach ($questionData as $key => $data) : ?>
  sessionStorage.setItem("<?= $key ?>", "<?= $data ?>");
  <?php endforeach; ?>
  window.location.href = "../register";
});
</script>
<?php */ ?> -->

<!-- 修正後： -->
<?php
	if (!isset($_SESSION)) { session_start(); }
	$questionData = $_SESSION["question"];

	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	$certificateTexts = array("無", "有");
	$numTexts = array("①", "②", "③", "④", "⑤");
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">問題登録/確認</h1>

<div class="emegra card">
	<div class="card-header">設定</div>
	
	<div class="card-body">
		<style type="text/css">
			dl.emegra.setting { grid-template-columns: repeat(2, 100px 1fr); }
		</style>
		<dl class="emegra setting">
			<dt>問題種別</dt>
			<dd><?php echo $questionData["typeTitle"]; ?></dd>

			<div style="grid-column: 3 / 5; display: grid; grid-template-columns: repeat(2, 100px 1fr);">
				<dt>最後学歴</dt>
				<dd><?php echo $academicTexts[$questionData["academic"] / 2]; ?>

				<dt>IT専攻</dt>
				<dd><?php echo (isset($questionData["major"])) ? "O" : "X"; ?></dd>
			</div>

			<dt>資格(IT)</dt>
			<dd><?php echo $certificateTexts[$questionData["certificate"]]; ?></dd>

			<dt>履歴</dt>
			<dd><?php echo $questionData["career"]; ?>年</dd>
		</dl>
	</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">問題</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.question { grid-template-columns: 100px 1fr; }
		</style>

		<dl class="emegra question">
			<dt>問題</dt>
			<dd><?php echo $questionData["question"]; ?></dd>

			<?php for ($i = 1;  $i <= 5; $i++): ?>
				<?php if ($questionData["answer" . $i] != ""): ?>
					<dt><?= $numTexts[$i - 1]; ?></dt>
					<dd><?php echo $questionData["answer" . $i] ?></dd>
				<?php endif; ?>
			<?php endfor; ?>

			<dt>正解番号</dt>
			<dd><?php echo $questionData["correct"]; ?></dd>
		</dl>
	</div>
</div>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back();">戻る</button>
	<button class="emegra" onclick="submit();">登録</button>
</div>

<form id="form" method="post">
	<input name="type" type="hidden" value="<?php echo $questionData["type"]; ?>">
	<input name="academic" type="hidden" value="<?php echo $questionData["academic"]; ?>">
	<input name="career" type="hidden" value="<?php echo $questionData["career"]; ?>">
	<input name="certificate" type="hidden" value="<?php echo $questionData["certificate"]; ?>">
	<input name="question" type="hidden" value="<?php echo $questionData["question"]; ?>">
	<input name="answer1" type="hidden" value="<?php echo $questionData["answer1"]; ?>">
	<input name="answer2" type="hidden" value="<?php echo $questionData["answer2"]; ?>">
	<input name="answer3" type="hidden" value="<?php echo $questionData["answer3"]; ?>">
	<input name="answer4" type="hidden" value="<?php echo $questionData["answer4"]; ?>">
	<input name="answer5" type="hidden" value="<?php echo $questionData["answer5"]; ?>">
	<input name="correct" type="hidden" value="<?php echo $questionData["correct"]; ?>">
</form>

<script>
	const form = document.getElementById("form");

	function submit() {
		if (<?php echo isset($questionData["major"]) ? "true" : "false"; ?>) {
			form.academic.value = parseInt(form.academic.value) + 1;
		}

		var result = confirm("問題を登録しますか？");
		if (result === true) { form.submit(); }
	}
</script>
<!-- ここまで -->