<!-- 画面変更
	作成：朴昰成
	修正：朴昰成
	修正日：2027/03/12
-->

<!-- 修正前： <?php /* ?>
!-- 
html修正
作成日：2024/02/22
--
!--修正前：　<?php !*?> 
<?php
$level[1] = "初級";
$level[2] = "中級";
$level[3] = "高級";

$answers = explode("|", $questionData["answers"]);

$nums[0] = "①";
$nums[1] = "②";
$nums[2] = "③";
$nums[3] = "④";
$nums[4] = "⑤";
?>

<div class="p-5 align-self-center" style="width: 800px;">

  <p class="mb-5 h2">問題詳細</p>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-3 text-right border-light">問題種別 : </td>
        <td class="col-3 text-left border-light"><?= $typeData["question_title"] ?></td>

        <td class="col-3 text-right border-light">レベル :</td>
        <td class="col-3 text-left border-light"><?= $level[$questionData["question_level"]] ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">question</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">問題 : </td>
        <td class="col-10 text-left"><?= $questionData["question"] ?></td>
      </tr>
      <?php foreach ($answers as $index => $answer) : ?>
      <tr style="height: 50px;">
        <td class="col-2 text-right"><?= $nums[$index] ?> :</td>
        <td class="col-10 text-left"><?= $answer ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>

  <p class="mt-4 mb-3">correct</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">正解番号 :</td>
        <td class="col-10 text-left"><?= $questionData["correct_answer"] ?></td>
      </tr>
    </table>
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="return-bt">戻る</button>
  </div>
</div>

<script>
document.getElementById("return-bt").addEventListener("click", function() {
  let page = sessionStorage.getItem("listPage");
  window.location.href = "/admin/question/list?page=" + page;
});
</script>
<?php *! ?> --
!-- 修正後： --
<?php
$level[1] = "その他";
$level[2] = "高等学校";
$level[3] = "専門学校";
$level[4] = "短期大学";
$level[5] = "大学";
$level[6] = "大学院";

$answers = explode("|", $questionData["answers"]);

$nums[0] = "①";
$nums[1] = "②";
$nums[2] = "③";
$nums[3] = "④";
$nums[4] = "⑤";
?>

<div class="p-5 align-self-center" style="width: 800px;">

  <p class="mb-5 h2">問題詳細</p>

  <p class="mt-4 mb-3">setting</p>
  <div class="p-3 rounded-3 bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-3 text-right border-light">問題種別 : </td>
        <td class="col-3 text-left border-light"><?= $typeData["question_title"] ?></td>

        <td class="col-3 text-right border-light">アカデミック :</td>
				!-- 表示するデータの変更
					作成：丁錫圓
					修正：朴昰成
					修正日：2024/03/08
				--

				!-- 修正前： <?php !* ?>
        <td class="col-3 text-left border-light"><?= $level[$questionData["academic"]] ?></td>
				<?php *! ?> --

				!-- 修正前： --
        <td class="col-3 text-left border-light">
					<?php echo $level[$questionData["academic"] / 2]; ?>
					<?php echo ($questionData["academic"] % 2 == 1) ? "" : "&nbspIT専攻"; ?>
				</td>
				!-- ここまで --

        <td class="col-3 text-right border-light">キャリア :</td>
        <td class="col-3 text-left border-light"><?= $questionData["career"] ?></td>
        
        <td class="col-3 text-right border-light">資格(IT) :</td>
        <td class="col-3 text-left border-light"><?= $questionData["certificate"] ?></td>
      </tr>
    </table>
  </div>

  <p class="mt-4 mb-3">question</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">問題 : </td>
        <td class="col-10 text-left"><?= $questionData["question"] ?></td>
      </tr>
      <?php foreach ($answers as $index => $answer) : ?>
      <tr style="height: 50px;">
        <td class="col-2 text-right"><?= $nums[$index] ?> :</td>
        <td class="col-10 text-left"><?= $answer ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>

  <p class="mt-4 mb-3">correct</p>
  <div class="p-3 rounded-3 d-flex flex-column bg-light">
    <table class="w-100">
      <tr style="height: 50px;">
        <td class="col-2 text-right">正解番号 :</td>
        <td class="col-10 text-left"><?= $questionData["correct_answer"] ?></td>
      </tr>
    </table>
  </div>

  <div class="mt-2 d-flex flex-row justify-content-center gap-3">
    <button class="btn btn-primary" id="return-bt">戻る</button>
  </div>
</div>

<script>
document.getElementById("return-bt").addEventListener("click", function() {
  let page = sessionStorage.getItem("listPage");
  window.location.href = "/admin/question/list?page=" + page;
});
</script>
!-- ここまで --
<?php */ ?> -->

<!-- 修正後： -->
<?php
	$academicTexts = array("その他", "高等学校", "専門学校", "短期大学", "大学", "大学院");
	$answers = explode("|", $questionData["answers"]);
	$numTexts = array("①", "②", "③", "④", "⑤");
?>

<?php echo $this->partial("breadcrumb", ["datas" => $breadcrumbData]); ?>

<h1 class="title">問題詳細</h1>

<div class="emegra card">
	<div class="card-header">設定</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.setting { grid-template-columns: repeat(2, 80px 1fr); }
		</style>
		<dl class="emegra setting">
			<dt>問題種別</dt>
			<dd><?php echo $typeData["question_title"]; ?></dd>

			<dt>学歴</dt>
			<dd>
				<?php echo $academicTexts[$questionData["academic"] / 2]; ?>
				<?php echo ($questionData["academic"] % 2 == 1) ? "" : "&nbspIT専攻"; ?>
			</dd>
		
			<dt>履歴</dt>
			<dd><?php echo $questionData["career"]; ?></dd>
		
			<dt>資格(IT)</dt>
			<dd><?php echo $questionData["certificate"]; ?></dd>
		</dl>
	</div>
</div>

<div class="emegra card" style="margin-top: 32px;">
	<div class="card-header">問題</div>

	<div class="card-body">
		<style type="text/css">
			dl.emegra.question { grid-template-columns: 80px 1fr; }
		</style>
		<dl class="emegra question">
			<dt>問題</dt>
			<dd><?php echo $questionData["question"]; ?></dd>

			<?php foreach ($answers as $index => $answer): ?>
				<dt><?= $numTexts[$index]; ?></dt>
				<dd><?php echo $answer; ?></dd>
			<?php endforeach; ?>

			<dt>正解番号</dt>
			<dd><?php echo $questionData["correct_answer"]; ?></dd>

		</dl>
	</div>
</div>

<div class="btn-place" style="margin-top: 32px;">
	<button class="emegra cancel" onclick="history.back();">戻る</button>
</div>
<!-- ここまで -->