<!-- 構造の改善
	作成：朴昰成
	作成日：2024/03/08
-->
<?php
	if (!isset($_SESSION)) { session_start(); }
	if (!isset($_SESSION["user"]) || !isset($_SESSION["user"]["id"])) {
		echo "<script>
			alert('ログインをしてください。');
			self.location.href='/admin/login';
		</script>";
	}
	else { $userData = $_SESSION["user"]; }

	echo $this->doctype();
	$url = explode("/", $_SERVER["REQUEST_URI"]);
	$mainMenu = $url[2];
	$subMenu = explode("?", $url[3])[0];

	if ($this->title == "") {
		$this->title = "G&GService";
	}

	$breadcrumb = json_decode($this->breadcrumb, true);
	$submenuArray = json_decode($this->submenuArray, true);
?>

<html lang="jp">
	<head>
		<meta charset="utf-8">	
		<?php
			echo $this->headTitle($this->title)->setSeparator(" - ")->setAutoEscape(false);
			
			echo $this->headMeta()
				->appendName("title", $this->title)
				->appendName("description", $this->description)
				->appendName("keywords", $this->keywords)
				->appendName("robots", "ALL")
				->appendName("Distribution", "GNGService")
				->appendName("author", "drapiece@gngs.co.jp")
				->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
				->appendHttpEquiv("X-UA-Compatible", "IE=edge");
		?>
		<meta name="viewport" content="height=device-height">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="/css/emegra-admin.css" rel="stylesheet" type="text/css">
	</head>

	<body>
		<header>
			<div class="logo">
				<img src="/img/hd_logo.png" alt="logo" height="43px" width="auto" style="margin-left: 39px;"/>
				<a class="logo-title">調達管理システム<small>Ver 0.9</small></a>
			</div>

			<div class="status">
				<p style="margin-right: 16px;">ないない様</p>
				<p style="margin-right: 24px;"> 前回のログイン:yyyy/mm/dd HH:mm</p>
				<a style="margin-right: 32px; display: flex; flex-direction: row; cursor: pointer;" onclick="logout();">
					<img src="/img/ic_logout.svg" alt="logout" width="auto" style="margin-right: 4px;"/>
					ログアウト
				</a>
			</div>
		</header>

		<nav>
			<button class="btn-main<?php echo ($mainMenu == "exam") ? " active" : ""; ?>" onclick="self.location.href='/admin/exam/list'">応募者状況管理</button>
			<button class="btn-main<?php echo ($mainMenu == "question") ? " active" : ""; ?>" onclick="self.location.href='/admin/question/list'">問題管理</button>
		</nav>

		<aside>
			<?php foreach($submenuArray as $key => $urls): ?>
				<button class="btn-sub<?php echo (in_array($subMenu, $urls)) ? " active" : ""; ?>" onclick="self.location.href='/admin/<?php echo $mainMenu . '/' . $urls[0]; ?>'">
					<?php echo $key; ?>
				</button>
			<?php endforeach; ?>
		</aside>
		
		<main>
			<?php echo $this->content; ?>
		</main>

		<form id="form_logout" action="/admin/logout" method="post"></form>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
		<script>
			function logout() { document.getElementById("form_logout").submit(); }
		</script>
	</body>
</html>
<!-- ここまで -->