<?php
	echo $this->doctype();

	if ($this->title == "") { $this->title = "G&GService"; }
?>

<html lang="jp">
	<head>
		<meta charset="utf-8">	
		<?php
			echo $this->headTitle($this->title)->setSeparator(" - ")->setAutoEscape(false);
			
			echo $this->headMeta()
				->appendName("title", $this->title)
				->appendName("description", $this->description)
				->appendName("keywords", $this->keywords)
				->appendName("robots", "ALL")
				->appendName("Distribution", "GNGService")
				->appendName("author", "drapiece@gngs.co.jp")
				->appendName("viewport", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
				->appendHttpEquiv("X-UA-Compatible", "IE=edge");
		?>
		<meta name="viewport" content="height=device-height">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="/css/emegra-login.css" rel="stylesheet" type="text/css">
		<style type="text/css">
			body { background: linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); }
		</style>
	</head>

	<body class="login">
		<div class="vector" id="vector"></div>
		<div class="gngLogo_back"></div>
		<header class="logo">
			<img src="/img/hd_logo.png" alt="logo" height="64px" width="auto"/>
			<a class="logo-title">ITスキル診断システム<small><small> Ver 0.11</small></small></a>
		</header>
			
		<main>
			<div class="emegra card">
				<div class="card-header">G&G Service 診断管理</div>

				<div class="card-body">
          <!-- Add Enter Event
            作成：朴昰成
            修正：朴昰成
            修正日：24/05/27
          -->

          <!-- 修正前： <?php /* ?>
            <span>ログインID</span>
            <input class="form-control" id="id" type="text" placeholder="IDを入力ください（自分のメール）">

            <span style="margin-top: 24px">パスワード</span>
            <input class="form-control" id="password" type="password" placeholder="パスワードを入力ください">
          <?php */ ?> -->

          <!-- 修正後： -->
          <span>ログインID</span>
          <input class="form-control" id="id" type="text" placeholder="IDを入力ください（自分のメール）" onkeypress="Enter(event);">

          <span style="margin-top: 24px">パスワード</span>
          <input class="form-control" id="password" type="password" placeholder="パスワードを入力ください" onkeypress="Enter(event);">
          <!-- ここまで -->

					<style type="text/css">
						button.emegra { background: linear-gradient(111deg, #50D7C7 0%, #40ADF0 100%); }
						button.emegra:hover { background: #44B0DA; }
					</style>
					<button class="emegra" style="margin-top: 40px;" onclick="submit();">ログイン</button>
				</div>
			</div>
		</main>

		<footer class="descript"><a>GOMS Order・Received・Service.</a> Copyright G&GService. All Right Reserved.</footer>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
		<script type="text/javascript">
			const id = document.getElementById("id");
			const password = document.getElementById("password");
			const url = window.location.href.split("/");

      /* Add Enter Event
        作成：朴昰成
        作成日：24/05/27
      */
      function Enter(event) {
        if (event.code == "Enter") { submit(); }
      }

      /* ここまで */
			function submit() {
				if (id.value == "") {
					alert("IDを入力ください");
					id.focus();
					return false;
				}

				if (password.value == "") {
					alert("パスワードを入力ください");
					password.focus();
					return false;
				}

				const postForm = new FormData();
				postForm.append("id", id.value);
				postForm.append("password", password.value);

				const xhr = new XMLHttpRequest();
				xhr.open("POST", "account/login", true);
				xhr.send(postForm);

				xhr.onload = () => {
					if (xhr.status == 200) {
						const result = xhr.responseText;
						if (result == "fail") {
							alert("IDとパスワードを確認してくたさい");
							id.focus();
							return false;
						}
						if (result == "success") { self.location.href = "question/list"; }
						else {
							console.log(result);
						}
					}
				}
			}
		</script>
	</body>
</html>